#!/usr/bin/env bash
set -Eeuo pipefail

ROOT="${1:-/root/hyper-hosting-panel}"
SID="${2:-25}"
PUBLIC="90.189.208.25"
LAN="192.168.0.179"
SRC_CTL="$ROOT/cs16-panel/bin/hyper-cs16-ctl"
LIVE_CTL="/usr/local/sbin/hyper-cs16-ctl"
SERVER_ROOT="/srv/hyper-cs16/servers/$SID"
CSTRIKE="$SERVER_ROOT/cstrike"
FASTDL="/srv/hyper-cs16/fastdl/$SID"
STAMP="$(date +%Y%m%d-%H%M%S)"
BACKUP="/root/hyper-cs16-fastdl-final-v8-${STAMP}"

[[ ${EUID:-$(id -u)} -eq 0 ]] || { echo "[ERROR] run as root"; exit 1; }
[[ -f "$SRC_CTL" ]] || { echo "[ERROR] missing controller: $SRC_CTL"; exit 2; }
[[ -d "$CSTRIKE/maps" ]] || { echo "[ERROR] missing maps directory: $CSTRIKE/maps"; exit 2; }

mkdir -p "$BACKUP"
cp -a "$SRC_CTL" "$BACKUP/hyper-cs16-ctl.repo"
[[ -f "$LIVE_CTL" ]] && cp -a "$LIVE_CTL" "$BACKUP/hyper-cs16-ctl.live"
[[ -f "$CSTRIKE/server.cfg" ]] && cp -a "$CSTRIKE/server.cfg" "$BACKUP/server.cfg"

echo "================================================================"
echo " HYPER-HOST FASTDL FINAL v8"
echo " Server: #$SID"
echo " URL:    http://$PUBLIC/fastdl/$SID/"
echo " Backup: $BACKUP"
echo "================================================================"

echo "[1/10] Validate SOURCE BSP files..."
python3 - "$CSTRIKE/maps" <<'PY'
from pathlib import Path
import sys
root=Path(sys.argv[1])
good=[]; bad=[]
for p in sorted(root.glob('*.bsp')):
    try:
        with p.open('rb') as f:
            head=f.read(4)
        ver=int.from_bytes(head,'little') if len(head)==4 else None
        if ver==30:
            good.append(p.name)
        else:
            bad.append((p.name,ver,head.hex(),p.stat().st_size))
    except Exception as e:
        bad.append((p.name,None,str(e),0))
print("valid BSP:",len(good))
print("bad BSP:",len(bad))
if bad:
    for x in bad[:50]: print("BAD",x)
    raise SystemExit(20)
PY

echo "[2/10] Configure one authoritative nginx FastDL vhost for the PUBLIC IP..."
NGPY="$(mktemp)"
echo 'CmZyb20gcGF0aGxpYiBpbXBvcnQgUGF0aAppbXBvcnQgcmUsIHN1YnByb2Nlc3MsIHN5cywgc2h1dGlsLCB0aW1lCgpQVUJMSUM9JzkwLjE4OS4yMDguMjUnCkJBQ0tVUD1QYXRoKHN5cy5hcmd2WzFdKQpCQUNLVVAubWtkaXIocGFyZW50cz1UcnVlLGV4aXN0X29rPVRydWUpCgpkZWYgcnVuKGNtZCk6CiAgICByZXR1cm4gc3VicHJvY2Vzcy5ydW4oY21kLHRleHQ9VHJ1ZSxzdGRvdXQ9c3VicHJvY2Vzcy5QSVBFLHN0ZGVycj1zdWJwcm9jZXNzLlNURE9VVCxjaGVjaz1GYWxzZSkKCmR1bXA9cnVuKFsnbmdpbngnLCctVCddKS5zdGRvdXQgb3IgJycKaWYgbm90IGR1bXA6CiAgICByYWlzZSBTeXN0ZW1FeGl0KCdbRVJST1JdIG5naW54IC1UIHJldHVybmVkIG5vIGNvbmZpZ3VyYXRpb24nKQoKaWYgcmUuc2VhcmNoKHInaW5jbHVkZVxzKy9ldGMvbmdpbngvY29uZlwuZC9cKlwuY29uZlxzKjsnLGR1bXApOgogICAgdGFyZ2V0PVBhdGgoJy9ldGMvbmdpbngvY29uZi5kLzAwLWh5cGVyLWNzMTYtZmFzdGRsLWlwLXY4LmNvbmYnKQplbGlmIHJlLnNlYXJjaChyJ2luY2x1ZGVccysvZXRjL25naW54L3NpdGVzLWVuYWJsZWQvXCpccyo7JyxkdW1wKToKICAgIHRhcmdldD1QYXRoKCcvZXRjL25naW54L3NpdGVzLWVuYWJsZWQvMDAtaHlwZXItY3MxNi1mYXN0ZGwtaXAtdjguY29uZicpCmVsaWYgcmUuc2VhcmNoKHInaW5jbHVkZVxzKy9ldGMvbmdpbngvaHlwZXItaG9zdC1tYW5hZ2VkL1wqXC5jb25mXHMqOycsZHVtcCk6CiAgICB0YXJnZXQ9UGF0aCgnL2V0Yy9uZ2lueC9oeXBlci1ob3N0LW1hbmFnZWQvMDAtaHlwZXItY3MxNi1mYXN0ZGwtaXAtdjguY29uZicpCmVsc2U6CiAgICByYWlzZSBTeXN0ZW1FeGl0KCdbRVJST1JdIENvdWxkIG5vdCBmaW5kIGFuIGFjdGl2ZSBuZ2lueCAqLmNvbmYgaW5jbHVkZSBkaXJlY3RvcnknKQoKYWN0aXZlPVtdCmZvciBtIGluIHJlLmZpbmRpdGVyKHInXiMgY29uZmlndXJhdGlvbiBmaWxlIChbXjpdKyk6JCcsZHVtcCxyZS5NKToKICAgIHA9UGF0aChtLmdyb3VwKDEpKQogICAgaWYgcC5pc19maWxlKCk6CiAgICAgICAgYWN0aXZlLmFwcGVuZChwKQoKZm9yIHAgaW4gYWN0aXZlOgogICAgaWYgcD09dGFyZ2V0IG9yICdmYXN0ZGwnIG5vdCBpbiBwLm5hbWUubG93ZXIoKToKICAgICAgICBjb250aW51ZQogICAgdHJ5OgogICAgICAgIHR4dD1wLnJlYWRfdGV4dChlbmNvZGluZz0ndXRmLTgnLGVycm9ycz0naWdub3JlJykKICAgIGV4Y2VwdCBFeGNlcHRpb246CiAgICAgICAgY29udGludWUKICAgIGlmIHJlLnNlYXJjaChyJyg/bSleXHMqbGlzdGVuXHMrKD86W147XSo6KT84MDgwXGInLHR4dCk6CiAgICAgICAgc2h1dGlsLmNvcHkyKHAsQkFDS1VQLyhwLm5hbWUrJy5wcmUtdjgnKSkKICAgICAgICBkaXNhYmxlZD1wLndpdGhfbmFtZShwLm5hbWUrJy5kaXNhYmxlZC12OCcpCiAgICAgICAgdHJ5OgogICAgICAgICAgICBwLnJlbmFtZShkaXNhYmxlZCkKICAgICAgICAgICAgcHJpbnQoJ2Rpc2FibGVkIG9sZCA4MDgwIEZhc3RETCBjb25maWc6JyxwKQogICAgICAgIGV4Y2VwdCBFeGNlcHRpb24gYXMgZXhjOgogICAgICAgICAgICBwcmludCgnd2FybmluZzogY2Fubm90IGRpc2FibGUnLHAsZXhjKQoKdGVzdD1ydW4oWyduZ2lueCcsJy10J10pCmlmIHRlc3QucmV0dXJuY29kZSE9MDoKICAgIHByaW50KHRlc3Quc3Rkb3V0KQogICAgcmFpc2UgU3lzdGVtRXhpdCgnW0VSUk9SXSBuZ2lueCBpbnZhbGlkIGFmdGVyIGRpc2FibGluZyBvbGQgODA4MCBjb25maWdzJykKCmR1bXA9cnVuKFsnbmdpbngnLCctVCddKS5zdGRvdXQgb3IgJycKYWN0aXZlPVtdCmZvciBtIGluIHJlLmZpbmRpdGVyKHInXiMgY29uZmlndXJhdGlvbiBmaWxlIChbXjpdKyk6JCcsZHVtcCxyZS5NKToKICAgIHA9UGF0aChtLmdyb3VwKDEpKQogICAgaWYgcC5pc19maWxlKCk6CiAgICAgICAgYWN0aXZlLmFwcGVuZChwKQoKIyBEaXJlY3QgSVAgbXVzdCBiZWxvbmcgdG8gb25lIGF1dGhvcml0YXRpdmUgdmhvc3QuCmZvciBwIGluIGFjdGl2ZToKICAgIGlmIHA9PXRhcmdldDoKICAgICAgICBjb250aW51ZQogICAgdHJ5OgogICAgICAgIHR4dD1wLnJlYWRfdGV4dChlbmNvZGluZz0ndXRmLTgnLGVycm9ycz0naWdub3JlJykKICAgIGV4Y2VwdCBFeGNlcHRpb246CiAgICAgICAgY29udGludWUKCiAgICBkZWYgcmV3cml0ZV9zZXJ2ZXJfbmFtZShtKToKICAgICAgICBwcmVmaXg9bS5ncm91cCgxKQogICAgICAgIGJvZHk9bS5ncm91cCgyKQogICAgICAgIHRva2Vucz1ib2R5LnNwbGl0KCkKICAgICAgICBpZiBQVUJMSUMgbm90IGluIHRva2VuczoKICAgICAgICAgICAgcmV0dXJuIG0uZ3JvdXAoMCkKICAgICAgICBrZXB0PVt4IGZvciB4IGluIHRva2VucyBpZiB4IT1QVUJMSUNdCiAgICAgICAgaWYgbm90IGtlcHQ6CiAgICAgICAgICAgIGtlcHQ9WydsZWdhY3ktZGlyZWN0LWlwLWRpc2FibGVkLmludmFsaWQnXQogICAgICAgIHJldHVybiBwcmVmaXgrJyAnLmpvaW4oa2VwdCkrJzsnCgogICAgbmV3PXJlLnN1YihyJyg/bSleKFxzKnNlcnZlcl9uYW1lXHMrKShbXjtdKyk7JyxyZXdyaXRlX3NlcnZlcl9uYW1lLHR4dCkKICAgIGlmIG5ldyE9dHh0OgogICAgICAgIHNodXRpbC5jb3B5MihwLEJBQ0tVUC8ocC5uYW1lKycuaXAtY29uZmxpY3QucHJlLXY4JykpCiAgICAgICAgcC53cml0ZV90ZXh0KG5ldyxlbmNvZGluZz0ndXRmLTgnKQogICAgICAgIHByaW50KCdyZW1vdmVkIGNvbmZsaWN0aW5nIGRpcmVjdC1JUCBzZXJ2ZXJfbmFtZSBmcm9tOicscCkKCnRhcmdldC5wYXJlbnQubWtkaXIocGFyZW50cz1UcnVlLGV4aXN0X29rPVRydWUpCmlmIHRhcmdldC5leGlzdHMoKToKICAgIHNodXRpbC5jb3B5Mih0YXJnZXQsQkFDS1VQLyh0YXJnZXQubmFtZSsnLnByZS12OCcpKQoKY2ZnID0gJycnIyBIWVBFUi1IT1NUIEZBU1RETCBWOCDigJQgYXV0aG9yaXRhdGl2ZSBkaXJlY3QtSVAgZW5kcG9pbnQKc2VydmVyIHsKICAgIGxpc3RlbiA4MDsKICAgIGxpc3RlbiBbOjpdOjgwOwogICAgc2VydmVyX25hbWUgOTAuMTg5LjIwOC4yNTsKCiAgICByb290IC9zcnYvaHlwZXItY3MxNjsKICAgIHNlcnZlcl90b2tlbnMgb2ZmOwogICAgc2VuZGZpbGUgb247CiAgICB0Y3Bfbm9wdXNoIG9uOwoKICAgIGFjY2Vzc19sb2cgL3Zhci9sb2cvbmdpbngvaHlwZXItY3MxNi1mYXN0ZGwtYWNjZXNzLmxvZzsKICAgIGVycm9yX2xvZyAgL3Zhci9sb2cvbmdpbngvaHlwZXItY3MxNi1mYXN0ZGwtZXJyb3IubG9nIHdhcm47CgogICAgbG9jYXRpb24gXn4gL2Zhc3RkbC8gewogICAgICAgIHRyeV9maWxlcyAkdXJpID00MDQ7CiAgICAgICAgdHlwZXMgeyB9CiAgICAgICAgZGVmYXVsdF90eXBlIGFwcGxpY2F0aW9uL29jdGV0LXN0cmVhbTsKICAgICAgICBhZGRfaGVhZGVyIFgtSHlwZXItRmFzdERMICJyYXciIGFsd2F5czsKICAgICAgICBhZGRfaGVhZGVyIFgtQ29udGVudC1UeXBlLU9wdGlvbnMgIm5vc25pZmYiIGFsd2F5czsKICAgICAgICBhZGRfaGVhZGVyIENhY2hlLUNvbnRyb2wgInB1YmxpYywgbWF4LWFnZT04NjQwMCIgYWx3YXlzOwogICAgfQoKICAgIGxvY2F0aW9uIC8gewogICAgICAgIHJldHVybiA0MDQ7CiAgICB9Cn0KJycnCnRhcmdldC53cml0ZV90ZXh0KGNmZyxlbmNvZGluZz0ndXRmLTgnKQpwcmludCgnaW5zdGFsbGVkIGF1dGhvcml0YXRpdmUgRmFzdERMIHZob3N0OicsdGFyZ2V0KQoKdGVzdD1ydW4oWyduZ2lueCcsJy10J10pCnByaW50KHRlc3Quc3Rkb3V0LGVuZD0nJykKaWYgdGVzdC5yZXR1cm5jb2RlIT0wOgogICAgcmFpc2UgU3lzdGVtRXhpdCgnW0VSUk9SXSBuZ2lueCAtdCBmYWlsZWQnKQoKcmVsb2FkPXJ1bihbJ3N5c3RlbWN0bCcsJ3JlbG9hZCcsJ25naW54J10pCmlmIHJlbG9hZC5yZXR1cm5jb2RlIT0wOgogICAgcHJpbnQocmVsb2FkLnN0ZG91dCkKICAgIHJhaXNlIFN5c3RlbUV4aXQoJ1tFUlJPUl0gbmdpbnggcmVsb2FkIGZhaWxlZCcpCgp0aW1lLnNsZWVwKDAuNCkKcHJpbnQoJ25naW54IEZhc3RETCB2OCByZWFkeScpCg==' | base64 -d > "$NGPY"
python3 "$NGPY" "$BACKUP"
rm -f "$NGPY"

echo "[3/10] Patch panel with a final FastDL override..."
PATCHER="$(mktemp)"
echo 'CmZyb20gcGF0aGxpYiBpbXBvcnQgUGF0aAppbXBvcnQgcmUsIHN5cwoKY3RsID0gUGF0aChzeXMuYXJndlsxXSkKcyA9IGN0bC5yZWFkX3RleHQoZW5jb2Rpbmc9J3V0Zi04JykKCkJFR0lOID0gIiMgSFlQRVItSE9TVCBGQVNUREwgRklOQUwgT1ZFUlJJREUgVjggQkVHSU4iCkVORCAgID0gIiMgSFlQRVItSE9TVCBGQVNUREwgRklOQUwgT1ZFUlJJREUgVjggRU5EIgoKb3ZlcnJpZGUgPSByJycnCiMgSFlQRVItSE9TVCBGQVNUREwgRklOQUwgT1ZFUlJJREUgVjggQkVHSU4KZGVmIF9oaF9mYXN0ZGxfdjhfdXJsKGM6ZGljdCktPnN0cjoKICAgIHNpZD1pbnQoYy5nZXQoJ2lkJykgb3IgMCkKICAgIHJldHVybiBmJ2h0dHA6Ly85MC4xODkuMjA4LjI1L2Zhc3RkbC97c2lkfScKCgpkZWYgX2hoX2Zhc3RkbF92OF9maXhfY2ZnKGM6ZGljdCwgcm9vdDpQYXRoKS0+ZGljdDoKICAgIGNmZz1yb290Lydjc3RyaWtlL3NlcnZlci5jZmcnCiAgICBjZmcucGFyZW50Lm1rZGlyKHBhcmVudHM9VHJ1ZSxleGlzdF9vaz1UcnVlKQogICAgcmF3PWNmZy5yZWFkX3RleHQoZW5jb2Rpbmc9J3V0Zi04JyxlcnJvcnM9J2lnbm9yZScpIGlmIGNmZy5leGlzdHMoKSBlbHNlICcnCgogICAgZXNjYXBlZD1GYWxzZQogICAgaWYgcmF3LmNvdW50KCdcXG4nKT49NSBhbmQgcmF3LmNvdW50KCdcbicpPD0yOgogICAgICAgIHJhdz1yYXcucmVwbGFjZSgnXFxyXFxuJywnXG4nKS5yZXBsYWNlKCdcXG4nLCdcbicpLnJlcGxhY2UoJ1xccicsJ1xuJykKICAgICAgICBlc2NhcGVkPVRydWUKCiAgICB0ZXh0PXJhdy5yZXBsYWNlKCdcclxuJywnXG4nKS5yZXBsYWNlKCdccicsJ1xuJykKICAgIGJlZ2luPScvLyBIWVBFUi1IT1NUIEZBU1RETCBCRUdJTicKICAgIGVuZD0nLy8gSFlQRVItSE9TVCBGQVNUREwgRU5EJwoKICAgIHRleHQ9cmUuc3ViKAogICAgICAgIHInKD9pbXMpXlxzKi8vIEhZUEVSLUhPU1QgRkFTVERMIEJFR0lOXHMqJC4qP15ccyovLyBIWVBFUi1IT1NUIEZBU1RETCBFTkRccyokXG4/JywKICAgICAgICAnJywKICAgICAgICB0ZXh0CiAgICApCgogICAgbWFuYWdlZD17J3N2X2Rvd25sb2FkdXJsJywnc3ZfYWxsb3dkb3dubG9hZCcsJ3N2X2FsbG93dXBsb2FkJywnc3Zfc2VuZF9yZXNvdXJjZXMnLCdzdl9hbGxvd19kbGZpbGUnfQogICAga2VwdD1bXQogICAgcmVtb3ZlZD1bXQogICAgZm9yIGxpbmUgaW4gdGV4dC5zcGxpdGxpbmVzKCk6CiAgICAgICAgbT1yZS5tYXRjaChyJ15ccyooW0EtWmEtel9dW0EtWmEtejAtOV9dKilcYicsbGluZSkKICAgICAgICBpZiBtIGFuZCBtLmdyb3VwKDEpLmxvd2VyKCkgaW4gbWFuYWdlZDoKICAgICAgICAgICAgcmVtb3ZlZC5hcHBlbmQobGluZS5zdHJpcCgpKQogICAgICAgICAgICBjb250aW51ZQogICAgICAgIGtlcHQuYXBwZW5kKGxpbmUpCgogICAgdXJsPV9oaF9mYXN0ZGxfdjhfdXJsKGMpCiAgICBibG9jaz1bCiAgICAgICAgYmVnaW4sCiAgICAgICAgJy8vIE1hbmFnZWQgYnkgSFlQRVItSE9TVCBGYXN0REwgdjguIEtlZXAgdGhpcyBibG9jayBvbmNlLicsCiAgICAgICAgJ3N2X2FsbG93ZG93bmxvYWQgMScsCiAgICAgICAgJ3N2X2FsbG93dXBsb2FkIDAnLAogICAgICAgICdzdl9zZW5kX3Jlc291cmNlcyAxJywKICAgICAgICAnc3ZfYWxsb3dfZGxmaWxlIDEnLAogICAgICAgIGYnc3ZfZG93bmxvYWR1cmwgInt1cmx9LyInLAogICAgICAgIGVuZCwKICAgIF0KICAgIGNvbnRlbnQ9J1xuJy5qb2luKGtlcHQpLnJzdHJpcCgpKydcblxuJysnXG4nLmpvaW4oYmxvY2spKydcbicKICAgIGNmZy53cml0ZV90ZXh0KGNvbnRlbnQsZW5jb2Rpbmc9J3V0Zi04JykKCiAgICBoZWxwZXI9Jy8vIE1hbmFnZWQgYnkgSFlQRVItSE9TVCBGYXN0REwgdjhcbicrJ1xuJy5qb2luKGJsb2NrWzI6LTFdKSsnXG4nCiAgICBmb3IgbmFtZSBpbiAoJ2Zhc3RkbC5jZmcnLCdzZXJ2ZXJfZG93bmxvYWRfZml4LmNmZycsJ1NBRkVfRE9XTkxPQURfTU9ERS5jZmcnLCdFTkFCTEVfRkFTVERMX0FGVEVSX1ZFUklGWS5jZmcnKToKICAgICAgICB0cnk6CiAgICAgICAgICAgIChyb290Lydjc3RyaWtlJy9uYW1lKS53cml0ZV90ZXh0KGhlbHBlcixlbmNvZGluZz0ndXRmLTgnKQogICAgICAgIGV4Y2VwdCBFeGNlcHRpb246CiAgICAgICAgICAgIHBhc3MKCiAgICByZXR1cm4gewogICAgICAgICd1cmwnOnVybCwKICAgICAgICAnY29uZmlnJzpzdHIoY2ZnKSwKICAgICAgICAnZXNjYXBlZF9uZXdsaW5lc19yZXBhaXJlZCc6ZXNjYXBlZCwKICAgICAgICAncmVtb3ZlZF9vbGRfbGluZXMnOnJlbW92ZWRbOjEwMF0sCiAgICAgICAgJ2xpbmVfY291bnQnOmxlbihjb250ZW50LnNwbGl0bGluZXMoKSkKICAgIH0KCgpkZWYgX2hoX2Zhc3RkbF92OF92YWxpZGF0ZV9ic3BfZGlyKG1hcHM6UGF0aCktPmRpY3Q6CiAgICBnb29kPVtdCiAgICBiYWQ9W10KICAgIGlmIG5vdCBtYXBzLmlzX2RpcigpOgogICAgICAgIHJldHVybiB7J2dvb2QnOmdvb2QsJ2JhZCc6YmFkfQogICAgZm9yIGZwIGluIHNvcnRlZChtYXBzLmdsb2IoJyouYnNwJykpOgogICAgICAgIHRyeToKICAgICAgICAgICAgc2l6ZT1mcC5zdGF0KCkuc3Rfc2l6ZQogICAgICAgICAgICB3aXRoIGZwLm9wZW4oJ3JiJykgYXMgZmg6CiAgICAgICAgICAgICAgICBoZWFkPWZoLnJlYWQoNCkKICAgICAgICAgICAgdmVyPWludC5mcm9tX2J5dGVzKGhlYWQsJ2xpdHRsZScpIGlmIGxlbihoZWFkKT09NCBlbHNlIE5vbmUKICAgICAgICAgICAgaWYgc2l6ZT49NCBhbmQgdmVyPT0zMDoKICAgICAgICAgICAgICAgIGdvb2QuYXBwZW5kKHsnbmFtZSc6ZnAubmFtZSwnYnl0ZXMnOnNpemV9KQogICAgICAgICAgICBlbHNlOgogICAgICAgICAgICAgICAgYmFkLmFwcGVuZCh7J25hbWUnOmZwLm5hbWUsJ2J5dGVzJzpzaXplLCd2ZXJzaW9uJzp2ZXIsJ2hlYWQnOmhlYWQuaGV4KCl9KQogICAgICAgIGV4Y2VwdCBFeGNlcHRpb24gYXMgZXhjOgogICAgICAgICAgICBiYWQuYXBwZW5kKHsnbmFtZSc6ZnAubmFtZSwnZXJyb3InOnN0cihleGMpfSkKICAgIHJldHVybiB7J2dvb2QnOmdvb2QsJ2JhZCc6YmFkfQoKCmRlZiBfaGhfZmFzdGRsX3Y4X3JlcGFpcl9jYXNlX29ubHkoY3N0cmlrZTpQYXRoKS0+ZGljdDoKICAgIGluZGV4PXt9CiAgICBmb3IgdG9wIGluICgnbWFwcycsJ21vZGVscycsJ3NvdW5kJywnc3ByaXRlcycsJ2dmeCcsJ3Jlc291cmNlJywnb3ZlcnZpZXdzJywnZXZlbnRzJywnbWVkaWEnKToKICAgICAgICBiYXNlPWNzdHJpa2UvdG9wCiAgICAgICAgaWYgbm90IGJhc2UuaXNfZGlyKCk6CiAgICAgICAgICAgIGNvbnRpbnVlCiAgICAgICAgZm9yIGZwIGluIGJhc2Uucmdsb2IoJyonKToKICAgICAgICAgICAgdHJ5OgogICAgICAgICAgICAgICAgaWYgZnAuaXNfZmlsZSgpIGFuZCBub3QgZnAuaXNfc3ltbGluaygpOgogICAgICAgICAgICAgICAgICAgIHJlbD1mcC5yZWxhdGl2ZV90byhjc3RyaWtlKS5hc19wb3NpeCgpCiAgICAgICAgICAgICAgICAgICAgaW5kZXguc2V0ZGVmYXVsdChyZWwubG93ZXIoKSxbXSkuYXBwZW5kKGZwKQogICAgICAgICAgICBleGNlcHQgT1NFcnJvcjoKICAgICAgICAgICAgICAgIHBhc3MKICAgIGZvciBmcCBpbiBjc3RyaWtlLmdsb2IoJyoud2FkJyk6CiAgICAgICAgaWYgZnAuaXNfZmlsZSgpOgogICAgICAgICAgICBpbmRleC5zZXRkZWZhdWx0KGZwLm5hbWUubG93ZXIoKSxbXSkuYXBwZW5kKGZwKQoKICAgIHdhbnRlZD1bXQogICAgbWFwcz1jc3RyaWtlLydtYXBzJwogICAgaWYgbWFwcy5pc19kaXIoKToKICAgICAgICBmb3IgcmYgaW4gbWFwcy5nbG9iKCcqLnJlcycpOgogICAgICAgICAgICB0cnk6CiAgICAgICAgICAgICAgICBsaW5lcz1yZi5yZWFkX3RleHQoZW5jb2Rpbmc9J2xhdGluMScsZXJyb3JzPSdpZ25vcmUnKS5zcGxpdGxpbmVzKCkKICAgICAgICAgICAgZXhjZXB0IEV4Y2VwdGlvbjoKICAgICAgICAgICAgICAgIGNvbnRpbnVlCiAgICAgICAgICAgIGZvciByYXcgaW4gbGluZXM6CiAgICAgICAgICAgICAgICBzdD1yYXcuc3BsaXQoJy8vJywxKVswXS5zcGxpdCgnOycsMSlbMF0uc3RyaXAoKS5zdHJpcCgnIicpLnJlcGxhY2UoJ1xcJywnLycpCiAgICAgICAgICAgICAgICBpZiBub3Qgc3Qgb3IgJy4uJyBpbiBQYXRoKHN0KS5wYXJ0czoKICAgICAgICAgICAgICAgICAgICBjb250aW51ZQogICAgICAgICAgICAgICAgaWYgcmUubWF0Y2gocideKD86bWFwc3xtb2RlbHN8c291bmR8c3ByaXRlc3xnZnh8cmVzb3VyY2V8b3ZlcnZpZXdzfGV2ZW50c3xtZWRpYSkvJyxzdCxyZS5JKSBvciByZS5tYXRjaChyJ15bXi9dK1wud2FkJCcsc3QscmUuSSk6CiAgICAgICAgICAgICAgICAgICAgd2FudGVkLmFwcGVuZCgocmYubmFtZSxzdCkpCgogICAgcmVwYWlyZWQ9W10KICAgIG1pc3Npbmc9W10KICAgIGNyb290PWNzdHJpa2UucmVzb2x2ZSgpCiAgICBzZWVuPXNldCgpCiAgICBmb3Igc3JjbmFtZSxyZWwgaW4gd2FudGVkOgogICAgICAgIGlmIChzcmNuYW1lLHJlbCkgaW4gc2VlbjoKICAgICAgICAgICAgY29udGludWUKICAgICAgICBzZWVuLmFkZCgoc3JjbmFtZSxyZWwpKQogICAgICAgIHRhcmdldD0oY3N0cmlrZS9yZWwpLnJlc29sdmUoKQogICAgICAgIHRyeToKICAgICAgICAgICAgdGFyZ2V0LnJlbGF0aXZlX3RvKGNyb290KQogICAgICAgIGV4Y2VwdCBWYWx1ZUVycm9yOgogICAgICAgICAgICBjb250aW51ZQogICAgICAgIGlmIHRhcmdldC5pc19maWxlKCk6CiAgICAgICAgICAgIGNvbnRpbnVlCiAgICAgICAgbWF0Y2hlcz1pbmRleC5nZXQocmVsLmxvd2VyKCksW10pCiAgICAgICAgaWYgbGVuKG1hdGNoZXMpPT0xOgogICAgICAgICAgICBzcmM9bWF0Y2hlc1swXQogICAgICAgICAgICB0YXJnZXQucGFyZW50Lm1rZGlyKHBhcmVudHM9VHJ1ZSxleGlzdF9vaz1UcnVlKQogICAgICAgICAgICBzaHV0aWwuY29weTIoc3JjLHRhcmdldCkKICAgICAgICAgICAgcmVwYWlyZWQuYXBwZW5kKHsncmVxdWVzdGVkJzpyZWwsJ2Zyb20nOnNyYy5yZWxhdGl2ZV90byhjc3RyaWtlKS5hc19wb3NpeCgpLCdyZXMnOnNyY25hbWV9KQogICAgICAgICAgICBpbmRleC5zZXRkZWZhdWx0KHJlbC5sb3dlcigpLFtdKS5hcHBlbmQodGFyZ2V0KQogICAgICAgIGVsaWYgbGVuKG1hdGNoZXMpPT0wOgogICAgICAgICAgICBtaXNzaW5nLmFwcGVuZCh7J3JlcXVlc3RlZCc6cmVsLCdyZXMnOnNyY25hbWV9KQoKICAgIHJldHVybiB7CiAgICAgICAgJ3JlcGFpcmVkX2NvdW50JzpsZW4ocmVwYWlyZWQpLAogICAgICAgICdyZXBhaXJlZCc6cmVwYWlyZWRbOjEwMF0sCiAgICAgICAgJ21pc3NpbmdfY291bnQnOmxlbihtaXNzaW5nKSwKICAgICAgICAnbWlzc2luZyc6bWlzc2luZ1s6MTAwXQogICAgfQoKCmRlZiBfaGhfZmFzdGRsX3Y4X2h0dHBfY2hlY2soc2lkOmludCwgZGVzdDpQYXRoKS0+ZGljdDoKICAgIGltcG9ydCB1cmxsaWIucmVxdWVzdCBhcyBfdQogICAgaW1wb3J0IHVybGxpYi5lcnJvciBhcyBfdWUKCiAgICBtYXBzPWRlc3QvJ21hcHMnCiAgICBjaGVja2VkPVtdCiAgICBiYWQ9W10KCiAgICBpZiBub3QgbWFwcy5pc19kaXIoKToKICAgICAgICByZXR1cm4geydvayc6RmFsc2UsJ2NoZWNrZWQnOjAsJ2JhZCc6W3snZXJyb3InOidGYXN0REwgbWFwcyBkaXJlY3RvcnkgbWlzc2luZyd9XX0KCiAgICBmb3IgZnAgaW4gc29ydGVkKG1hcHMuZ2xvYignKi5ic3AnKSk6CiAgICAgICAgcmVsPWZwLnJlbGF0aXZlX3RvKGRlc3QpLmFzX3Bvc2l4KCkKICAgICAgICB1cmw9ZidodHRwOi8vMTI3LjAuMC4xL2Zhc3RkbC97c2lkfS8nK3VybGxpYi5wYXJzZS5xdW90ZShyZWwsc2FmZT0nLy5fLSsoKVtdJykKICAgICAgICByZXE9X3UuUmVxdWVzdCgKICAgICAgICAgICAgdXJsLAogICAgICAgICAgICBoZWFkZXJzPXsKICAgICAgICAgICAgICAgICdIb3N0JzonOTAuMTg5LjIwOC4yNScsCiAgICAgICAgICAgICAgICAnUmFuZ2UnOidieXRlcz0wLTMnLAogICAgICAgICAgICAgICAgJ1VzZXItQWdlbnQnOidIWVBFUi1IT1NULUZhc3RETC12OCcKICAgICAgICAgICAgfQogICAgICAgICkKICAgICAgICBjb2RlPTAKICAgICAgICBoZWFkPWInJwogICAgICAgIGNvbnRlbnRfdHlwZT0nJwogICAgICAgIG1hcmtlcj0nJwogICAgICAgIHRyeToKICAgICAgICAgICAgd2l0aCBfdS51cmxvcGVuKHJlcSx0aW1lb3V0PTUpIGFzIHI6CiAgICAgICAgICAgICAgICBjb2RlPWludChnZXRhdHRyKHIsJ3N0YXR1cycsMjAwKSBvciAyMDApCiAgICAgICAgICAgICAgICBoZWFkPXIucmVhZCg0KQogICAgICAgICAgICAgICAgY29udGVudF90eXBlPXN0cihyLmhlYWRlcnMuZ2V0KCdDb250ZW50LVR5cGUnKSBvciAnJykKICAgICAgICAgICAgICAgIG1hcmtlcj1zdHIoci5oZWFkZXJzLmdldCgnWC1IeXBlci1GYXN0REwnKSBvciAnJykKICAgICAgICBleGNlcHQgX3VlLkhUVFBFcnJvciBhcyBleGM6CiAgICAgICAgICAgIGNvZGU9aW50KGV4Yy5jb2RlIG9yIDApCiAgICAgICAgICAgIHRyeTogaGVhZD1leGMucmVhZCg0KQogICAgICAgICAgICBleGNlcHQgRXhjZXB0aW9uOiBoZWFkPWInJwogICAgICAgIGV4Y2VwdCBFeGNlcHRpb24gYXMgZXhjOgogICAgICAgICAgICBiYWQuYXBwZW5kKHsnbWFwJzpmcC5uYW1lLCdodHRwJzowLCdlcnJvcic6c3RyKGV4Yyl9KQogICAgICAgICAgICBjb250aW51ZQoKICAgICAgICB2ZXI9aW50LmZyb21fYnl0ZXMoaGVhZCwnbGl0dGxlJykgaWYgbGVuKGhlYWQpPT00IGVsc2UgTm9uZQogICAgICAgIHJvdz17J21hcCc6ZnAubmFtZSwnaHR0cCc6Y29kZSwndmVyc2lvbic6dmVyLCdoZWFkJzpoZWFkLmhleCgpLCdjb250ZW50X3R5cGUnOmNvbnRlbnRfdHlwZSwnbWFya2VyJzptYXJrZXJ9CiAgICAgICAgY2hlY2tlZC5hcHBlbmQocm93KQogICAgICAgIGlmIGNvZGUgbm90IGluICgyMDAsMjA2KSBvciB2ZXIhPTMwIG9yIG1hcmtlciE9J3Jhdyc6CiAgICAgICAgICAgIGJhZC5hcHBlbmQocm93KQoKICAgIHJldHVybiB7J29rJzpub3QgYmFkIGFuZCBib29sKGNoZWNrZWQpLCdjaGVja2VkJzpsZW4oY2hlY2tlZCksJ2JhZCc6YmFkWzoxMDBdfQoKCmRlZiBfZmFzdGRsX3VybChjOmRpY3QpLT5zdHI6CiAgICByZXR1cm4gX2hoX2Zhc3RkbF92OF91cmwoYykKCgpkZWYgX2Zhc3RkbF9hcHBseV9jZmcoYzpkaWN0LCByb290OlBhdGh8Tm9uZT1Ob25lKS0+ZGljdDoKICAgIHJldHVybiBfaGhfZmFzdGRsX3Y4X2ZpeF9jZmcoYyxQYXRoKHJvb3Qgb3IgY1sncGF0aCddKSkKCgpkZWYgZmFzdGRsX3N5bmMoc2lkOmludCwgY29uZmlndXJlOmJvb2w9VHJ1ZSk6CiAgICByZXF1aXJlX3Jvb3QoKQogICAgYz1sb2FkX3NlcnZlcihzaWQpCiAgICByb290PVBhdGgoY1sncGF0aCddKQogICAgY3N0cmlrZT1yb290Lydjc3RyaWtlJwogICAgaWYgbm90IGNzdHJpa2UuaXNfZGlyKCk6CiAgICAgICAgcmFpc2UgUnVudGltZUVycm9yKGYnY3N0cmlrZSBkaXJlY3RvcnkgaXMgbWlzc2luZzoge2NzdHJpa2V9JykKCiAgICBzb3VyY2VfYnNwPV9oaF9mYXN0ZGxfdjhfdmFsaWRhdGVfYnNwX2Rpcihjc3RyaWtlLydtYXBzJykKICAgIGlmIHNvdXJjZV9ic3BbJ2JhZCddOgogICAgICAgIHJhaXNlIFJ1bnRpbWVFcnJvcignU09VUkNFIEJTUCB2YWxpZGF0aW9uIGZhaWxlZDogJytqc29uLmR1bXBzKHNvdXJjZV9ic3BbJ2JhZCddWzozMF0sZW5zdXJlX2FzY2lpPUZhbHNlKSkKCiAgICBjYXNlZml4PV9oaF9mYXN0ZGxfdjhfcmVwYWlyX2Nhc2Vfb25seShjc3RyaWtlKQoKICAgIGRlc3Q9UGF0aCgnL3Nydi9oeXBlci1jczE2L2Zhc3RkbCcpL3N0cihpbnQoc2lkKSkKICAgIGRlc3QubWtkaXIocGFyZW50cz1UcnVlLGV4aXN0X29rPVRydWUpCgogICAgZGlycz0oJ21hcHMnLCdtb2RlbHMnLCdzb3VuZCcsJ3Nwcml0ZXMnLCdnZngnLCdyZXNvdXJjZScsJ292ZXJ2aWV3cycsJ2V2ZW50cycsJ21lZGlhJykKICAgIGNvcGllZD1bXQogICAgZm9yIG5hbWUgaW4gZGlyczoKICAgICAgICBzcmM9Y3N0cmlrZS9uYW1lCiAgICAgICAgZHN0PWRlc3QvbmFtZQogICAgICAgIGlmIHNyYy5pc19kaXIoKToKICAgICAgICAgICAgZHN0Lm1rZGlyKHBhcmVudHM9VHJ1ZSxleGlzdF9vaz1UcnVlKQogICAgICAgICAgICBjcD1ydW4oWydyc3luYycsJy1hJywnLS1kZWxldGUnLCctLXNhZmUtbGlua3MnLHN0cihzcmMpKycvJyxzdHIoZHN0KSsnLyddLGNoZWNrPUZhbHNlLHRpbWVvdXQ9MTIwMCkKICAgICAgICAgICAgaWYgY3AucmV0dXJuY29kZSE9MDoKICAgICAgICAgICAgICAgIHJhaXNlIFJ1bnRpbWVFcnJvcignRmFzdERMIHJzeW5jIGZhaWxlZCBmb3IgJytuYW1lKyc6ICcrKGNwLnN0ZG91dCBvciAnJylbLTI1MDA6XSkKICAgICAgICAgICAgY29waWVkLmFwcGVuZChuYW1lKQogICAgICAgIGVsaWYgZHN0LmV4aXN0cygpOgogICAgICAgICAgICBzaHV0aWwucm10cmVlKGRzdCxpZ25vcmVfZXJyb3JzPVRydWUpCgogICAgc3JjX3dhZHM9e3gubmFtZTp4IGZvciB4IGluIGNzdHJpa2UuaXRlcmRpcigpIGlmIHguaXNfZmlsZSgpIGFuZCB4LnN1ZmZpeC5sb3dlcigpPT0nLndhZCd9CiAgICBmb3Igb2xkIGluIGRlc3QuZ2xvYignKi53YWQnKToKICAgICAgICBpZiBvbGQubmFtZSBub3QgaW4gc3JjX3dhZHM6CiAgICAgICAgICAgIHRyeTogb2xkLnVubGluaygpCiAgICAgICAgICAgIGV4Y2VwdCBPU0Vycm9yOiBwYXNzCiAgICBmb3IgbmFtZSxzcmMgaW4gc3JjX3dhZHMuaXRlbXMoKToKICAgICAgICBzaHV0aWwuY29weTIoc3JjLGRlc3QvbmFtZSkKCiAgICByZW1vdmVkX3p0bXA9MAogICAgZm9yIGZwIGluIGxpc3QoZGVzdC5yZ2xvYignKi56dG1wJykpOgogICAgICAgIHRyeToKICAgICAgICAgICAgZnAudW5saW5rKCkKICAgICAgICAgICAgcmVtb3ZlZF96dG1wKz0xCiAgICAgICAgZXhjZXB0IE9TRXJyb3I6CiAgICAgICAgICAgIHBhc3MKCiAgICBtaXJyb3JfYnNwPV9oaF9mYXN0ZGxfdjhfdmFsaWRhdGVfYnNwX2RpcihkZXN0LydtYXBzJykKICAgIGlmIG1pcnJvcl9ic3BbJ2JhZCddOgogICAgICAgIHJhaXNlIFJ1bnRpbWVFcnJvcignRkFTVERMIG1pcnJvciBCU1AgdmFsaWRhdGlvbiBmYWlsZWQ6ICcranNvbi5kdW1wcyhtaXJyb3JfYnNwWydiYWQnXVs6MzBdLGVuc3VyZV9hc2NpaT1GYWxzZSkpCgogICAgaW1wb3J0IGhhc2hsaWIgYXMgX2hoX2hhc2hsaWIKICAgIGRlZiBfc2hhKGZwKToKICAgICAgICBoPV9oaF9oYXNobGliLnNoYTI1NigpCiAgICAgICAgd2l0aCBmcC5vcGVuKCdyYicpIGFzIGZoOgogICAgICAgICAgICBmb3IgY2h1bmsgaW4gaXRlcihsYW1iZGE6ZmgucmVhZCgxMDI0KjEwMjQpLGInJyk6CiAgICAgICAgICAgICAgICBoLnVwZGF0ZShjaHVuaykKICAgICAgICByZXR1cm4gaC5oZXhkaWdlc3QoKQoKICAgIHNyY19zaGE9e2ZwLm5hbWU6X3NoYShmcCkgZm9yIGZwIGluIHNvcnRlZCgoY3N0cmlrZS8nbWFwcycpLmdsb2IoJyouYnNwJykpfQogICAgbWlycm9yX3NoYT17ZnAubmFtZTpfc2hhKGZwKSBmb3IgZnAgaW4gc29ydGVkKChkZXN0LydtYXBzJykuZ2xvYignKi5ic3AnKSl9CiAgICBtaXNtYXRjaGVkPVtuYW1lIGZvciBuYW1lLHZhbCBpbiBzcmNfc2hhLml0ZW1zKCkgaWYgbWlycm9yX3NoYS5nZXQobmFtZSkhPXZhbF0KICAgIGV4dHJhPXNvcnRlZChzZXQobWlycm9yX3NoYSktc2V0KHNyY19zaGEpKQogICAgaWYgbWlzbWF0Y2hlZCBvciBleHRyYToKICAgICAgICByYWlzZSBSdW50aW1lRXJyb3IoCiAgICAgICAgICAgICdGYXN0REwgQlNQIG1pcnJvciBkaWZmZXJzIGZyb20gc291cmNlOiBtaXNtYXRjaGVkPScKICAgICAgICAgICAgK2pzb24uZHVtcHMobWlzbWF0Y2hlZCxlbnN1cmVfYXNjaWk9RmFsc2UpCiAgICAgICAgICAgICsnIGV4dHJhPScranNvbi5kdW1wcyhleHRyYSxlbnN1cmVfYXNjaWk9RmFsc2UpCiAgICAgICAgKQoKICAgIGNmZ19yZXN1bHQ9X2hoX2Zhc3RkbF92OF9maXhfY2ZnKGMscm9vdCkgaWYgY29uZmlndXJlIGVsc2Ugeyd1cmwnOl9oaF9mYXN0ZGxfdjhfdXJsKGMpfQoKICAgIHJ1bihbJ2Nob3duJywnLVInLCdyb290Ond3dy1kYXRhJyxzdHIoZGVzdCldLGNoZWNrPUZhbHNlKQogICAgcnVuKFsnZmluZCcsc3RyKGRlc3QpLCctdHlwZScsJ2QnLCctZXhlYycsJ2NobW9kJywnMDc1NScsJ3t9JywnKyddLGNoZWNrPUZhbHNlKQogICAgcnVuKFsnZmluZCcsc3RyKGRlc3QpLCctdHlwZScsJ2YnLCctZXhlYycsJ2NobW9kJywnMDY0NCcsJ3t9JywnKyddLGNoZWNrPUZhbHNlKQoKICAgIGZpbGVzPTAKICAgIHRvdGFsPTAKICAgIGZvciBmcCBpbiBkZXN0LnJnbG9iKCcqJyk6CiAgICAgICAgdHJ5OgogICAgICAgICAgICBpZiBmcC5pc19maWxlKCk6CiAgICAgICAgICAgICAgICBmaWxlcys9MQogICAgICAgICAgICAgICAgdG90YWwrPWZwLnN0YXQoKS5zdF9zaXplCiAgICAgICAgZXhjZXB0IE9TRXJyb3I6CiAgICAgICAgICAgIHBhc3MKCiAgICBjWydmYXN0ZGxfdXJsJ109X2hoX2Zhc3RkbF92OF91cmwoYykKICAgIGNbJ2Zhc3RkbF9sYXN0X3N5bmMnXT1pbnQodGltZS50aW1lKCkpCiAgICBjWydmYXN0ZGxfZmlsZXMnXT1maWxlcwogICAgY1snZmFzdGRsX2J5dGVzJ109dG90YWwKICAgIHNhdmVfc2VydmVyKGMpCgogICAgcnVudGltZV9lcnJvcnM9W10KICAgIGlmIHNlcnZpY2Vfc3RhdHVzKHNpZCk9PSdhY3RpdmUnIGFuZCB1ZHBfbGlzdGVuaW5nKGludChjLmdldCgncG9ydCcpIG9yIDApKToKICAgICAgICBmb3IgY21kIGluICgKICAgICAgICAgICAgJ3N2X2FsbG93ZG93bmxvYWQgMScsCiAgICAgICAgICAgICdzdl9hbGxvd3VwbG9hZCAwJywKICAgICAgICAgICAgJ3N2X3NlbmRfcmVzb3VyY2VzIDEnLAogICAgICAgICAgICAnc3ZfYWxsb3dfZGxmaWxlIDEnLAogICAgICAgICAgICBmJ3N2X2Rvd25sb2FkdXJsICJ7Y1siZmFzdGRsX3VybCJdfS8iJwogICAgICAgICk6CiAgICAgICAgICAgIHRyeToKICAgICAgICAgICAgICAgIHF1ZXJ5X3Jjb24oJzEyNy4wLjAuMScsaW50KGNbJ3BvcnQnXSksc3RyKGMuZ2V0KCdyY29uX3Bhc3N3b3JkJywnJykpLGNtZCwyLjApCiAgICAgICAgICAgIGV4Y2VwdCBFeGNlcHRpb24gYXMgZXhjOgogICAgICAgICAgICAgICAgcnVudGltZV9lcnJvcnMuYXBwZW5kKHN0cihleGMpKQoKICAgIGh0dHA9X2hoX2Zhc3RkbF92OF9odHRwX2NoZWNrKGludChzaWQpLGRlc3QpCiAgICBpZiBub3QgaHR0cFsnb2snXToKICAgICAgICByYWlzZSBSdW50aW1lRXJyb3IoCiAgICAgICAgICAgICdGYXN0REwgSFRUUCBpcyBub3Qgc2VydmluZyByYXcgQlNQIGJ5dGVzOiAnCiAgICAgICAgICAgICtqc29uLmR1bXBzKGh0dHBbJ2JhZCddWzo0MF0sZW5zdXJlX2FzY2lpPUZhbHNlKQogICAgICAgICkKCiAgICByZXR1cm4gewogICAgICAgICdvayc6VHJ1ZSwKICAgICAgICAnaWQnOnNpZCwKICAgICAgICAndXJsJzpjWydmYXN0ZGxfdXJsJ10sCiAgICAgICAgJ3Jvb3QnOnN0cihkZXN0KSwKICAgICAgICAnZmlsZXMnOmZpbGVzLAogICAgICAgICdieXRlcyc6dG90YWwsCiAgICAgICAgJ21hcHMnOmxlbihzb3VyY2VfYnNwWydnb29kJ10pLAogICAgICAgICdkaXJzJzpjb3BpZWQsCiAgICAgICAgJ2NvbmZpZyc6Y2ZnX3Jlc3VsdCwKICAgICAgICAnY2FzZV9yZXBhaXInOmNhc2VmaXgsCiAgICAgICAgJ3JlbW92ZWRfenRtcCc6cmVtb3ZlZF96dG1wLAogICAgICAgICdydW50aW1lX2FwcGxpZWQnOm5vdCBydW50aW1lX2Vycm9ycywKICAgICAgICAncnVudGltZV9lcnJvcnMnOnJ1bnRpbWVfZXJyb3JzWzo4XSwKICAgICAgICAnaHR0cCc6aHR0cCwKICAgICAgICAnYnNwX3NoYTI1Nl9tYXRjaCc6VHJ1ZQogICAgfQoKCmRlZiBmYXN0ZGxfc3RhdHVzKHNpZDppbnQpOgogICAgYz1sb2FkX3NlcnZlcihzaWQpCiAgICByb290PVBhdGgoY1sncGF0aCddKQogICAgZGVzdD1QYXRoKCcvc3J2L2h5cGVyLWNzMTYvZmFzdGRsJykvc3RyKGludChzaWQpKQogICAgdXJsPV9oaF9mYXN0ZGxfdjhfdXJsKGMpCiAgICBjZmc9cm9vdC8nY3N0cmlrZS9zZXJ2ZXIuY2ZnJwoKICAgIGN1cnJlbnQ9JycKICAgIGJsb2Nrcz0wCiAgICBjZmdfb2s9RmFsc2UKICAgIGlmIGNmZy5pc19maWxlKCk6CiAgICAgICAgdHJ5OgogICAgICAgICAgICByYXc9Y2ZnLnJlYWRfdGV4dChlbmNvZGluZz0ndXRmLTgnLGVycm9ycz0naWdub3JlJykKICAgICAgICAgICAgdmFscz1yZS5maW5kYWxsKHInKD9pbSleXHMqc3ZfZG93bmxvYWR1cmxccysiPyhbXiJcclxuXSspJyxyYXcpCiAgICAgICAgICAgIGlmIHZhbHM6IGN1cnJlbnQ9dmFsc1stMV0uc3RyaXAoKS5yc3RyaXAoJy8nKQogICAgICAgICAgICBibG9ja3M9bGVuKHJlLmZpbmRhbGwocicoP2ltKV5ccyovLyBIWVBFUi1IT1NUIEZBU1RETCBCRUdJTlxzKiQnLHJhdykpCiAgICAgICAgICAgIGNmZ19vaz0ocmF3LmNvdW50KCdcXG4nKTw1IG9yIHJhdy5jb3VudCgnXG4nKT4yKQogICAgICAgIGV4Y2VwdCBFeGNlcHRpb246CiAgICAgICAgICAgIHBhc3MKCiAgICBmaWxlcz0wCiAgICB0b3RhbD0wCiAgICBpZiBkZXN0LmlzX2RpcigpOgogICAgICAgIGZvciBmcCBpbiBkZXN0LnJnbG9iKCcqJyk6CiAgICAgICAgICAgIHRyeToKICAgICAgICAgICAgICAgIGlmIGZwLmlzX2ZpbGUoKToKICAgICAgICAgICAgICAgICAgICBmaWxlcys9MQogICAgICAgICAgICAgICAgICAgIHRvdGFsKz1mcC5zdGF0KCkuc3Rfc2l6ZQogICAgICAgICAgICBleGNlcHQgT1NFcnJvcjoKICAgICAgICAgICAgICAgIHBhc3MKCiAgICBzb3VyY2U9X2hoX2Zhc3RkbF92OF92YWxpZGF0ZV9ic3BfZGlyKHJvb3QvJ2NzdHJpa2UvbWFwcycpCiAgICBtaXJyb3I9X2hoX2Zhc3RkbF92OF92YWxpZGF0ZV9ic3BfZGlyKGRlc3QvJ21hcHMnKQogICAgaHR0cD1faGhfZmFzdGRsX3Y4X2h0dHBfY2hlY2soaW50KHNpZCksZGVzdCkgaWYgZGVzdC5pc19kaXIoKSBlbHNlIHsnb2snOkZhbHNlLCdjaGVja2VkJzowLCdiYWQnOlt7J2Vycm9yJzonRmFzdERMIG1pc3NpbmcnfV19CgogICAgY29uZmlndXJlZD1ib29sKAogICAgICAgIGRlc3QuaXNfZGlyKCkKICAgICAgICBhbmQgY3VycmVudC5yc3RyaXAoJy8nKT09dXJsLnJzdHJpcCgnLycpCiAgICAgICAgYW5kIGJsb2Nrcz09MQogICAgICAgIGFuZCBjZmdfb2sKICAgICAgICBhbmQgbm90IHNvdXJjZVsnYmFkJ10KICAgICAgICBhbmQgbm90IG1pcnJvclsnYmFkJ10KICAgICAgICBhbmQgbGVuKHNvdXJjZVsnZ29vZCddKT09bGVuKG1pcnJvclsnZ29vZCddKQogICAgICAgIGFuZCBodHRwWydvayddCiAgICApCgogICAgcmV0dXJuIHsKICAgICAgICAnb2snOlRydWUsCiAgICAgICAgJ2lkJzpzaWQsCiAgICAgICAgJ3VybCc6dXJsLAogICAgICAgICdjb25maWd1cmVkX3VybCc6Y3VycmVudCwKICAgICAgICAnY29uZmlndXJlZCc6Y29uZmlndXJlZCwKICAgICAgICAncm9vdCc6c3RyKGRlc3QpLAogICAgICAgICdleGlzdHMnOmRlc3QuaXNfZGlyKCksCiAgICAgICAgJ2ZpbGVzJzpmaWxlcywKICAgICAgICAnYnl0ZXMnOnRvdGFsLAogICAgICAgICdzb3VyY2VfbWFwcyc6bGVuKHNvdXJjZVsnZ29vZCddKSwKICAgICAgICAnZmFzdGRsX21hcHMnOmxlbihtaXJyb3JbJ2dvb2QnXSksCiAgICAgICAgJ3NvdXJjZV9iYWRfbWFwcyc6c291cmNlWydiYWQnXSwKICAgICAgICAnZmFzdGRsX2JhZF9tYXBzJzptaXJyb3JbJ2JhZCddLAogICAgICAgICdodHRwX29rJzpib29sKGh0dHBbJ29rJ10pLAogICAgICAgICdodHRwX2NoZWNrZWRfbWFwcyc6aW50KGh0dHAuZ2V0KCdjaGVja2VkJykgb3IgMCksCiAgICAgICAgJ2h0dHBfYmFkJzpodHRwLmdldCgnYmFkJyxbXSlbOjIwXSwKICAgICAgICAnZmFzdGRsX2Jsb2Nrcyc6YmxvY2tzLAogICAgICAgICdjZmdfb2snOmNmZ19vaywKICAgICAgICAnbGFzdF9zeW5jJzppbnQoYy5nZXQoJ2Zhc3RkbF9sYXN0X3N5bmMnKSBvciAwKQogICAgfQojIEhZUEVSLUhPU1QgRkFTVERMIEZJTkFMIE9WRVJSSURFIFY4IEVORAonJycKCmlmIEJFR0lOIGluIHMgYW5kIEVORCBpbiBzOgogICAgc3RhcnQ9cy5pbmRleChCRUdJTikKICAgIHN0b3A9cy5pbmRleChFTkQsc3RhcnQpK2xlbihFTkQpCiAgICBzPXNbOnN0YXJ0XStvdmVycmlkZS5zdHJpcCgpK3Nbc3RvcDpdCmVsc2U6CiAgICBtPXJlLnNlYXJjaChyJyg/bSleZGVmIG1haW5cKFwpOicscykKICAgIGlmIG5vdCBtOgogICAgICAgIHJhaXNlIFN5c3RlbUV4aXQoJ1tQQVRDSCBFUlJPUl0gZGVmIG1haW4oKSBub3QgZm91bmQnKQogICAgcz1zWzptLnN0YXJ0KCldK292ZXJyaWRlLnN0cmlwKCkrJ1xuXG4nK3NbbS5zdGFydCgpOl0KCmN0bC53cml0ZV90ZXh0KHMsZW5jb2Rpbmc9J3V0Zi04JykK' | base64 -d > "$PATCHER"
python3 "$PATCHER" "$SRC_CTL"
python3 -m py_compile "$SRC_CTL"
install -m 0755 "$SRC_CTL" "$LIVE_CTL"
python3 -m py_compile "$LIVE_CTL"
rm -f "$PATCHER"

echo "[4/10] Firewall..."
if command -v ufw >/dev/null 2>&1; then
  ufw allow 80/tcp >/dev/null 2>&1 || true
fi

echo "[5/10] Clean FastDL sync..."
"$LIVE_CTL" fastdl-sync "$SID"

echo "[6/10] Verify source == FastDL BSP checksums..."
python3 - "$CSTRIKE/maps" "$FASTDL/maps" <<'PY'
from pathlib import Path
import hashlib,sys
src=Path(sys.argv[1]); dst=Path(sys.argv[2])
def sha(p):
    h=hashlib.sha256()
    with p.open('rb') as f:
        for c in iter(lambda:f.read(1024*1024),b''):
            h.update(c)
    return h.hexdigest()
sm={p.name:sha(p) for p in src.glob('*.bsp')}
dm={p.name:sha(p) for p in dst.glob('*.bsp')}
bad=[n for n,h in sm.items() if dm.get(n)!=h]
extra=sorted(set(dm)-set(sm))
print("source maps:",len(sm))
print("fastdl maps:",len(dm))
print("mismatched:",len(bad))
print("extra:",len(extra))
if bad or extra:
    print("BAD:",bad)
    print("EXTRA:",extra)
    raise SystemExit(21)
PY

echo "[7/10] Verify EVERY BSP through nginx using Host: $PUBLIC ..."
python3 - "$FASTDL/maps" "$SID" <<'PY'
from pathlib import Path
import urllib.request,urllib.error,urllib.parse,sys
maps=Path(sys.argv[1]); sid=int(sys.argv[2])
bad=[]; good=0
for p in sorted(maps.glob('*.bsp')):
    url='http://127.0.0.1/fastdl/%d/maps/%s'%(sid,urllib.parse.quote(p.name,safe='._-+()[]'))
    req=urllib.request.Request(url,headers={'Host':'90.189.208.25','Range':'bytes=0-3','User-Agent':'HYPER-HOST-FastDL-v8'})
    code=0; head=b''; marker=''
    try:
        with urllib.request.urlopen(req,timeout=5) as r:
            code=int(getattr(r,'status',200) or 200)
            head=r.read(4)
            marker=str(r.headers.get('X-Hyper-FastDL') or '')
    except urllib.error.HTTPError as e:
        code=e.code
        head=e.read(4)
    except Exception as e:
        bad.append((p.name,0,None,'',str(e)))
        continue
    ver=int.from_bytes(head,'little') if len(head)==4 else None
    if code not in (200,206) or ver!=30 or marker!='raw':
        bad.append((p.name,code,ver,head.hex(),marker))
    else:
        good+=1
print("HTTP raw BSP OK:",good)
print("HTTP raw BSP BAD:",len(bad))
if bad:
    for x in bad[:50]: print("BAD",x)
    raise SystemExit(22)
PY

echo "[8/10] Restart CS server and re-apply runtime FastDL..."
systemctl restart "hyper-cs16@${SID}.service"
sleep 3
"$LIVE_CTL" fastdl-sync "$SID"

echo "[9/10] Panel status..."
"$LIVE_CTL" fastdl-status "$SID"

echo "[10/10] Runtime cvars..."
"$LIVE_CTL" rcon "$SID" "sv_downloadurl" || true
"$LIVE_CTL" rcon "$SID" "sv_allowdownload" || true
"$LIVE_CTL" rcon "$SID" "sv_allow_dlfile" || true

echo
echo "Direct local HTTP proof:"
PROBE="$(find "$FASTDL/maps" -maxdepth 1 -type f -name 'zm_303.bsp' -print -quit)"
[[ -n "$PROBE" ]] || PROBE="$(find "$FASTDL/maps" -maxdepth 1 -type f -name '*.bsp' -print -quit)"
if [[ -n "$PROBE" ]]; then
  NAME="$(basename "$PROBE")"
  curl -sS -D /tmp/hh-fastdl-v8.headers -H "Host: $PUBLIC" --range 0-3 "http://127.0.0.1/fastdl/$SID/maps/$NAME" -o /tmp/hh-fastdl-v8.head
  sed -n '1,20p' /tmp/hh-fastdl-v8.headers
  echo -n "First 4 bytes: "
  xxd -p -l4 /tmp/hh-fastdl-v8.head
  echo -n "BSP version: "
  python3 - <<'PY'
from pathlib import Path
b=Path('/tmp/hh-fastdl-v8.head').read_bytes()[:4]
print(int.from_bytes(b,'little') if len(b)==4 else None)
PY
  rm -f /tmp/hh-fastdl-v8.headers /tmp/hh-fastdl-v8.head
fi

echo
echo "================================================================"
echo " [SUCCESS] FASTDL FINAL v8"
echo "================================================================"
echo "URL: http://$PUBLIC/fastdl/$SID/"
echo "Source BSP and FastDL BSP are byte-identical."
echo "Every published BSP returned GoldSrc version 30 through nginx."
echo "The panel fastdl-sync/status commands now use the same verification."
echo "Backup: $BACKUP"
echo
echo "NOTE: old-zombie.ru / SSL / HTTPS is NOT used for FastDL."
echo "External clients need TCP 80 forwarded to $LAN:80."
