#!/usr/bin/env bash
set -Eeuo pipefail

# HYPER-HOST CS16 v3.23 — COHERENT RUNTIME GUARD
#
# Requires installed v3.20 + v3.22 controller.
# Prevents cstrike-only legacy runtimes from being mixed with an unrelated
# modern HLDS engine. Full server-root archives that carry their own hlds_linux
# remain eligible for exact runtime preservation.

SID="${1:-20}"
LIVE_CTL="${HYPER_CTL:-/usr/local/sbin/hyper-cs16-ctl}"
REPO="${HYPER_REPO:-$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)}"
REPO_CTL="$REPO/cs16-panel/bin/hyper-cs16-ctl"
DOMAIN="www.avito.hyper-host.pw"
STAMP="$(date +%Y%m%d-%H%M%S)"
BACKUP="/root/hyper-cs16-v3.23-backup-${STAMP}"
LOG="/root/hyper-cs16-v3.23-${STAMP}.log"

mkdir -p "$BACKUP"
exec > >(tee -a "$LOG") 2>&1

die() {
  echo
  echo "[ERROR] $*"
  echo "[ERROR] Log: $LOG"
  echo "[ERROR] Backup: $BACKUP"
  exit 1
}

backup_file() {
  local f="$1"
  [[ -f "$f" ]] || return 0
  local safe
  safe="$(printf '%s' "$f" | sed 's#^/##;s#/#__#g')"
  cp -a "$f" "$BACKUP/$safe"
}

echo "============================================================"
echo " HYPER-HOST CS16 v3.23 — COHERENT RUNTIME GUARD"
echo "============================================================"
echo "Server:     $SID"
echo "Live ctl:   $LIVE_CTL"
echo "Repo:       $REPO"
echo "Backup:     $BACKUP"
echo "Log:        $LOG"
echo

[[ "$SID" =~ ^[0-9]+$ ]] || die "Invalid server id: $SID"
[[ -f "$LIVE_CTL" ]] || die "Live controller not found: $LIVE_CTL"
[[ -f "$REPO_CTL" ]] || die "Repository controller not found: $REPO_CTL"
grep -q "def _v320_prepare_runtime" "$LIVE_CTL" || die "v3.20 adaptive runtime is not installed"
grep -q "def _v322_skip_missing_optional_refs" "$LIVE_CTL" || die "v3.22 optional-file sanitizer is not installed"

PATCHER="$(mktemp /tmp/hh-v323.XXXXXX.py)"
ROOTS="$(mktemp /tmp/hh-v323-roots.XXXXXX)"
NGTMP="$(mktemp /tmp/hh-v323-nginx.XXXXXX)"
trap 'rm -f "$PATCHER" "$ROOTS" "$NGTMP" 2>/dev/null || true' EXIT
printf '%s' 'ZnJvbSBfX2Z1dHVyZV9fIGltcG9ydCBhbm5vdGF0aW9ucwoKaW1wb3J0IGFzdAppbXBvcnQgb3MKaW1wb3J0IHB5X2NvbXBpbGUKaW1wb3J0IHJlCmltcG9ydCBzeXMKZnJvbSBwYXRobGliIGltcG9ydCBQYXRoCgpNQVJLRVIgPSAnIyA+Pj4gSFlQRVItSE9TVCB2My4yMyBDT0hFUkVOVCBSVU5USU1FIEdVQVJEID4+PicKCkhFTFBFUiA9IHInJycKIyA+Pj4gSFlQRVItSE9TVCB2My4yMyBDT0hFUkVOVCBSVU5USU1FIEdVQVJEID4+PgpfVjMyM19PRkZJQ0lBTF9BTVhYX01PRFVMRVM9ewogICAgJ2NzdHJpa2VfYW14eF9pMzg2LnNvJywnY3N4X2FteHhfaTM4Ni5zbycsJ2VuZ2luZV9hbXh4X2kzODYuc28nLAogICAgJ2Zha2VtZXRhX2FteHhfaTM4Ni5zbycsJ2Z1bl9hbXh4X2kzODYuc28nLCdnZW9pcF9hbXh4X2kzODYuc28nLAogICAgJ2hhbXNhbmR3aWNoX2FteHhfaTM4Ni5zbycsJ2pzb25fYW14eF9pMzg2LnNvJywnbXlzcWxfYW14eF9pMzg2LnNvJywKICAgICdudmF1bHRfYW14eF9pMzg2LnNvJywncmVnZXhfYW14eF9pMzg2LnNvJywnc29ja2V0c19hbXh4X2kzODYuc28nLAogICAgJ3NxbGl0ZV9hbXh4X2kzODYuc28nLAp9CgoKZGVmIF92MzIzX3BheWxvYWRfY3N0cmlrZShwYXlsb2FkOlBhdGgsbGF5b3V0OnN0ciktPlBhdGg6CiAgICByZXR1cm4gcGF5bG9hZC8nY3N0cmlrZScgaWYgbGF5b3V0PT0nc2VydmVyLXJvb3QnIGVsc2UgcGF5bG9hZAoKCmRlZiBfdjMyM19kZXRlY3RfcHJldmlvdXNfYnVpbGQoY3N0cmlrZTpQYXRoKS0+bGlzdFtzdHJdOgogICAgYnVpbGRzPVtdCiAgICBsb2dzPWNzdHJpa2UvJ2xvZ3MnCiAgICBpZiBub3QgbG9ncy5pc19kaXIoKToKICAgICAgICByZXR1cm4gYnVpbGRzCiAgICBzZWVuPTAKICAgIGZvciBwIGluIHNvcnRlZChsb2dzLmdsb2IoJyoubG9nJykpOgogICAgICAgIGlmIHNlZW4+PTgwOiBicmVhawogICAgICAgIHNlZW4rPTEKICAgICAgICB0cnk6CiAgICAgICAgICAgIGRhdGE9cC5yZWFkX2J5dGVzKClbOjUxMioxMDI0XQogICAgICAgIGV4Y2VwdCBFeGNlcHRpb246CiAgICAgICAgICAgIGNvbnRpbnVlCiAgICAgICAgZm9yIG0gaW4gcmUuZmluZGl0ZXIocmInNDgvMVsuXTFbLl0yWy5dNy9TdGRpby8/WyBdKihbMC05XXszLDZ9KScsZGF0YSk6CiAgICAgICAgICAgIGI9bS5ncm91cCgxKS5kZWNvZGUoJ2FzY2lpJywnaWdub3JlJykKICAgICAgICAgICAgaWYgYiBhbmQgYiBub3QgaW4gYnVpbGRzOgogICAgICAgICAgICAgICAgYnVpbGRzLmFwcGVuZChiKQogICAgICAgICAgICAgICAgaWYgbGVuKGJ1aWxkcyk+PTY6CiAgICAgICAgICAgICAgICAgICAgcmV0dXJuIGJ1aWxkcwogICAgcmV0dXJuIGJ1aWxkcwoKCmRlZiBfdjMyM19hbmFseXplX2FyY2hpdmVfcnVudGltZShwYXlsb2FkOlBhdGgsbGF5b3V0OnN0ciktPmRpY3Q6CiAgICBjc3RyaWtlPV92MzIzX3BheWxvYWRfY3N0cmlrZShwYXlsb2FkLGxheW91dCkKICAgIHJvb3Q9cGF5bG9hZCBpZiBsYXlvdXQ9PSdzZXJ2ZXItcm9vdCcgZWxzZSBwYXlsb2FkLnBhcmVudAoKICAgIGVuZ2luZV9maWxlcz1bXQogICAgaWYgbGF5b3V0PT0nc2VydmVyLXJvb3QnOgogICAgICAgIGZvciByZWwgaW4gKCdobGRzX2xpbnV4JywnZW5naW5lX2k0ODYuc28nLCdjb3JlLnNvJywnZmlsZXN5c3RlbV9zdGRpby5zbycpOgogICAgICAgICAgICBpZiAocGF5bG9hZC9yZWwpLmlzX2ZpbGUoKTogZW5naW5lX2ZpbGVzLmFwcGVuZChyZWwpCgogICAgcnVudGltZV9jYW5kaWRhdGVzPSgKICAgICAgICAnZGxscy9jcy5zbycsCiAgICAgICAgJ2FkZG9ucy9tZXRhbW9kL2RsbHMvbWV0YW1vZC5zbycsCiAgICAgICAgJ2FkZG9ucy9tZXRhbW9kL2RsbHMvbWV0YW1vZF9pMzg2LnNvJywKICAgICAgICAnYWRkb25zL21ldGFtb2QvbWV0YW1vZF9pMzg2LnNvJywKICAgICAgICAnYWRkb25zL2FteG1vZHgvZGxscy9hbXhtb2R4LnNvJywKICAgICAgICAnYWRkb25zL2FteG1vZHgvZGxscy9hbXhtb2R4X21tX2kzODYuc28nLAogICAgICAgICdhZGRvbnMvcmV1bmlvbi9kbGxzL3JldW5pb24uc28nLAogICAgICAgICdhZGRvbnMvZHByb3RvL2Rwcm90b19pMzg2LnNvJywKICAgICkKICAgIHJ1bnRpbWVfZmlsZXM9W3JlbCBmb3IgcmVsIGluIHJ1bnRpbWVfY2FuZGlkYXRlcyBpZiAoY3N0cmlrZS9yZWwpLmlzX2ZpbGUoKV0KCiAgICBtb2R1bGVzPVtdCiAgICBtb2RkaXI9Y3N0cmlrZS8nYWRkb25zL2FteG1vZHgvbW9kdWxlcycKICAgIGlmIG1vZGRpci5pc19kaXIoKToKICAgICAgICBtb2R1bGVzPXNvcnRlZChwLm5hbWUgZm9yIHAgaW4gbW9kZGlyLmdsb2IoJyouc28nKSBpZiBwLmlzX2ZpbGUoKSkKCiAgICBoYXNfbWF0Y2hpbmdfZW5naW5lPWJvb2woCiAgICAgICAgbGF5b3V0PT0nc2VydmVyLXJvb3QnIGFuZAogICAgICAgIChwYXlsb2FkLydobGRzX2xpbnV4JykuaXNfZmlsZSgpIGFuZAogICAgICAgIF9lbGZfYml0cyhwYXlsb2FkLydobGRzX2xpbnV4Jyk9PTMyCiAgICApCiAgICBjYXJyaWVzX2NzdHJpa2VfcnVudGltZT1ib29sKHJ1bnRpbWVfZmlsZXMgb3IgbW9kdWxlcykKICAgIHBhcnRpYWw9Ym9vbChjYXJyaWVzX2NzdHJpa2VfcnVudGltZSBhbmQgbm90IGhhc19tYXRjaGluZ19lbmdpbmUpCiAgICBidWlsZHM9X3YzMjNfZGV0ZWN0X3ByZXZpb3VzX2J1aWxkKGNzdHJpa2UpCgogICAgcmVhc29uPScnCiAgICBpZiBwYXJ0aWFsOgogICAgICAgIHJlYXNvbj0nYXJjaGl2ZSBjb250YWlucyBjc3RyaWtlIHJ1bnRpbWUgYnV0IGRvZXMgbm90IGNvbnRhaW4gaXRzIG1hdGNoaW5nIExpbnV4IGhsZHNfbGludXggZW5naW5lJwogICAgICAgIGlmIGJ1aWxkczoKICAgICAgICAgICAgcmVhc29uKz0nOyBhcmNoaXZlZCBzZXJ2ZXIgbG9ncyBzaG93IGJ1aWxkKHMpOiAnKycsICcuam9pbihidWlsZHMpCgogICAgcmV0dXJuIHsKICAgICAgICAnbGF5b3V0JzpsYXlvdXQsCiAgICAgICAgJ2hhc19tYXRjaGluZ19lbmdpbmUnOmhhc19tYXRjaGluZ19lbmdpbmUsCiAgICAgICAgJ2VuZ2luZV9maWxlcyc6ZW5naW5lX2ZpbGVzLAogICAgICAgICdjYXJyaWVzX2NzdHJpa2VfcnVudGltZSc6Y2Fycmllc19jc3RyaWtlX3J1bnRpbWUsCiAgICAgICAgJ3J1bnRpbWVfZmlsZXMnOnJ1bnRpbWVfZmlsZXMsCiAgICAgICAgJ2FteHhfbW9kdWxlcyc6bW9kdWxlcywKICAgICAgICAncGFydGlhbF9sZWdhY3lfcnVudGltZSc6cGFydGlhbCwKICAgICAgICAnYXJjaGl2ZWRfZW5naW5lX2J1aWxkcyc6YnVpbGRzLAogICAgICAgICdyZWFzb24nOnJlYXNvbiwKICAgIH0KCgpkZWYgX3YzMjNfZGlzYWJsZV9sZWdhY3lfYXV0aF9wbHVnaW5zKGNzdHJpa2U6UGF0aCktPmxpc3Rbc3RyXToKICAgIGFjdGlvbnM9W10KICAgIG1wPWNzdHJpa2UvJ2FkZG9ucy9tZXRhbW9kL3BsdWdpbnMuaW5pJwogICAgaWYgbm90IG1wLmlzX2ZpbGUoKToKICAgICAgICByZXR1cm4gYWN0aW9ucwogICAgcmF3PW1wLnJlYWRfYnl0ZXMoKS5yZXBsYWNlKGInXHJcbicsYidcbicpLnJlcGxhY2UoYidccicsYidcbicpLmRlY29kZSgnbGF0aW4xJywnaWdub3JlJykKICAgIG91dD1bXTsgY2hhbmdlZD1GYWxzZQogICAgZm9yIGxpbmUgaW4gcmF3LnNwbGl0bGluZXMoKToKICAgICAgICBzdD1saW5lLnN0cmlwKCk7IGxvdz1zdC5sb3dlcigpCiAgICAgICAgYWN0aXZlPWJvb2woc3QgYW5kIG5vdCBzdC5zdGFydHN3aXRoKCgnOycsJyMnLCcvLycpKSkKICAgICAgICBpZiBhY3RpdmUgYW5kICgoJ3JldW5pb24nIGluIGxvdykgb3IgKCdkcHJvdG8nIGluIGxvdykpIGFuZCAnLnNvJyBpbiBsb3c6CiAgICAgICAgICAgIG91dC5hcHBlbmQoJzsgSFlQRVItSE9TVCB2My4yMyBkaXNhYmxlZCBsZWdhY3kgYXV0aCBwbHVnaW4gZnJvbSBwYXJ0aWFsIHJ1bnRpbWU6ICcrbGluZSkKICAgICAgICAgICAgY2hhbmdlZD1UcnVlCiAgICAgICAgICAgIGFjdGlvbnMuYXBwZW5kKCdkaXNhYmxlZCBsZWdhY3kgJysoJ1JldW5pb24nIGlmICdyZXVuaW9uJyBpbiBsb3cgZWxzZSAnZHByb3RvJykrJyBsb2FkZXInKQogICAgICAgIGVsc2U6CiAgICAgICAgICAgIG91dC5hcHBlbmQobGluZSkKICAgIGlmIGNoYW5nZWQ6CiAgICAgICAgbXAud3JpdGVfYnl0ZXMoKCdcbicuam9pbihvdXQpLnJzdHJpcCgpKydcbicpLmVuY29kZSgnbGF0aW4xJywncmVwbGFjZScpKQogICAgcmV0dXJuIGFjdGlvbnMKCgpkZWYgX3YzMjNfcmVtb3ZlX2xlZ2FjeV9ydW50aW1lX2ZpbGVzKHBhdGg6UGF0aCktPmxpc3Rbc3RyXToKICAgIGNzdHJpa2U9cGF0aC8nY3N0cmlrZSc7IGFjdGlvbnM9W10KCiAgICAjIEdhbWVETEw6IG11c3QgbWF0Y2ggdGhlIGVuZ2luZSBzZWxlY3RlZCBiZWxvdy4KICAgIGNzPWNzdHJpa2UvJ2RsbHMvY3Muc28nCiAgICBpZiBjcy5pc19maWxlKCk6CiAgICAgICAgY3MudW5saW5rKCkKICAgICAgICBhY3Rpb25zLmFwcGVuZCgncmVtb3ZlZCB1cGxvYWRlZCBjcy5zbyB3aXRob3V0IG1hdGNoaW5nIGVuZ2luZScpCgogICAgIyBNZXRhbW9kIGV4ZWN1dGFibGUgcnVudGltZS4KICAgIGZvciBwIGluICgKICAgICAgICBjc3RyaWtlLydhZGRvbnMvbWV0YW1vZC9kbGxzL21ldGFtb2Quc28nLAogICAgICAgIGNzdHJpa2UvJ2FkZG9ucy9tZXRhbW9kL2RsbHMvbWV0YW1vZF9pMzg2LnNvJywKICAgICAgICBjc3RyaWtlLydhZGRvbnMvbWV0YW1vZC9tZXRhbW9kX2kzODYuc28nLAogICAgKToKICAgICAgICB0cnk6CiAgICAgICAgICAgIGlmIHAuaXNfZmlsZSgpOgogICAgICAgICAgICAgICAgcC51bmxpbmsoKTsgYWN0aW9ucy5hcHBlbmQoJ3JlbW92ZWQgdXBsb2FkZWQgTWV0YW1vZCBsb2FkZXIgJytwLm5hbWUpCiAgICAgICAgZXhjZXB0IEV4Y2VwdGlvbjoKICAgICAgICAgICAgcGFzcwoKICAgICMgQU1YWCBsb2FkZXI6IGNvbmZpZ3MvcGx1Z2lucy9jb250ZW50IHN0YXkgZXhhY3RseSBmcm9tIHRoZSBhc3NlbWJseS4KICAgIGRsbHM9Y3N0cmlrZS8nYWRkb25zL2FteG1vZHgvZGxscycKICAgIGlmIGRsbHMuaXNfZGlyKCk6CiAgICAgICAgZm9yIHAgaW4gZGxscy5nbG9iKCcqLnNvJyk6CiAgICAgICAgICAgIHRyeToKICAgICAgICAgICAgICAgIHAudW5saW5rKCk7IGFjdGlvbnMuYXBwZW5kKCdyZW1vdmVkIHVwbG9hZGVkIEFNWFggbG9hZGVyICcrcC5uYW1lKQogICAgICAgICAgICBleGNlcHQgRXhjZXB0aW9uOgogICAgICAgICAgICAgICAgcGFzcwoKICAgICMgUmVwbGFjZSBvZmZpY2lhbCBBTVhYIG1vZHVsZXMgYXMgb25lIEFCSS1jb2hlcmVudCBzZXQuIFVua25vd24gY3VzdG9tCiAgICAjIG1vZHVsZXMgYXJlIHByZXNlcnZlZCBhbmQgY2FuIHN0aWxsIGJlIGRpYWdub3NlZCBieSBub3JtYWwgc3RhcnR1cCBjaGVja3MuCiAgICBtb2RzPWNzdHJpa2UvJ2FkZG9ucy9hbXhtb2R4L21vZHVsZXMnCiAgICBpZiBtb2RzLmlzX2RpcigpOgogICAgICAgIGZvciBwIGluIG1vZHMuZ2xvYignKi5zbycpOgogICAgICAgICAgICBpZiBwLm5hbWUubG93ZXIoKSBpbiBfVjMyM19PRkZJQ0lBTF9BTVhYX01PRFVMRVM6CiAgICAgICAgICAgICAgICB0cnk6CiAgICAgICAgICAgICAgICAgICAgcC51bmxpbmsoKQogICAgICAgICAgICAgICAgZXhjZXB0IEV4Y2VwdGlvbjoKICAgICAgICAgICAgICAgICAgICBwYXNzCgogICAgIyBIYW0vZ2FtZWRhdGEgbXVzdCBtYXRjaCB0aGUgbWFuYWdlZCBBTVhYIGJpbmFyeSBzZXQuCiAgICB0cnk6CiAgICAgICAgKGNzdHJpa2UvJ2FkZG9ucy9hbXhtb2R4L2NvbmZpZ3MvaGFtZGF0YS5pbmknKS51bmxpbmsoKQogICAgZXhjZXB0IEV4Y2VwdGlvbjoKICAgICAgICBwYXNzCiAgICBnZD1jc3RyaWtlLydhZGRvbnMvYW14bW9keC9kYXRhL2dhbWVkYXRhJwogICAgaWYgZ2QuaXNfZGlyKCk6CiAgICAgICAgc2h1dGlsLnJtdHJlZShnZCxpZ25vcmVfZXJyb3JzPVRydWUpCgogICAgYWN0aW9ucy5leHRlbmQoX3YzMjNfZGlzYWJsZV9sZWdhY3lfYXV0aF9wbHVnaW5zKGNzdHJpa2UpKQogICAgcmV0dXJuIGFjdGlvbnMKCgpkZWYgX3YzMjNfcHJlcGFyZV9jb2hlcmVudF9ydW50aW1lKHBhdGg6UGF0aCxjOmRpY3Qsc2NvcGU6ZGljdCktPmRpY3Q6CiAgICBpZiBub3QgYm9vbChzY29wZS5nZXQoJ3BhcnRpYWxfbGVnYWN5X3J1bnRpbWUnKSk6CiAgICAgICAgcmV0dXJuIHsKICAgICAgICAgICAgJ29rJzpUcnVlLCdmb3JjZWQnOkZhbHNlLCdyZWFzb24nOicnLAogICAgICAgICAgICAnYXJjaGl2ZV9zY29wZSc6c2NvcGUsJ2FjdGlvbnMnOltdLAogICAgICAgICAgICAncnVudGltZSc6X3YzMjBfcnVudGltZV9pbnZlbnRvcnkocGF0aCksCiAgICAgICAgfQoKICAgIGFjdGlvbnM9W10KICAgIGFjdGlvbnMuZXh0ZW5kKF92MzIzX3JlbW92ZV9sZWdhY3lfcnVudGltZV9maWxlcyhwYXRoKSkKCiAgICAjIEEgY3N0cmlrZS1vbmx5IHJ1bnRpbWUgY2Fubm90IGJlIHByZXNlcnZlZCBzYWZlbHkgYmVjYXVzZSB0aGUgbWF0Y2hpbmcKICAgICMgZW5naW5lIGlzIGFic2VudC4gQnVpbGQgb25lIGNvbXBsZXRlLCBtdXR1YWxseSBjb21wYXRpYmxlIExpbnV4IHN0YWNrLgogICAgaW5zdGFsbF9yZWhsZHMocGF0aCkKICAgIGFjdGlvbnMuYXBwZW5kKCdpbnN0YWxsZWQgY29oZXJlbnQgUmVITERTICcrc3RyKFJFSExEU19WRVJTSU9OKSsnICsgUmVHYW1lRExMICcrc3RyKFJFR0FNRURMTF9WRVJTSU9OKSkKCiAgICBpbnN0YWxsX21ldGFtb2RfcmVobGRzKHBhdGgpCiAgICBhY3Rpb25zLmFwcGVuZCgnaW5zdGFsbGVkIGNvaGVyZW50IE1ldGFtb2QtUiAnK3N0cihNRVRBTU9EX1ZFUlNJT04pKQoKICAgIGlmICdfdjMxNl9yZWZyZXNoX2FteHhfcGxhdGZvcm0nIGluIGdsb2JhbHMoKToKICAgICAgICBhY3Rpb25zLmV4dGVuZChfdjMxNl9yZWZyZXNoX2FteHhfcGxhdGZvcm0ocGF0aCkpCiAgICBlbHNlOgogICAgICAgIGluc3RhbGxfYW14eChwYXRoKQogICAgICAgIGFjdGlvbnMuYXBwZW5kKCdpbnN0YWxsZWQgY29oZXJlbnQgQU1YWCBydW50aW1lJykKCiAgICAjIEluc3RhbGwgbWFuYWdlZCBSZUFQSSBvbmx5IHdoZW4gYWN0dWFsIHBsdWdpbnMgcmVxdWlyZSBpdC4KICAgIHRyeToKICAgICAgICByZWFwaT1fZW5zdXJlX3JlYXBpX2NvbXBhdGlibGVfc3RhY2socGF0aCkKICAgICAgICBhY3Rpb25zLmV4dGVuZChsaXN0KHJlYXBpLmdldCgnYWN0aW9ucycpIG9yIFtdKSkKICAgIGV4Y2VwdCBFeGNlcHRpb24gYXMgZXhjOgogICAgICAgIHJlYXBpPXsncmVxdWlyZWQnOkZhbHNlLCdhY3Rpb25zJzpbXSwnd2FybmluZyc6c3RyKGV4Yyl9CgogICAgYWN0aW9ucy5leHRlbmQobGlzdCgoX3YzMjBfc2FuaXRpemVfbG9hZGVyX2NoYWluKHBhdGgpLmdldCgnYWN0aW9ucycpIG9yIFtdKSkpCiAgICBub3JtYWxpemVfcGVybWlzc2lvbnMocGF0aCkKCiAgICByZXR1cm4gewogICAgICAgICdvayc6VHJ1ZSwKICAgICAgICAnZm9yY2VkJzpUcnVlLAogICAgICAgICdyZWFzb24nOnN0cihzY29wZS5nZXQoJ3JlYXNvbicpIG9yICdwYXJ0aWFsIGNzdHJpa2UgcnVudGltZSB3aXRob3V0IG1hdGNoaW5nIGVuZ2luZScpLAogICAgICAgICdhcmNoaXZlX3Njb3BlJzpzY29wZSwKICAgICAgICAnYWN0aW9ucyc6bGlzdChkaWN0LmZyb21rZXlzKGFjdGlvbnMpKSwKICAgICAgICAnYXV0aF9ub3RlJzonbGVnYWN5IFJldW5pb24vZHByb3RvIGxvYWRlciB3YXMgZGlzYWJsZWQ7IGluc3RhbGwgYSBjb21wYXRpYmxlIGF1dGggbW9kdWxlIHNlcGFyYXRlbHkgaWYgbm9uLVN0ZWFtIGFjY2VzcyBpcyByZXF1aXJlZCcsCiAgICAgICAgJ3JlYXBpJzpyZWFwaSwKICAgICAgICAncnVudGltZSc6X3YzMjBfcnVudGltZV9pbnZlbnRvcnkocGF0aCksCiAgICB9CgoKZGVmIF92MzIzX3J1bnRpbWVfYmFja3VwKHBhdGg6UGF0aCxiYWNrdXA6UGF0aCk6CiAgICByZWxzPSgKICAgICAgICAnaGxkc19saW51eCcsJ2VuZ2luZV9pNDg2LnNvJywnY29yZS5zbycsJ2ZpbGVzeXN0ZW1fc3RkaW8uc28nLCdkZW1vcGxheWVyLnNvJywKICAgICAgICAnY3N0cmlrZS9kbGxzL2NzLnNvJywnY3N0cmlrZS9saWJsaXN0LmdhbScsJ2NzdHJpa2UvYWRkb25zL21ldGFtb2QnLAogICAgICAgICdjc3RyaWtlL2FkZG9ucy9yZXVuaW9uJywnY3N0cmlrZS9hZGRvbnMvZHByb3RvJywKICAgICAgICAnY3N0cmlrZS9hZGRvbnMvYW14bW9keC9kbGxzJywnY3N0cmlrZS9hZGRvbnMvYW14bW9keC9tb2R1bGVzJywKICAgICAgICAnY3N0cmlrZS9hZGRvbnMvYW14bW9keC9jb25maWdzL2hhbWRhdGEuaW5pJywnY3N0cmlrZS9hZGRvbnMvYW14bW9keC9kYXRhL2dhbWVkYXRhJywKICAgICkKICAgIGZvciByZWwgaW4gcmVsczoKICAgICAgICBzcmM9cGF0aC9yZWwKICAgICAgICBpZiBub3Qgc3JjLmV4aXN0cygpOiBjb250aW51ZQogICAgICAgIGRzdD1iYWNrdXAvcmVsOyBkc3QucGFyZW50Lm1rZGlyKHBhcmVudHM9VHJ1ZSxleGlzdF9vaz1UcnVlKQogICAgICAgIGlmIHNyYy5pc19kaXIoKTogc2h1dGlsLmNvcHl0cmVlKHNyYyxkc3QsZGlyc19leGlzdF9vaz1UcnVlKQogICAgICAgIGVsc2U6IHNodXRpbC5jb3B5MihzcmMsZHN0KQoKCmRlZiBfdjMyM19ydW50aW1lX3Jlc3RvcmUocGF0aDpQYXRoLGJhY2t1cDpQYXRoKToKICAgIHJlbHM9KAogICAgICAgICdobGRzX2xpbnV4JywnZW5naW5lX2k0ODYuc28nLCdjb3JlLnNvJywnZmlsZXN5c3RlbV9zdGRpby5zbycsJ2RlbW9wbGF5ZXIuc28nLAogICAgICAgICdjc3RyaWtlL2RsbHMvY3Muc28nLCdjc3RyaWtlL2xpYmxpc3QuZ2FtJywnY3N0cmlrZS9hZGRvbnMvbWV0YW1vZCcsCiAgICAgICAgJ2NzdHJpa2UvYWRkb25zL3JldW5pb24nLCdjc3RyaWtlL2FkZG9ucy9kcHJvdG8nLAogICAgICAgICdjc3RyaWtlL2FkZG9ucy9hbXhtb2R4L2RsbHMnLCdjc3RyaWtlL2FkZG9ucy9hbXhtb2R4L21vZHVsZXMnLAogICAgICAgICdjc3RyaWtlL2FkZG9ucy9hbXhtb2R4L2NvbmZpZ3MvaGFtZGF0YS5pbmknLCdjc3RyaWtlL2FkZG9ucy9hbXhtb2R4L2RhdGEvZ2FtZWRhdGEnLAogICAgKQogICAgZm9yIHJlbCBpbiByZWxzOgogICAgICAgIGN1cj1wYXRoL3JlbAogICAgICAgIGlmIGN1ci5pc19kaXIoKTogc2h1dGlsLnJtdHJlZShjdXIsaWdub3JlX2Vycm9ycz1UcnVlKQogICAgICAgIGVsaWYgY3VyLmV4aXN0cygpOgogICAgICAgICAgICB0cnk6IGN1ci51bmxpbmsoKQogICAgICAgICAgICBleGNlcHQgRXhjZXB0aW9uOiBwYXNzCiAgICAgICAgc3JjPWJhY2t1cC9yZWwKICAgICAgICBpZiBub3Qgc3JjLmV4aXN0cygpOiBjb250aW51ZQogICAgICAgIGN1ci5wYXJlbnQubWtkaXIocGFyZW50cz1UcnVlLGV4aXN0X29rPVRydWUpCiAgICAgICAgaWYgc3JjLmlzX2RpcigpOiBzaHV0aWwuY29weXRyZWUoc3JjLGN1cixkaXJzX2V4aXN0X29rPVRydWUpCiAgICAgICAgZWxzZTogc2h1dGlsLmNvcHkyKHNyYyxjdXIpCgoKZGVmIHJ1bnRpbWVfY29oZXJlbnRfYXBwbHkoc2lkOmludCk6CiAgICByZXF1aXJlX3Jvb3QoKTsgYz1sb2FkX3NlcnZlcihzaWQpOyBwYXRoPXNhZmVfc2VydmVyX3BhdGgoc2lkKQogICAgYmFja3VwPXBhdGgucGFyZW50L0JVSUxEX0JBQ0tVUF9ESVJfTkFNRS9mJ3tzaWR9LWNvaGVyZW50LXYzMjMte3RpbWUuc3RyZnRpbWUoIiVZJW0lZC0lSCVNJVMiKX0te3NlY3JldHMudG9rZW5faGV4KDQpfScKICAgIGJhY2t1cC5ta2RpcihwYXJlbnRzPVRydWUsZXhpc3Rfb2s9VHJ1ZSkKICAgIF92MzIzX3J1bnRpbWVfYmFja3VwKHBhdGgsYmFja3VwKQoKICAgIGN1cnJlbnRfc2NvcGU9ewogICAgICAgICdsYXlvdXQnOidpbnN0YWxsZWQtc2VydmVyJywKICAgICAgICAnaGFzX21hdGNoaW5nX2VuZ2luZSc6RmFsc2UsCiAgICAgICAgJ2NhcnJpZXNfY3N0cmlrZV9ydW50aW1lJzpUcnVlLAogICAgICAgICdwYXJ0aWFsX2xlZ2FjeV9ydW50aW1lJzpUcnVlLAogICAgICAgICdhcmNoaXZlZF9lbmdpbmVfYnVpbGRzJzpfdjMyM19kZXRlY3RfcHJldmlvdXNfYnVpbGQocGF0aC8nY3N0cmlrZScpLAogICAgICAgICdyZWFzb24nOidtYW51YWwvY3VycmVudC1zZXJ2ZXIgY29oZXJlbnQgcnVudGltZSByZXBhaXInLAogICAgfQoKICAgIHJ1bihbJ3N5c3RlbWN0bCcsJ3N0b3AnLGYnaHlwZXItY3MxNkB7c2lkfS5zZXJ2aWNlJ10sY2hlY2s9RmFsc2UsdGltZW91dD02MCkKICAgIHRyeToKICAgICAgICByZXN1bHQ9X3YzMjNfcHJlcGFyZV9jb2hlcmVudF9ydW50aW1lKHBhdGgsYyxjdXJyZW50X3Njb3BlKQogICAgICAgIGM9bG9hZF9zZXJ2ZXIoc2lkKQogICAgICAgIGNbJ3Byb2ZpbGUnXT0ncmVobGRzJwogICAgICAgIGNbJ3J1bnRpbWVfcG9saWN5J109eydlbmdpbmUnOidhdXRvJywnbWV0YW1vZCc6J2F1dG8nLCdhbXh4JzonYXV0byd9CiAgICAgICAgc2F2ZV9zZXJ2ZXIoYyk7IGRiX3VwZGF0ZV9wcm9maWxlKHNpZCwncmVobGRzJykKICAgICAgICBub3JtYWxpemVfcGVybWlzc2lvbnMocGF0aCkKICAgICAgICBydW4oWydzeXN0ZW1jdGwnLCdyZXNldC1mYWlsZWQnLGYnaHlwZXItY3MxNkB7c2lkfS5zZXJ2aWNlJ10sY2hlY2s9RmFsc2UpCiAgICAgICAgcnVuKFsnc3lzdGVtY3RsJywnc3RhcnQnLGYnaHlwZXItY3MxNkB7c2lkfS5zZXJ2aWNlJ10sY2hlY2s9RmFsc2UsdGltZW91dD02MCkKICAgICAgICBvayxkZXRhaWw9d2FpdF9zZXJ2ZXJfcmVhZHkobG9hZF9zZXJ2ZXIoc2lkKSw1MC4wKQogICAgICAgIGlmIG5vdCBvazoKICAgICAgICAgICAgcmFpc2UgUnVudGltZUVycm9yKCdjb2hlcmVudCBydW50aW1lIGRpZCBub3QgYmVjb21lIHJlYWR5OiAnK3N0cihkZXRhaWwpKQogICAgICAgIHRpbWUuc2xlZXAoMS41KQogICAgICAgIGludj1fdjMyMF9ydW50aW1lX2ludmVudG9yeShwYXRoKQogICAgICAgIHJldHVybiB7J29rJzpUcnVlLCdpZCc6c2lkLCdiYWNrdXAnOnN0cihiYWNrdXApLCdxdWVyeSc6ZGV0YWlsLCdjb2hlcmVuY2UnOnJlc3VsdCwncnVudGltZSc6aW52fQogICAgZXhjZXB0IEV4Y2VwdGlvbiBhcyBleGM6CiAgICAgICAgcnVuKFsnc3lzdGVtY3RsJywnc3RvcCcsZidoeXBlci1jczE2QHtzaWR9LnNlcnZpY2UnXSxjaGVjaz1GYWxzZSx0aW1lb3V0PTMwKQogICAgICAgIF92MzIzX3J1bnRpbWVfcmVzdG9yZShwYXRoLGJhY2t1cCkKICAgICAgICBub3JtYWxpemVfcGVybWlzc2lvbnMocGF0aCkKICAgICAgICBydW4oWydzeXN0ZW1jdGwnLCdyZXNldC1mYWlsZWQnLGYnaHlwZXItY3MxNkB7c2lkfS5zZXJ2aWNlJ10sY2hlY2s9RmFsc2UpCiAgICAgICAgcnVuKFsnc3lzdGVtY3RsJywnc3RhcnQnLGYnaHlwZXItY3MxNkB7c2lkfS5zZXJ2aWNlJ10sY2hlY2s9RmFsc2UsdGltZW91dD02MCkKICAgICAgICByYWlzZSBSdW50aW1lRXJyb3IoJ3YzLjIzIGNvaGVyZW50IHJ1bnRpbWUgcmVwYWlyIGZhaWxlZCBhbmQgcnVudGltZSBiYWNrdXAgd2FzIHJlc3RvcmVkOiAnK3N0cihleGMpKQojIDw8PCBIWVBFUi1IT1NUIHYzLjIzIENPSEVSRU5UIFJVTlRJTUUgR1VBUkQgPDw8CicnJwoKCmRlZiBwYXJzZShzcmM6c3RyKToKICAgIHJldHVybiBhc3QucGFyc2Uoc3JjKQoKCmRlZiBmdW5jdGlvbl9ub2RlKHRyZWU6YXN0LkFTVCxuYW1lOnN0cik6CiAgICBmb3Igbm9kZSBpbiBnZXRhdHRyKHRyZWUsJ2JvZHknLFtdKToKICAgICAgICBpZiBpc2luc3RhbmNlKG5vZGUsKGFzdC5GdW5jdGlvbkRlZixhc3QuQXN5bmNGdW5jdGlvbkRlZikpIGFuZCBub2RlLm5hbWU9PW5hbWU6CiAgICAgICAgICAgIHJldHVybiBub2RlCiAgICByZXR1cm4gTm9uZQoKCmRlZiBmdW5jX3NvdXJjZShzcmM6c3RyLG5vZGUpLT5zdHI6CiAgICBsaW5lcz1zcmMuc3BsaXRsaW5lcyhrZWVwZW5kcz1UcnVlKQogICAgcmV0dXJuICcnLmpvaW4obGluZXNbbm9kZS5saW5lbm8tMTpub2RlLmVuZF9saW5lbm9dKQoKCmRlZiByZXBsYWNlX2Z1bmN0aW9uKHNyYzpzdHIsbm9kZSxuZXdfZm46c3RyKS0+c3RyOgogICAgbGluZXM9c3JjLnNwbGl0bGluZXMoa2VlcGVuZHM9VHJ1ZSkKICAgIGlmIG5ld19mbiBhbmQgbm90IG5ld19mbi5lbmRzd2l0aCgnXG4nKTogbmV3X2ZuKz0nXG4nCiAgICBsaW5lc1tub2RlLmxpbmVuby0xOm5vZGUuZW5kX2xpbmVub109W25ld19mbl0KICAgIHJldHVybiAnJy5qb2luKGxpbmVzKQoKCmRlZiBwYXRjaF9jdGwocGF0aDpQYXRoKToKICAgIHNyYz1wYXRoLnJlYWRfdGV4dChlbmNvZGluZz0ndXRmLTgnLGVycm9ycz0nc3Vycm9nYXRlZXNjYXBlJykKICAgIGlmICdkZWYgX3YzMjBfcHJlcGFyZV9ydW50aW1lKCcgbm90IGluIHNyYzoKICAgICAgICByYWlzZSBSdW50aW1lRXJyb3IoJ3YzLjIzIHJlcXVpcmVzIGluc3RhbGxlZCB2My4yMCBhZGFwdGl2ZSBydW50aW1lJykKICAgIGlmICdkZWYgX3YzMjJfc2tpcF9taXNzaW5nX29wdGlvbmFsX3JlZnMoJyBub3QgaW4gc3JjOgogICAgICAgIHJhaXNlIFJ1bnRpbWVFcnJvcigndjMuMjMgcmVxdWlyZXMgaW5zdGFsbGVkIHYzLjIyIG9wdGlvbmFsLWZpbGUgc2FuaXRpemVyJykKCiAgICBpZiBNQVJLRVIgbm90IGluIHNyYzoKICAgICAgICBwb3M9c3JjLmZpbmQoJ1xuZGVmIGluc3RhbGxfY3VzdG9tX2J1aWxkKCcpCiAgICAgICAgaWYgcG9zPDA6IHJhaXNlIFJ1bnRpbWVFcnJvcignaW5zdGFsbF9jdXN0b21fYnVpbGQgbm90IGZvdW5kJykKICAgICAgICBzcmM9c3JjWzpwb3NdKydcbicrSEVMUEVSK3NyY1twb3M6XQoKICAgIHRyZWU9cGFyc2Uoc3JjKTsgZm49ZnVuY3Rpb25fbm9kZSh0cmVlLCdpbnN0YWxsX2N1c3RvbV9idWlsZCcpCiAgICBpZiBmbiBpcyBOb25lOiByYWlzZSBSdW50aW1lRXJyb3IoJ2luc3RhbGxfY3VzdG9tX2J1aWxkIG1pc3NpbmcgYWZ0ZXIgaGVscGVyIGluc2VydGlvbicpCiAgICBmc3JjPWZ1bmNfc291cmNlKHNyYyxmbikKCiAgICBpZiAncnVudGltZV9zY29wZT1fdjMyM19hbmFseXplX2FyY2hpdmVfcnVudGltZShwYXlsb2FkLGxheW91dCknIG5vdCBpbiBmc3JjOgogICAgICAgIGFuY2hvcj0nICAgICAgICBwYXlsb2FkLGxheW91dD1fZGV0ZWN0X2J1aWxkX3BheWxvYWQoZXh0cmFjdF9yb290KVxuJwogICAgICAgIGlmIGFuY2hvciBub3QgaW4gZnNyYzogcmFpc2UgUnVudGltZUVycm9yKCdwYXlsb2FkL2xheW91dCBzdHJ1Y3R1cmFsIHBvaW50IG1pc3NpbmcnKQogICAgICAgIGZzcmM9ZnNyYy5yZXBsYWNlKGFuY2hvcixhbmNob3IrJyAgICAgICAgcnVudGltZV9zY29wZT1fdjMyM19hbmFseXplX2FyY2hpdmVfcnVudGltZShwYXlsb2FkLGxheW91dClcbicsMSkKCiAgICBpZiAncnVudGltZV9jb2hlcmVuY2U9X3YzMjNfcHJlcGFyZV9jb2hlcmVudF9ydW50aW1lKHN0YWdlLGMscnVudGltZV9zY29wZSknIG5vdCBpbiBmc3JjOgogICAgICAgIGFuY2hvcj0nICAgICAgICBwbGF0Zm9ybV9ydW50aW1lPV92MzIwX3ByZXBhcmVfcnVudGltZShzdGFnZSxjKVxuJwogICAgICAgIGlmIGFuY2hvciBub3QgaW4gZnNyYzogcmFpc2UgUnVudGltZUVycm9yKCd2My4yMCBwbGF0Zm9ybSBydW50aW1lIHBvaW50IG1pc3NpbmcnKQogICAgICAgIGJsb2NrPSgKICAgICAgICAgICAgJyAgICAgICAgcnVudGltZV9jb2hlcmVuY2U9X3YzMjNfcHJlcGFyZV9jb2hlcmVudF9ydW50aW1lKHN0YWdlLGMscnVudGltZV9zY29wZSlcbicKICAgICAgICAgICAgIiAgICAgICAgaWYgcnVudGltZV9jb2hlcmVuY2UuZ2V0KCdmb3JjZWQnKTpcbiIKICAgICAgICAgICAgIiAgICAgICAgICAgIGNbJ3Byb2ZpbGUnXT0ncmVobGRzJ1xuIgogICAgICAgICAgICAiICAgICAgICAgICAgZGJfdXBkYXRlX3Byb2ZpbGUoc2lkLCdyZWhsZHMnKVxuIgogICAgICAgICkKICAgICAgICBmc3JjPWZzcmMucmVwbGFjZShhbmNob3IsYmxvY2srYW5jaG9yLDEpCgogICAgaWYgJytjb2hlcmVudC1ydW50aW1lLXYzMjMnIG5vdCBpbiBmc3JjOgogICAgICAgICMgQXBwZW5kIG9ubHkgd2hlbiBhIHBhcnRpYWwgbGVnYWN5IHJ1bnRpbWUgd2FzIGFjdHVhbGx5IG5vcm1hbGl6ZWQuCiAgICAgICAgYW5jaG9yPSIgICAgICAgIGltcG9ydF9tb2RlPWltcG9ydF9tb2RlKycrc2tpcC1taXNzaW5nLXYzMjInXG4iCiAgICAgICAgaWYgYW5jaG9yIG5vdCBpbiBmc3JjOgogICAgICAgICAgICByYWlzZSBSdW50aW1lRXJyb3IoJ3YzLjIyIGltcG9ydCBzdWZmaXggcG9pbnQgbWlzc2luZycpCiAgICAgICAgZnNyYz1mc3JjLnJlcGxhY2UoCiAgICAgICAgICAgIGFuY2hvciwKICAgICAgICAgICAgYW5jaG9yKyIgICAgICAgIGlmIHJ1bnRpbWVfY29oZXJlbmNlLmdldCgnZm9yY2VkJyk6IGltcG9ydF9tb2RlPWltcG9ydF9tb2RlKycrY29oZXJlbnQtcnVudGltZS12MzIzJ1xuIiwKICAgICAgICAgICAgMSwKICAgICAgICApCgogICAgIyBFeHBvc2UgcmVzdWx0IHRvIHBhbmVsL0FQSS4KICAgIGlmICIncnVudGltZV9jb2hlcmVuY2UnOnJ1bnRpbWVfY29oZXJlbmNlIiBub3QgaW4gZnNyYzoKICAgICAgICBvbGQ9IidydW50aW1lX2ZpbGwnOnJ1bnRpbWVfZmlsbCwncmVhcGlfY29tcGF0JzpyZWFwaV9jb21wYXQsJ2FyY2hpdmVfbWFuaWZlc3QnOm1hbmlmZXN0LCIKICAgICAgICBuZXc9IidydW50aW1lX2ZpbGwnOnJ1bnRpbWVfZmlsbCwncnVudGltZV9jb2hlcmVuY2UnOnJ1bnRpbWVfY29oZXJlbmNlLCdyZWFwaV9jb21wYXQnOnJlYXBpX2NvbXBhdCwnYXJjaGl2ZV9tYW5pZmVzdCc6bWFuaWZlc3QsIgogICAgICAgIGlmIG9sZCBpbiBmc3JjOgogICAgICAgICAgICBmc3JjPWZzcmMucmVwbGFjZShvbGQsbmV3LDEpCiAgICAgICAgZWxzZToKICAgICAgICAgICAgIyBDdXJyZW50IHYzLjIyIGZ1bmN0aW9uIGhhcyBydW50aW1lX2ZpbGwgZm9sbG93ZWQgYnkgcmVhcGlfY29tcGF0IGluIHRoZSByZXN1bHQgZGljdC4KICAgICAgICAgICAgZnNyYz1mc3JjLnJlcGxhY2UoIidydW50aW1lX2ZpbGwnOnJ1bnRpbWVfZmlsbCwncmVhcGlfY29tcGF0JzpyZWFwaV9jb21wYXQiLCAiJ3J1bnRpbWVfZmlsbCc6cnVudGltZV9maWxsLCdydW50aW1lX2NvaGVyZW5jZSc6cnVudGltZV9jb2hlcmVuY2UsJ3JlYXBpX2NvbXBhdCc6cmVhcGlfY29tcGF0IiwxKQoKICAgICMgQWRkIGEgY29uY2lzZSB3YXJuaW5nL25vdGUgb25seSBmb3IgZm9yY2VkIGNvaGVyZW5jZS4KICAgIGlmICJydW50aW1lX2NvaGVyZW5jZS5nZXQoJ2ZvcmNlZCcpIiBpbiBmc3JjIGFuZCAnUGFydGlhbCBsZWdhY3kgcnVudGltZSB3YXMgcmVwbGFjZWQnIG5vdCBpbiBmc3JjOgogICAgICAgIGFuY2hvcj0iICAgICAgICB3YXJuaW5ncz1bXVxuIgogICAgICAgIGlmIGFuY2hvciBpbiBmc3JjOgogICAgICAgICAgICBub3RlPSgKICAgICAgICAgICAgICAgICIgICAgICAgIGlmIHJ1bnRpbWVfY29oZXJlbmNlLmdldCgnZm9yY2VkJyk6XG4iCiAgICAgICAgICAgICAgICAiICAgICAgICAgICAgYnVpbGRzPWxpc3QoKHJ1bnRpbWVfY29oZXJlbmNlLmdldCgnYXJjaGl2ZV9zY29wZScpIG9yIHt9KS5nZXQoJ2FyY2hpdmVkX2VuZ2luZV9idWlsZHMnKSBvciBbXSlcbiIKICAgICAgICAgICAgICAgICIgICAgICAgICAgICB3YXJuaW5ncy5hcHBlbmQoJ1BhcnRpYWwgbGVnYWN5IHJ1bnRpbWUgd2FzIHJlcGxhY2VkIHdpdGggb25lIGNvaGVyZW50IEhZUEVSLUhPU1Qgc3RhY2snICsgKCgnIChhcmNoaXZlZCBidWlsZCAnKycsICcuam9pbihidWlsZHMpKycpJykgaWYgYnVpbGRzIGVsc2UgJycpICsgJy4gTGVnYWN5IFJldW5pb24vZHByb3RvIGxvYWRlciBkaXNhYmxlZC4nKVxuIgogICAgICAgICAgICApCiAgICAgICAgICAgIGZzcmM9ZnNyYy5yZXBsYWNlKGFuY2hvcixhbmNob3Irbm90ZSwxKQoKICAgIHNyYz1yZXBsYWNlX2Z1bmN0aW9uKHNyYyxmbixmc3JjKQoKICAgICMgQWRkIENMSSBjb21tYW5kIHRvIHRoZSBnZW5lcmljIGlkIGNvbW1hbmQgbGlzdC4KICAgIGlmICIncnVudGltZS1jb2hlcmVudC1hcHBseSciIG5vdCBpbiBzcmM6CiAgICAgICAgc3JjPXNyYy5yZXBsYWNlKCIncnVudGltZS1zdGF0dXMnLCdydW50aW1lLWFwcGx5JywncnVudGltZS1yZXBhaXItY2hhaW4nIiwgIidydW50aW1lLXN0YXR1cycsJ3J1bnRpbWUtYXBwbHknLCdydW50aW1lLWNvaGVyZW50LWFwcGx5JywncnVudGltZS1yZXBhaXItY2hhaW4nIiwxKQoKICAgIGlmICJlbGlmIGFyZ3MuY21kPT0ncnVudGltZS1jb2hlcmVudC1hcHBseSciIG5vdCBpbiBzcmM6CiAgICAgICAgYW5jaG9yPSIgICAgICAgIGVsaWYgYXJncy5jbWQ9PSdydW50aW1lLWFwcGx5JzogcmVzdWx0PXJ1bnRpbWVfYXBwbHkoYXJncy5pZClcbiIKICAgICAgICBpZiBhbmNob3Igbm90IGluIHNyYzogcmFpc2UgUnVudGltZUVycm9yKCdydW50aW1lIENMSSBicmFuY2ggYW5jaG9yIG1pc3NpbmcnKQogICAgICAgIHNyYz1zcmMucmVwbGFjZShhbmNob3IsYW5jaG9yKyIgICAgICAgIGVsaWYgYXJncy5jbWQ9PSdydW50aW1lLWNvaGVyZW50LWFwcGx5JzogcmVzdWx0PXJ1bnRpbWVfY29oZXJlbnRfYXBwbHkoYXJncy5pZClcbiIsMSkKCiAgICB0bXA9cGF0aC53aXRoX25hbWUocGF0aC5uYW1lKycudjMyM3RtcCcpCiAgICB0bXAud3JpdGVfdGV4dChzcmMsZW5jb2Rpbmc9J3V0Zi04JyxlcnJvcnM9J3N1cnJvZ2F0ZWVzY2FwZScpCiAgICBvcy5jaG1vZCh0bXAscGF0aC5zdGF0KCkuc3RfbW9kZSkKICAgIHB5X2NvbXBpbGUuY29tcGlsZShzdHIodG1wKSxkb3JhaXNlPVRydWUpCiAgICBmaW5hbD10bXAucmVhZF90ZXh0KGVuY29kaW5nPSd1dGYtOCcsZXJyb3JzPSdzdXJyb2dhdGVlc2NhcGUnKQogICAgY2hlY2tzPVsKICAgICAgICBNQVJLRVIsCiAgICAgICAgJ3J1bnRpbWVfc2NvcGU9X3YzMjNfYW5hbHl6ZV9hcmNoaXZlX3J1bnRpbWUocGF5bG9hZCxsYXlvdXQpJywKICAgICAgICAncnVudGltZV9jb2hlcmVuY2U9X3YzMjNfcHJlcGFyZV9jb2hlcmVudF9ydW50aW1lKHN0YWdlLGMscnVudGltZV9zY29wZSknLAogICAgICAgICcrY29oZXJlbnQtcnVudGltZS12MzIzJywKICAgICAgICAnZGVmIHJ1bnRpbWVfY29oZXJlbnRfYXBwbHkoc2lkOmludCk6JywKICAgICAgICAiZWxpZiBhcmdzLmNtZD09J3J1bnRpbWUtY29oZXJlbnQtYXBwbHknIiwKICAgIF0KICAgIG1pc3Npbmc9W3ggZm9yIHggaW4gY2hlY2tzIGlmIHggbm90IGluIGZpbmFsXQogICAgaWYgbWlzc2luZzoKICAgICAgICB0bXAudW5saW5rKG1pc3Npbmdfb2s9VHJ1ZSkKICAgICAgICByYWlzZSBSdW50aW1lRXJyb3IoJ3YzLjIzIHZlcmlmaWNhdGlvbiBmYWlsZWQ6ICcrcmVwcihtaXNzaW5nKSkKICAgIG9zLnJlcGxhY2UodG1wLHBhdGgpCiAgICBwcmludCgnW1BBVENIRURdJyxwYXRoKQoKCmRlZiBwYXRjaF9pbmRleChwYXRoOlBhdGgpOgogICAgc3JjPXBhdGgucmVhZF90ZXh0KGVuY29kaW5nPSd1dGYtOCcsZXJyb3JzPSdzdXJyb2dhdGVlc2NhcGUnKQogICAgc3JjPXNyYy5yZXBsYWNlKCfRg9GB0YLQsNC90L7QstC70LXQvdCwINC40Lcg0LDRgNGF0LjQstCwINCx0LXQtyDQstGL0YDQtdC30LDQvdC40Y8gcnVudGltZS4nLCfRg9GB0YLQsNC90L7QstC70LXQvdCwINC40Lcg0LDRgNGF0LjQstCwLicpCiAgICBzcmM9c3JjLnJlcGxhY2UoJ9Ch0LHQvtGA0LrQsCDRgdC60LDRh9Cw0L3QsCDQuCDRg9GB0YLQsNC90L7QstC70LXQvdCwINCx0LXQtyDQstGL0YDQtdC30LDQvdC40Y8gcnVudGltZS4nLCfQodCx0L7RgNC60LAg0YHQutCw0YfQsNC90LAg0Lgg0YPRgdGC0LDQvdC+0LLQu9C10L3QsC4nKQogICAgIyBUaGUgYnVpbGQgc3VjY2VzcyBoYW5kbGVycyBhcmUgaW50ZW50aW9uYWxseSBvbmUtbGluZSBQSFA7IGluamVjdCBhIHNtYWxsCiAgICAjIGNvaGVyZW5jZSBkZXNjcmlwdG9yIHdpdGhvdXQgZGVwZW5kaW5nIG9uIGV4YWN0IFJ1c3NpYW4gd29yZGluZyBhcm91bmQgaXQuCiAgICBpZiAiJGNvaD1pc19hcnJheSgkclsncnVudGltZV9jb2hlcmVuY2UnXSIgbm90IGluIHNyYzoKICAgICAgICBtYXJrZXI9IiR3YXJuPXRyaW0oKHN0cmluZykoJHJbJ3dhcm5pbmcnXT8/JycpKTsiCiAgICAgICAgaW5qZWN0PSIkY29oPWlzX2FycmF5KCRyWydydW50aW1lX2NvaGVyZW5jZSddPz9udWxsKT8kclsncnVudGltZV9jb2hlcmVuY2UnXTpbXTskY29oRm9yY2VkPSFlbXB0eSgkY29oWydmb3JjZWQnXSk7JGNvaFNjb3BlPWlzX2FycmF5KCRjb2hbJ2FyY2hpdmVfc2NvcGUnXT8/bnVsbCk/JGNvaFsnYXJjaGl2ZV9zY29wZSddOltdOyRjb2hCdWlsZHM9aXNfYXJyYXkoJGNvaFNjb3BlWydhcmNoaXZlZF9lbmdpbmVfYnVpbGRzJ10/P251bGwpPyRjb2hTY29wZVsnYXJjaGl2ZWRfZW5naW5lX2J1aWxkcyddOltdOyIKICAgICAgICBzcmM9c3JjLnJlcGxhY2UobWFya2VyLG1hcmtlcitpbmplY3QpCgogICAgaWYgJ9Ch0YLQsNGA0YvQuSDQvdC10L/QvtC70L3Ri9C5IHJ1bnRpbWUg0YHQsdC+0YDQutC4INCw0LLRgtC+0LzQsNGC0LjRh9C10YHQutC4INC30LDQvNC10L3RkdC9JyBub3QgaW4gc3JjOgogICAgICAgIG5lZWRsZT0iaWYoISRoZWFsdGh5KSRtc2cuPScg0KHQsdC+0YDQutCwINC+0YHRgtCw0LLQu9C10L3QsCDRg9GB0YLQsNC90L7QstC70LXQvdC90L7QuSwg0L3QviBydW50aW1lINGC0YDQtdCx0YPQtdGCINCy0L3QuNC80LDQvdC40Y8nIgogICAgICAgIGluamVjdD0iaWYoaXNzZXQoJGNvaEZvcmNlZCkmJiRjb2hGb3JjZWQpJG1zZy49JyDQodGC0LDRgNGL0Lkg0L3QtdC/0L7Qu9C90YvQuSBydW50aW1lINGB0LHQvtGA0LrQuCDQsNCy0YLQvtC80LDRgtC40YfQtdGB0LrQuCDQt9Cw0LzQtdC90ZHQvSDQtdC00LjQvdGL0Lwg0YHQvtCy0LzQtdGB0YLQuNC80YvQvCBIWVBFUi1IT1NUIHJ1bnRpbWUnLigoaXNzZXQoJGNvaEJ1aWxkcykmJiRjb2hCdWlsZHMpPycgKNCyINGB0YLQsNGA0YvRhSDQu9C+0LPQsNGFIGJ1aWxkICcuaW1wbG9kZSgnLCAnLCRjb2hCdWlsZHMpLicpJzonJykuJy4g0KHRgtCw0YDRi9C5IFJldW5pb24vZHByb3RvINC+0YLQutC70Y7Rh9GR0L0uJzsiCiAgICAgICAgaWYgbmVlZGxlIGluIHNyYzoKICAgICAgICAgICAgc3JjPXNyYy5yZXBsYWNlKG5lZWRsZSxpbmplY3QrbmVlZGxlKQoKICAgIHRtcD1wYXRoLndpdGhfbmFtZShwYXRoLm5hbWUrJy52MzIzdG1wJykKICAgIHRtcC53cml0ZV90ZXh0KHNyYyxlbmNvZGluZz0ndXRmLTgnLGVycm9ycz0nc3Vycm9nYXRlZXNjYXBlJykKICAgIG9zLmNobW9kKHRtcCxwYXRoLnN0YXQoKS5zdF9tb2RlKQogICAgb3MucmVwbGFjZSh0bXAscGF0aCkKICAgIHByaW50KCdbUEFUQ0hFRF0nLHBhdGgpCgoKZGVmIG1haW4oKToKICAgIGlmIGxlbihzeXMuYXJndikhPTM6CiAgICAgICAgcmFpc2UgU3lzdGVtRXhpdCgndXNhZ2U6IHBhdGNoX3YzMjMucHkgY3RsfGluZGV4IFBBVEgnKQogICAgbW9kZT1zeXMuYXJndlsxXTsgcGF0aD1QYXRoKHN5cy5hcmd2WzJdKQogICAgaWYgbW9kZT09J2N0bCc6IHBhdGNoX2N0bChwYXRoKQogICAgZWxpZiBtb2RlPT0naW5kZXgnOiBwYXRjaF9pbmRleChwYXRoKQogICAgZWxzZTogcmFpc2UgU3lzdGVtRXhpdCgndW5rbm93biBtb2RlJykKCmlmIF9fbmFtZV9fPT0nX19tYWluX18nOgogICAgbWFpbigpCg==' | base64 -d >"$PATCHER"
python3 -m py_compile "$PATCHER" || die "Embedded v3.23 patcher is invalid"

echo "[1/8] Backing up controller and panel..."
backup_file "$LIVE_CTL"
backup_file "$REPO_CTL"

echo
echo "[2/8] Patching LIVE controller..."
python3 "$PATCHER" ctl "$LIVE_CTL" || die "Live controller patch failed"
python3 -m py_compile "$LIVE_CTL" || die "Live controller syntax validation failed"
echo "[OK] live controller patched"

echo
echo "[3/8] Synchronizing verified controller into current repo checkout..."
install -m 0755 "$LIVE_CTL" "$REPO_CTL"
python3 -m py_compile "$REPO_CTL" || die "Repository controller validation failed"

echo
echo "[4/8] Patching active panel message..."
for root in   "/var/www/hyper-host-sites/$DOMAIN/public_html"   "/var/www/$DOMAIN/public_html"   "/var/www/$DOMAIN"
do
  [[ -f "$root/index.php" ]] && echo "$root" >>"$ROOTS"
done

if command -v nginx >/dev/null 2>&1; then
  nginx -T >"$NGTMP" 2>&1 || true
  python3 - "$NGTMP" "$DOMAIN" >>"$ROOTS" <<'PYROOTS'
import re,sys
text=open(sys.argv[1],encoding='utf-8',errors='ignore').read()
domain=sys.argv[2]
for block in re.findall(r'server\s*\{.*?\n\}',text,re.S):
    if domain not in block: continue
    for root in re.findall(r'(?m)^\s*root\s+([^;]+);',block):
        root=root.strip()
        if root.startswith('/'): print(root)
PYROOTS
fi

while IFS= read -r idx; do
  grep -q "serverTabs" "$idx" 2>/dev/null || continue
  echo "$(dirname "$idx")" >>"$ROOTS"
done < <(find /var/www -xdev -type f -name index.php 2>/dev/null || true)

sort -u "$ROOTS" -o "$ROOTS"
PANEL_COUNT=0
FIRST_ROOT=""
while IFS= read -r DOCROOT; do
  [[ -n "$DOCROOT" ]] || continue
  [[ -f "$DOCROOT/index.php" ]] || continue
  grep -q "serverTabs" "$DOCROOT/index.php" || continue
  PANEL_COUNT=$((PANEL_COUNT+1))
  [[ -n "$FIRST_ROOT" ]] || FIRST_ROOT="$DOCROOT"
  backup_file "$DOCROOT/index.php"
  python3 "$PATCHER" index "$DOCROOT/index.php" || die "Panel patch failed: $DOCROOT"
  php -l "$DOCROOT/index.php" >/dev/null || die "PHP syntax error: $DOCROOT/index.php"
  echo "[PATCHED PANEL] $DOCROOT"
done <"$ROOTS"

if [[ "$PANEL_COUNT" -gt 0 && -n "$FIRST_ROOT" ]]; then
  install -m 0644 "$FIRST_ROOT/index.php" "$REPO/cs16-panel/public/index.php"
  php -l "$REPO/cs16-panel/public/index.php" >/dev/null || die "Repo panel validation failed"
else
  echo "[WARN] Active CS16 panel root not found; backend is patched, panel wording unchanged."
fi

while IFS= read -r svc; do
  [[ -n "$svc" ]] || continue
  systemctl reload "$svc" 2>/dev/null || systemctl restart "$svc" 2>/dev/null || true
done < <(systemctl list-units --type=service --state=running --no-legend 2>/dev/null | awk '/php.*fpm/ {print $1}')

echo
echo "[5/8] Verifying future-import guard..."
python3 - "$LIVE_CTL" <<'PYVERIFY'
from pathlib import Path
import ast,sys
s=Path(sys.argv[1]).read_text(encoding='utf-8',errors='surrogateescape')
ast.parse(s)
checks={
 'v3.23 helper':'def _v323_analyze_archive_runtime' in s,
 'archive runtime scope':'runtime_scope=_v323_analyze_archive_runtime(payload,layout)' in s,
 'coherent prepare':'runtime_coherence=_v323_prepare_coherent_runtime(stage,c,runtime_scope)' in s,
 'import marker':'+coherent-runtime-v323' in s,
 'current repair command':'def runtime_coherent_apply(sid:int):' in s,
}
bad=[]
for name,ok in checks.items():
    print(('[OK] ' if ok else '[FAIL] ')+name)
    if not ok: bad.append(name)
if bad: raise SystemExit('[ERROR] verification failed: '+', '.join(bad))
PYVERIFY

echo
echo "[6/8] Applying coherent runtime to CURRENT server #$SID..."
set +e
CURRENT_OUT="$($LIVE_CTL runtime-coherent-apply "$SID" 2>&1)"
CURRENT_RC=$?
set -e
echo "$CURRENT_OUT"
if [[ "$CURRENT_RC" -ne 0 ]]; then
  echo "[WARN] v3.23 architecture IS installed, but current-server coherent repair returned non-zero."
  echo "[WARN] The runtime helper restores its runtime backup on failure."
else
  echo "[OK] current server coherent runtime applied"
fi

echo
echo "[7/8] Runtime status after repair..."
$LIVE_CTL runtime-status "$SID" 2>&1 || true
echo "--- version ---"
$LIVE_CTL rcon "$SID" "version" 2>&1 || true
echo "--- meta list ---"
$LIVE_CTL rcon "$SID" "meta list" 2>&1 || true
echo "--- amxx plugins ---"
$LIVE_CTL rcon "$SID" "amxx plugins" 2>&1 || true

echo
echo "[8/8] Controller idempotence check..."
python3 "$PATCHER" ctl "$LIVE_CTL" || die "Repeated v3.23 controller patch failed"
python3 -m py_compile "$LIVE_CTL" || die "Controller invalid after repeated patch"
install -m 0755 "$LIVE_CTL" "$REPO_CTL"
echo "[OK] repeated patch pass is valid"

echo
echo "============================================================"
echo " v3.23 INSTALLED SUCCESSFULLY"
echo "============================================================"
echo "Future import rule:"
echo " - FULL server-root + own hlds_linux -> archive runtime may be preserved"
echo " - cstrike runtime WITHOUT matching hlds_linux -> NEVER mixed with host engine"
echo " - partial runtime -> ReHLDS/ReGameDLL + Metamod-R + managed AMXX runtime"
echo " - gameplay plugins/configs/models/maps/sounds stay from the assembly"
echo " - legacy Reunion/dproto loader from partial runtime is disabled"
echo " - import gets +coherent-runtime-v323"
echo
echo "Backup: $BACKUP"
echo "Log:    $LOG"
echo "============================================================"
