#!/usr/bin/env bash
set -Eeuo pipefail
ROOT="${1:-/root/hyper-hosting-panel}"
SID="${2:-25}"
PUBLIC_IP="90.189.208.25"
SRC_CTL="$ROOT/cs16-panel/bin/hyper-cs16-ctl"
LIVE_CTL="/usr/local/sbin/hyper-cs16-ctl"
CSTRIKE="/srv/hyper-cs16/servers/$SID/cstrike"
FASTDL="/srv/hyper-cs16/fastdl/$SID"
STAMP="$(date +%Y%m%d-%H%M%S)"
BACKUP="/root/hyper-cs16-fastdl-final-v6-${STAMP}"
CANON="/etc/nginx/sites-available/00-hyper-cs16-fastdl-ip.conf"
LINK="/etc/nginx/sites-enabled/00-hyper-cs16-fastdl-ip.conf"

[[ ${EUID:-$(id -u)} -eq 0 ]] || { echo "[ERROR] run as root"; exit 1; }
[[ -f "$SRC_CTL" ]] || { echo "[ERROR] missing $SRC_CTL"; exit 2; }
[[ -d "$CSTRIKE" ]] || { echo "[ERROR] missing $CSTRIKE"; exit 2; }

mkdir -p "$BACKUP"
cp -a "$SRC_CTL" "$BACKUP/hyper-cs16-ctl.repo"
[[ -f "$LIVE_CTL" ]] && cp -a "$LIVE_CTL" "$BACKUP/hyper-cs16-ctl.live"
[[ -f "$CSTRIKE/server.cfg" ]] && cp -a "$CSTRIKE/server.cfg" "$BACKUP/server.cfg"
nginx -T >"$BACKUP/nginx-T-before.txt" 2>&1 || true

echo "=============================================================="
echo " HYPER-HOST FASTDL FINAL v6"
echo " Server: #$SID"
echo " URL:    http://$PUBLIC_IP/fastdl/$SID/"
echo "=============================================================="

echo "[1/9] Disable old FastDL 8080 nginx experiments..."
for d in /etc/nginx/conf.d /etc/nginx/sites-enabled; do
  [[ -d "$d" ]] || continue
  while IFS= read -r -d '' f; do
    [[ "$(readlink -f "$f")" == "$(readlink -f "$CANON" 2>/dev/null || true)" ]] && continue
    if grep -qi 'fastdl' "$f" 2>/dev/null && grep -Eq 'listen[[:space:]]+.*8080' "$f" 2>/dev/null; then
      echo "disable: $f"
      cp -aL "$f" "$BACKUP/$(basename "$f").8080.conf" 2>/dev/null || true
      rm -f "$f"
    fi
  done < <(find "$d" -maxdepth 1 \( -type f -o -type l \) -print0 2>/dev/null)
done

echo "[2/9] Install exact-IP FastDL vhost on HTTP/80..."
mkdir -p /etc/nginx/sites-available /etc/nginx/sites-enabled
cat >"$CANON" <<'EOF'
server {
    listen 80;
    listen [::]:80;
    server_name 90.189.208.25;

    access_log /var/log/nginx/hyper-cs16-fastdl-access.log;
    error_log  /var/log/nginx/hyper-cs16-fastdl-error.log warn;

    location ^~ /fastdl/ {
        alias /srv/hyper-cs16/fastdl/;
        autoindex off;
        default_type application/octet-stream;
        add_header Cache-Control "public, max-age=86400" always;
        add_header X-Hyper-FastDL "raw" always;
    }

    location / {
        return 404;
    }
}
EOF
ln -sfn "$CANON" "$LINK"
nginx -t
systemctl reload nginx

echo "[3/9] Patch all core FastDL functions..."
P="$(mktemp)"
echo 'CmZyb20gcGF0aGxpYiBpbXBvcnQgUGF0aAppbXBvcnQgcmUsIHN5cwoKY3RsPVBhdGgoc3lzLmFyZ3ZbMV0pCnM9Y3RsLnJlYWRfdGV4dChlbmNvZGluZz0ndXRmLTgnKQoKZGVmIHJlcGxhY2VfZnVuYyh0ZXh0LG5hbWUsbmV4dF9uYW1lLGJvZHkpOgogICAgcGF0PXJlLmNvbXBpbGUocmYnKD9tcyleZGVmIHtyZS5lc2NhcGUobmFtZSl9XGIuKj8oPz1eZGVmIHtyZS5lc2NhcGUobmV4dF9uYW1lKX1cYiknKQogICAgbT1wYXQuc2VhcmNoKHRleHQpCiAgICBpZiBub3QgbToKICAgICAgICByYWlzZSBTeXN0ZW1FeGl0KGYnW1BBVENIIEVSUk9SXSBmdW5jdGlvbiByYW5nZSBub3QgZm91bmQ6IHtuYW1lfSAtPiB7bmV4dF9uYW1lfScpCiAgICByZXR1cm4gdGV4dFs6bS5zdGFydCgpXStib2R5LnJzdHJpcCgpKydcblxuJyt0ZXh0W20uZW5kKCk6XQoKaGVscGVyPXInJydkZWYgX2hoX2Zhc3RkbF9jYXNlX3JlcGFpcl92Nihjc3RyaWtlOlBhdGgpLT5kaWN0OgogICAgaW5kZXg9e30KICAgIGZvciB0b3AgaW4gRkFTVERMX0RJUlM6CiAgICAgICAgYmFzZT1jc3RyaWtlL3RvcAogICAgICAgIGlmIG5vdCBiYXNlLmlzX2RpcigpOgogICAgICAgICAgICBjb250aW51ZQogICAgICAgIGZvciBmcCBpbiBiYXNlLnJnbG9iKCcqJyk6CiAgICAgICAgICAgIHRyeToKICAgICAgICAgICAgICAgIGlmIGZwLmlzX2ZpbGUoKSBhbmQgbm90IGZwLmlzX3N5bWxpbmsoKToKICAgICAgICAgICAgICAgICAgICByZWw9ZnAucmVsYXRpdmVfdG8oY3N0cmlrZSkuYXNfcG9zaXgoKQogICAgICAgICAgICAgICAgICAgIGluZGV4LnNldGRlZmF1bHQocmVsLmxvd2VyKCksW10pLmFwcGVuZChmcCkKICAgICAgICAgICAgZXhjZXB0IE9TRXJyb3I6CiAgICAgICAgICAgICAgICBwYXNzCiAgICBmb3IgZnAgaW4gY3N0cmlrZS5nbG9iKCcqLndhZCcpOgogICAgICAgIGlmIGZwLmlzX2ZpbGUoKToKICAgICAgICAgICAgaW5kZXguc2V0ZGVmYXVsdChmcC5uYW1lLmxvd2VyKCksW10pLmFwcGVuZChmcCkKCiAgICByZXBhaXJlZD1bXQogICAgdW5yZXNvbHZlZD1bXQogICAgY3Jvb3Q9Y3N0cmlrZS5yZXNvbHZlKCkKICAgIG1hcHM9Y3N0cmlrZS8nbWFwcycKICAgIGlmIG1hcHMuaXNfZGlyKCk6CiAgICAgICAgZm9yIHJmIGluIG1hcHMuZ2xvYignKi5yZXMnKToKICAgICAgICAgICAgdHJ5OgogICAgICAgICAgICAgICAgdGV4dD1yZi5yZWFkX3RleHQoZW5jb2Rpbmc9J2xhdGluMScsZXJyb3JzPSdpZ25vcmUnKQogICAgICAgICAgICBleGNlcHQgRXhjZXB0aW9uOgogICAgICAgICAgICAgICAgY29udGludWUKICAgICAgICAgICAgZm9yIHJhdyBpbiB0ZXh0LnJlcGxhY2UoJ1xyJywnXG4nKS5zcGxpdGxpbmVzKCk6CiAgICAgICAgICAgICAgICByZWw9cmF3LnNwbGl0KCcvLycsMSlbMF0uc3RyaXAoKS5zdHJpcCgnIicpLnJlcGxhY2UoJ1xcJywnLycpCiAgICAgICAgICAgICAgICBpZiBub3QgcmVsIG9yICcuLicgaW4gUGF0aChyZWwpLnBhcnRzOgogICAgICAgICAgICAgICAgICAgIGNvbnRpbnVlCiAgICAgICAgICAgICAgICBpZiBub3QgKAogICAgICAgICAgICAgICAgICAgIHJlLm1hdGNoKHInXig/Om1hcHN8bW9kZWxzfHNvdW5kfHNwcml0ZXN8Z2Z4fHJlc291cmNlfG92ZXJ2aWV3c3xldmVudHN8bWVkaWEpLycscmVsLHJlLkkpCiAgICAgICAgICAgICAgICAgICAgb3IgcmUubWF0Y2gocideW14vXStcLndhZCQnLHJlbCxyZS5JKQogICAgICAgICAgICAgICAgKToKICAgICAgICAgICAgICAgICAgICBjb250aW51ZQogICAgICAgICAgICAgICAgdGFyZ2V0PShjc3RyaWtlL3JlbCkucmVzb2x2ZSgpCiAgICAgICAgICAgICAgICB0cnk6CiAgICAgICAgICAgICAgICAgICAgdGFyZ2V0LnJlbGF0aXZlX3RvKGNyb290KQogICAgICAgICAgICAgICAgZXhjZXB0IFZhbHVlRXJyb3I6CiAgICAgICAgICAgICAgICAgICAgY29udGludWUKICAgICAgICAgICAgICAgIGlmIHRhcmdldC5pc19maWxlKCk6CiAgICAgICAgICAgICAgICAgICAgY29udGludWUKICAgICAgICAgICAgICAgIGZvdW5kPWluZGV4LmdldChyZWwubG93ZXIoKSxbXSkKICAgICAgICAgICAgICAgIGlmIGxlbihmb3VuZCk9PTE6CiAgICAgICAgICAgICAgICAgICAgc3JjPWZvdW5kWzBdCiAgICAgICAgICAgICAgICAgICAgdGFyZ2V0LnBhcmVudC5ta2RpcihwYXJlbnRzPVRydWUsZXhpc3Rfb2s9VHJ1ZSkKICAgICAgICAgICAgICAgICAgICBzaHV0aWwuY29weTIoc3JjLHRhcmdldCkKICAgICAgICAgICAgICAgICAgICByZXBhaXJlZC5hcHBlbmQoeydyZXF1ZXN0ZWQnOnJlbCwnY29waWVkX2Zyb20nOnNyYy5yZWxhdGl2ZV90byhjc3RyaWtlKS5hc19wb3NpeCgpfSkKICAgICAgICAgICAgICAgICAgICBpbmRleC5zZXRkZWZhdWx0KHJlbC5sb3dlcigpLFtdKS5hcHBlbmQodGFyZ2V0KQogICAgICAgICAgICAgICAgZWxpZiBub3QgZm91bmQ6CiAgICAgICAgICAgICAgICAgICAgdW5yZXNvbHZlZC5hcHBlbmQoeydyZXF1ZXN0ZWQnOnJlbCwncmVzJzpyZi5uYW1lfSkKICAgIHJldHVybiB7CiAgICAgICAgJ3JlcGFpcmVkX2NvdW50JzpsZW4ocmVwYWlyZWQpLCdyZXBhaXJlZCc6cmVwYWlyZWRbOjEwMF0sCiAgICAgICAgJ3VucmVzb2x2ZWRfY291bnQnOmxlbih1bnJlc29sdmVkKSwndW5yZXNvbHZlZCc6dW5yZXNvbHZlZFs6MTAwXQogICAgfQoKCmRlZiBfaGhfZmFzdGRsX3ZlcmlmeV9ic3BfdjYoY3N0cmlrZTpQYXRoLGRlc3Q6UGF0aCktPmRpY3Q6CiAgICBpbXBvcnQgc3RydWN0CiAgICBiYWRfc291cmNlPVtdCiAgICBiYWRfbWlycm9yPVtdCiAgICBzb3VyY2VfbWFwcz1zb3J0ZWQoKGNzdHJpa2UvJ21hcHMnKS5nbG9iKCcqLmJzcCcpKSBpZiAoY3N0cmlrZS8nbWFwcycpLmlzX2RpcigpIGVsc2UgW10KICAgIG1pcnJvcl9tYXBzPXNvcnRlZCgoZGVzdC8nbWFwcycpLmdsb2IoJyouYnNwJykpIGlmIChkZXN0LydtYXBzJykuaXNfZGlyKCkgZWxzZSBbXQoKICAgIGZvciBmcCBpbiBzb3VyY2VfbWFwczoKICAgICAgICB0cnk6CiAgICAgICAgICAgIHdpdGggZnAub3BlbigncmInKSBhcyBmaDoKICAgICAgICAgICAgICAgIGhlYWQ9ZmgucmVhZCg0KQogICAgICAgICAgICB2ZXI9c3RydWN0LnVucGFjaygnPEknLGhlYWQpWzBdIGlmIGxlbihoZWFkKT09NCBlbHNlIE5vbmUKICAgICAgICAgICAgaWYgdmVyIT0zMDoKICAgICAgICAgICAgICAgIGJhZF9zb3VyY2UuYXBwZW5kKHsnbWFwJzpmcC5uYW1lLCd2ZXJzaW9uJzp2ZXIsJ2hlYWQnOmhlYWQuaGV4KCl9KQogICAgICAgIGV4Y2VwdCBFeGNlcHRpb24gYXMgZXhjOgogICAgICAgICAgICBiYWRfc291cmNlLmFwcGVuZCh7J21hcCc6ZnAubmFtZSwnZXJyb3InOnN0cihleGMpfSkKCiAgICBmb3IgZnAgaW4gbWlycm9yX21hcHM6CiAgICAgICAgdHJ5OgogICAgICAgICAgICB3aXRoIGZwLm9wZW4oJ3JiJykgYXMgZmg6CiAgICAgICAgICAgICAgICBoZWFkPWZoLnJlYWQoNCkKICAgICAgICAgICAgdmVyPXN0cnVjdC51bnBhY2soJzxJJyxoZWFkKVswXSBpZiBsZW4oaGVhZCk9PTQgZWxzZSBOb25lCiAgICAgICAgICAgIGlmIHZlciE9MzA6CiAgICAgICAgICAgICAgICBiYWRfbWlycm9yLmFwcGVuZCh7J21hcCc6ZnAubmFtZSwndmVyc2lvbic6dmVyLCdoZWFkJzpoZWFkLmhleCgpfSkKICAgICAgICBleGNlcHQgRXhjZXB0aW9uIGFzIGV4YzoKICAgICAgICAgICAgYmFkX21pcnJvci5hcHBlbmQoeydtYXAnOmZwLm5hbWUsJ2Vycm9yJzpzdHIoZXhjKX0pCgogICAgbWlzc2luZz1zb3J0ZWQoe3AubmFtZSBmb3IgcCBpbiBzb3VyY2VfbWFwc30te3AubmFtZSBmb3IgcCBpbiBtaXJyb3JfbWFwc30pCiAgICByZXR1cm4gewogICAgICAgICdzb3VyY2VfY291bnQnOmxlbihzb3VyY2VfbWFwcyksJ21pcnJvcl9jb3VudCc6bGVuKG1pcnJvcl9tYXBzKSwKICAgICAgICAnYmFkX3NvdXJjZSc6YmFkX3NvdXJjZSwnYmFkX21pcnJvcic6YmFkX21pcnJvciwnbWlzc2luZyc6bWlzc2luZywKICAgICAgICAnb2snOm5vdCBiYWRfc291cmNlIGFuZCBub3QgYmFkX21pcnJvciBhbmQgbm90IG1pc3NpbmcKICAgIH0KCgpkZWYgX2hoX2Zhc3RkbF9odHRwX3ZlcmlmeV92NihkZXN0OlBhdGgsc2lkOmludCktPmRpY3Q6CiAgICBpbXBvcnQgc3RydWN0CiAgICBtYXBzPXNvcnRlZCgoZGVzdC8nbWFwcycpLmdsb2IoJyouYnNwJykpIGlmIChkZXN0LydtYXBzJykuaXNfZGlyKCkgZWxzZSBbXQogICAgY2hlY2tlZD1bXQogICAgYmFkPVtdCiAgICBmb3IgZnAgaW4gbWFwczoKICAgICAgICByZWw9ZnAucmVsYXRpdmVfdG8oZGVzdCkuYXNfcG9zaXgoKQogICAgICAgIHVybD0naHR0cDovLzEyNy4wLjAuMS9mYXN0ZGwvJytzdHIoaW50KHNpZCkpKycvJyt1cmxsaWIucGFyc2UucXVvdGUocmVsLHNhZmU9Jy8uXy0rKClbXScpCiAgICAgICAgdG1wPVBhdGgodGVtcGZpbGUuZ2V0dGVtcGRpcigpKS8oJ2hoLWZhc3RkbC0nK3NlY3JldHMudG9rZW5faGV4KDUpKycuYmluJykKICAgICAgICBjcD1ydW4oWwogICAgICAgICAgICAnY3VybCcsJy1zUycsJy0tY29ubmVjdC10aW1lb3V0JywnMicsJy0tbWF4LXRpbWUnLCcxMCcsCiAgICAgICAgICAgICctSCcsJ0hvc3Q6IDkwLjE4OS4yMDguMjUnLAogICAgICAgICAgICAnLW8nLHN0cih0bXApLCctdycsJyV7aHR0cF9jb2RlfScsdXJsCiAgICAgICAgXSxjaGVjaz1GYWxzZSx0aW1lb3V0PTEyKQogICAgICAgIGNvZGU9KGNwLnN0ZG91dCBvciAnJykuc3RyaXAoKVstMzpdCiAgICAgICAgaGVhZD1iJycKICAgICAgICB2ZXI9Tm9uZQogICAgICAgIHNpemU9MAogICAgICAgIHRyeToKICAgICAgICAgICAgaWYgdG1wLmlzX2ZpbGUoKToKICAgICAgICAgICAgICAgIHNpemU9dG1wLnN0YXQoKS5zdF9zaXplCiAgICAgICAgICAgICAgICB3aXRoIHRtcC5vcGVuKCdyYicpIGFzIGZoOgogICAgICAgICAgICAgICAgICAgIGhlYWQ9ZmgucmVhZCg0KQogICAgICAgICAgICAgICAgaWYgbGVuKGhlYWQpPT00OgogICAgICAgICAgICAgICAgICAgIHZlcj1zdHJ1Y3QudW5wYWNrKCc8SScsaGVhZClbMF0KICAgICAgICBmaW5hbGx5OgogICAgICAgICAgICB0cnk6IHRtcC51bmxpbmsoKQogICAgICAgICAgICBleGNlcHQgT1NFcnJvcjogcGFzcwogICAgICAgIGl0ZW09eydtYXAnOmZwLm5hbWUsJ2h0dHAnOmNvZGUsJ3ZlcnNpb24nOnZlciwnaGVhZCc6aGVhZC5oZXgoKSwnYnl0ZXMnOnNpemV9CiAgICAgICAgY2hlY2tlZC5hcHBlbmQoaXRlbSkKICAgICAgICBpZiBjb2RlIT0nMjAwJyBvciB2ZXIhPTMwIG9yIHNpemUhPWZwLnN0YXQoKS5zdF9zaXplOgogICAgICAgICAgICBiYWQuYXBwZW5kKGl0ZW0pCiAgICByZXR1cm4geydvayc6bm90IGJhZCwnY2hlY2tlZCc6bGVuKGNoZWNrZWQpLCdiYWQnOmJhZFs6NTBdLCdzYW1wbGUnOmNoZWNrZWRbOjNdfQoKCicnJwppZiAnZGVmIF9oaF9mYXN0ZGxfY2FzZV9yZXBhaXJfdjYoJyBub3QgaW4gczoKICAgIG09cmUuc2VhcmNoKHInKD9tKV5kZWYgX2Zhc3RkbF91cmxcYicscykKICAgIGlmIG5vdCBtOgogICAgICAgIHJhaXNlIFN5c3RlbUV4aXQoJ1tQQVRDSCBFUlJPUl0gX2Zhc3RkbF91cmwgbm90IGZvdW5kJykKICAgIHM9c1s6bS5zdGFydCgpXStoZWxwZXIrc1ttLnN0YXJ0KCk6XQoKZmFzdGRsX3VybD1yJycnZGVmIF9mYXN0ZGxfdXJsKGM6ZGljdCktPnN0cjoKICAgIHNpZD1pbnQoYy5nZXQoJ2lkJykgb3IgMCkKICAgIHJldHVybiBmJ2h0dHA6Ly85MC4xODkuMjA4LjI1L2Zhc3RkbC97c2lkfScKJycnCnM9cmVwbGFjZV9mdW5jKHMsJ19mYXN0ZGxfdXJsJywnX2Zhc3RkbF9hcHBseV9jZmcnLGZhc3RkbF91cmwpCgphcHBseV9jZmc9cicnJ2RlZiBfZmFzdGRsX2FwcGx5X2NmZyhjOmRpY3QsIHJvb3Q6UGF0aHxOb25lPU5vbmUpLT5kaWN0OgogICAgcm9vdD1QYXRoKHJvb3Qgb3IgY1sncGF0aCddKQogICAgY2ZnPXJvb3QvJ2NzdHJpa2Uvc2VydmVyLmNmZycKICAgIGNmZy5wYXJlbnQubWtkaXIocGFyZW50cz1UcnVlLGV4aXN0X29rPVRydWUpCiAgICByYXc9Y2ZnLnJlYWRfdGV4dChlbmNvZGluZz0ndXRmLTgnLGVycm9ycz0naWdub3JlJykgaWYgY2ZnLmV4aXN0cygpIGVsc2UgJycKCiAgICBlc2NhcGVkPUZhbHNlCiAgICBpZiByYXcuY291bnQoJ1xcbicpPj01IGFuZCByYXcuY291bnQoJ1xuJyk8PTI6CiAgICAgICAgcmF3PXJhdy5yZXBsYWNlKCdcXHJcXG4nLCdcbicpLnJlcGxhY2UoJ1xcbicsJ1xuJykucmVwbGFjZSgnXFxyJywnXG4nKQogICAgICAgIGVzY2FwZWQ9VHJ1ZQoKICAgIHRleHQ9cmF3LnJlcGxhY2UoJ1xyXG4nLCdcbicpLnJlcGxhY2UoJ1xyJywnXG4nKQogICAgdGV4dD1yZS5zdWIoCiAgICAgICAgcicoP2ltcyleXHMqLy8gSFlQRVItSE9TVCBGQVNUREwgQkVHSU5ccyokLio/XlxzKi8vIEhZUEVSLUhPU1QgRkFTVERMIEVORFxzKiRcbj8nLAogICAgICAgICcnLHRleHQKICAgICkKICAgIG1hbmFnZWQ9eydzdl9kb3dubG9hZHVybCcsJ3N2X2FsbG93ZG93bmxvYWQnLCdzdl9hbGxvd3VwbG9hZCcsJ3N2X3NlbmRfcmVzb3VyY2VzJywnc3ZfYWxsb3dfZGxmaWxlJ30KICAgIGtlcHQ9W10KICAgIHJlbW92ZWQ9W10KICAgIGZvciBsaW5lIGluIHRleHQuc3BsaXRsaW5lcygpOgogICAgICAgIG09cmUubWF0Y2gocideXHMqKFtBLVphLXpfXVtBLVphLXowLTlfXSopXHMrJyxsaW5lKQogICAgICAgIGlmIG0gYW5kIG0uZ3JvdXAoMSkubG93ZXIoKSBpbiBtYW5hZ2VkOgogICAgICAgICAgICByZW1vdmVkLmFwcGVuZChsaW5lLnN0cmlwKCkpCiAgICAgICAgICAgIGNvbnRpbnVlCiAgICAgICAga2VwdC5hcHBlbmQobGluZSkKCiAgICBjb21wYWN0PVtdCiAgICBibGFuaz0wCiAgICBmb3IgbGluZSBpbiBrZXB0OgogICAgICAgIGlmIGxpbmUuc3RyaXAoKT09Jyc6CiAgICAgICAgICAgIGJsYW5rKz0xCiAgICAgICAgICAgIGlmIGJsYW5rPjI6CiAgICAgICAgICAgICAgICBjb250aW51ZQogICAgICAgIGVsc2U6CiAgICAgICAgICAgIGJsYW5rPTAKICAgICAgICBjb21wYWN0LmFwcGVuZChsaW5lLnJzdHJpcCgpKQoKICAgIHVybD1fZmFzdGRsX3VybChjKS5yc3RyaXAoJy8nKSsnLycKICAgIGJsb2NrPVsKICAgICAgICAnLy8gSFlQRVItSE9TVCBGQVNUREwgQkVHSU4nLAogICAgICAgICcvLyBNYW5hZ2VkIGJ5IEhZUEVSLUhPU1QuIERvIG5vdCBkdXBsaWNhdGUgdGhpcyBibG9jay4nLAogICAgICAgICdzdl9hbGxvd2Rvd25sb2FkIDEnLAogICAgICAgICdzdl9hbGxvd3VwbG9hZCAwJywKICAgICAgICAnc3Zfc2VuZF9yZXNvdXJjZXMgMScsCiAgICAgICAgJ3N2X2FsbG93X2RsZmlsZSAxJywKICAgICAgICBmJ3N2X2Rvd25sb2FkdXJsICJ7dXJsfSInLAogICAgICAgICcvLyBIWVBFUi1IT1NUIEZBU1RETCBFTkQnCiAgICBdCiAgICBjb250ZW50PSdcbicuam9pbihjb21wYWN0KS5yc3RyaXAoKSsnXG5cbicrJ1xuJy5qb2luKGJsb2NrKSsnXG4nCiAgICBjZmcud3JpdGVfdGV4dChjb250ZW50LGVuY29kaW5nPSd1dGYtOCcpCgogICAgaGVscGVyPScvLyBIWVBFUi1IT1NUIGNhbm9uaWNhbCBGYXN0RExcbicrJ1xuJy5qb2luKGJsb2NrWzI6LTFdKSsnXG4nCiAgICBmb3IgbmFtZSBpbiAoJ2Zhc3RkbC5jZmcnLCdzZXJ2ZXJfZG93bmxvYWRfZml4LmNmZycsJ1NBRkVfRE9XTkxPQURfTU9ERS5jZmcnLCdFTkFCTEVfRkFTVERMX0FGVEVSX1ZFUklGWS5jZmcnKToKICAgICAgICB0cnk6CiAgICAgICAgICAgIChyb290Lydjc3RyaWtlJy9uYW1lKS53cml0ZV90ZXh0KGhlbHBlcixlbmNvZGluZz0ndXRmLTgnKQogICAgICAgIGV4Y2VwdCBFeGNlcHRpb246CiAgICAgICAgICAgIHBhc3MKCiAgICByZXR1cm4gewogICAgICAgICdvayc6VHJ1ZSwndXJsJzp1cmwucnN0cmlwKCcvJyksJ2NvbmZpZyc6c3RyKGNmZyksCiAgICAgICAgJ2VzY2FwZWRfbmV3bGluZXNfcmVwYWlyZWQnOmVzY2FwZWQsCiAgICAgICAgJ3JlbW92ZWRfdHJhbnNwb3J0X2xpbmVzJzpsZW4ocmVtb3ZlZCksCiAgICAgICAgJ2xpbmVfY291bnQnOmxlbihjb250ZW50LnNwbGl0bGluZXMoKSkKICAgIH0KJycnCnM9cmVwbGFjZV9mdW5jKHMsJ19mYXN0ZGxfYXBwbHlfY2ZnJywnX2Zhc3RkbF9jb3B5X3RyZWUnLGFwcGx5X2NmZykKCmNvcHlfdHJlZT1yJycnZGVmIF9mYXN0ZGxfY29weV90cmVlKHNyYzpQYXRoLGRzdDpQYXRoLGFsbG93ZWRfZXh0cz1Ob25lKToKICAgIGlmIG5vdCBzcmMuaXNfZGlyKCk6CiAgICAgICAgaWYgZHN0LmV4aXN0cygpOgogICAgICAgICAgICBzaHV0aWwucm10cmVlKGRzdCxpZ25vcmVfZXJyb3JzPVRydWUpCiAgICAgICAgcmV0dXJuCiAgICBkc3QubWtkaXIocGFyZW50cz1UcnVlLGV4aXN0X29rPVRydWUpCiAgICBjcD1ydW4oWydyc3luYycsJy1hJywnLS1kZWxldGUnLCctLXNhZmUtbGlua3MnLHN0cihzcmMpKycvJyxzdHIoZHN0KSsnLyddLGNoZWNrPUZhbHNlLHRpbWVvdXQ9MTIwMCkKICAgIGlmIGNwLnJldHVybmNvZGUhPTA6CiAgICAgICAgcmFpc2UgUnVudGltZUVycm9yKCdGYXN0REwgcnN5bmMgZmFpbGVkIGZvciAnK3N0cihzcmMpKyc6ICcrKGNwLnN0ZG91dCBvciAnJylbLTI1MDA6XSkKJycnCnM9cmVwbGFjZV9mdW5jKHMsJ19mYXN0ZGxfY29weV90cmVlJywnZmFzdGRsX3N5bmMnLGNvcHlfdHJlZSkKCnN5bmM9cicnJ2RlZiBmYXN0ZGxfc3luYyhzaWQ6aW50LCBjb25maWd1cmU6Ym9vbD1UcnVlKToKICAgIHJlcXVpcmVfcm9vdCgpCiAgICBjPWxvYWRfc2VydmVyKHNpZCkKICAgIHJvb3Q9UGF0aChjWydwYXRoJ10pCiAgICBjc3RyaWtlPXJvb3QvJ2NzdHJpa2UnCiAgICBpZiBub3QgY3N0cmlrZS5pc19kaXIoKToKICAgICAgICByYWlzZSBSdW50aW1lRXJyb3IoZidjc3RyaWtlIGRpcmVjdG9yeSBpcyBtaXNzaW5nOiB7Y3N0cmlrZX0nKQoKICAgIGNhc2VfcmVwYWlyPV9oaF9mYXN0ZGxfY2FzZV9yZXBhaXJfdjYoY3N0cmlrZSkKCiAgICBGQVNURExfUk9PVC5ta2RpcihwYXJlbnRzPVRydWUsZXhpc3Rfb2s9VHJ1ZSkKICAgIGRlc3Q9RkFTVERMX1JPT1Qvc3RyKHNpZCkKICAgIGRlc3QubWtkaXIocGFyZW50cz1UcnVlLGV4aXN0X29rPVRydWUpCgogICAgY29waWVkPVtdCiAgICBmb3IgbmFtZSBpbiBGQVNURExfRElSUzoKICAgICAgICBzcmM9Y3N0cmlrZS9uYW1lCiAgICAgICAgZGQ9ZGVzdC9uYW1lCiAgICAgICAgX2Zhc3RkbF9jb3B5X3RyZWUoc3JjLGRkKQogICAgICAgIGlmIHNyYy5pc19kaXIoKToKICAgICAgICAgICAgY29waWVkLmFwcGVuZChuYW1lKQoKICAgIHNvdXJjZV93YWRzPXtwLm5hbWU6cCBmb3IgcCBpbiBjc3RyaWtlLml0ZXJkaXIoKSBpZiBwLmlzX2ZpbGUoKSBhbmQgcC5zdWZmaXgubG93ZXIoKT09Jy53YWQnfQogICAgZm9yIG9sZCBpbiBkZXN0Lmdsb2IoJyoud2FkJyk6CiAgICAgICAgaWYgb2xkLm5hbWUgbm90IGluIHNvdXJjZV93YWRzOgogICAgICAgICAgICB0cnk6IG9sZC51bmxpbmsoKQogICAgICAgICAgICBleGNlcHQgT1NFcnJvcjogcGFzcwogICAgZm9yIG5hbWUsc3JjIGluIHNvdXJjZV93YWRzLml0ZW1zKCk6CiAgICAgICAgc2h1dGlsLmNvcHkyKHNyYyxkZXN0L25hbWUpCgogICAgenRtcD0wCiAgICBmb3IgZnAgaW4gbGlzdChkZXN0LnJnbG9iKCcqLnp0bXAnKSk6CiAgICAgICAgdHJ5OgogICAgICAgICAgICBmcC51bmxpbmsoKTsgenRtcCs9MQogICAgICAgIGV4Y2VwdCBPU0Vycm9yOgogICAgICAgICAgICBwYXNzCgogICAgY2ZnX3Jlc3VsdD1fZmFzdGRsX2FwcGx5X2NmZyhjLHJvb3QpIGlmIGNvbmZpZ3VyZSBlbHNlIHsndXJsJzpfZmFzdGRsX3VybChjKX0KCiAgICBydW4oWydjaG93bicsJy1SJywncm9vdDp3d3ctZGF0YScsc3RyKGRlc3QpXSxjaGVjaz1GYWxzZSkKICAgIHJ1bihbJ2ZpbmQnLHN0cihkZXN0KSwnLXR5cGUnLCdkJywnLWV4ZWMnLCdjaG1vZCcsJzA3NTUnLCd7fScsJysnXSxjaGVjaz1GYWxzZSkKICAgIHJ1bihbJ2ZpbmQnLHN0cihkZXN0KSwnLXR5cGUnLCdmJywnLWV4ZWMnLCdjaG1vZCcsJzA2NDQnLCd7fScsJysnXSxjaGVjaz1GYWxzZSkKCiAgICBic3A9X2hoX2Zhc3RkbF92ZXJpZnlfYnNwX3Y2KGNzdHJpa2UsZGVzdCkKICAgIGlmIG5vdCBic3AuZ2V0KCdvaycpOgogICAgICAgIHJhaXNlIFJ1bnRpbWVFcnJvcignRmFzdERMIEJTUCBtaXJyb3IgdmVyaWZpY2F0aW9uIGZhaWxlZDogJytqc29uLmR1bXBzKGJzcCxlbnN1cmVfYXNjaWk9RmFsc2UpKQoKICAgIGh0dHA9X2hoX2Zhc3RkbF9odHRwX3ZlcmlmeV92NihkZXN0LHNpZCkKICAgIGlmIG5vdCBodHRwLmdldCgnb2snKToKICAgICAgICByYWlzZSBSdW50aW1lRXJyb3IoJ0Zhc3RETCBIVFRQIGlzIG5vdCBzZXJ2aW5nIHJhdyBCU1AgYnl0ZXM6ICcranNvbi5kdW1wcyhodHRwLmdldCgnYmFkJyxbXSksZW5zdXJlX2FzY2lpPUZhbHNlKSkKCiAgICBmaWxlcz0wOyB0b3RhbD0wCiAgICBmb3IgZnAgaW4gZGVzdC5yZ2xvYignKicpOgogICAgICAgIHRyeToKICAgICAgICAgICAgaWYgZnAuaXNfZmlsZSgpOgogICAgICAgICAgICAgICAgZmlsZXMrPTE7IHRvdGFsKz1mcC5zdGF0KCkuc3Rfc2l6ZQogICAgICAgIGV4Y2VwdCBPU0Vycm9yOgogICAgICAgICAgICBwYXNzCgogICAgY1snZmFzdGRsX3VybCddPXN0cihjZmdfcmVzdWx0LmdldCgndXJsJykgb3IgX2Zhc3RkbF91cmwoYykpLnJzdHJpcCgnLycpCiAgICBjWydmYXN0ZGxfbGFzdF9zeW5jJ109aW50KHRpbWUudGltZSgpKQogICAgY1snZmFzdGRsX2ZpbGVzJ109ZmlsZXMKICAgIGNbJ2Zhc3RkbF9ieXRlcyddPXRvdGFsCiAgICBzYXZlX3NlcnZlcihjKQoKICAgIHJ1bnRpbWVfZXJyb3JzPVtdCiAgICBpZiBzZXJ2aWNlX3N0YXR1cyhzaWQpPT0nYWN0aXZlJyBhbmQgdWRwX2xpc3RlbmluZyhpbnQoYy5nZXQoJ3BvcnQnKSBvciAwKSk6CiAgICAgICAgZm9yIGNtZCBpbiBbCiAgICAgICAgICAgICdzdl9hbGxvd2Rvd25sb2FkIDEnLAogICAgICAgICAgICAnc3ZfYWxsb3d1cGxvYWQgMCcsCiAgICAgICAgICAgICdzdl9zZW5kX3Jlc291cmNlcyAxJywKICAgICAgICAgICAgJ3N2X2FsbG93X2RsZmlsZSAxJywKICAgICAgICAgICAgZidzdl9kb3dubG9hZHVybCAie2NbImZhc3RkbF91cmwiXX0vIicKICAgICAgICBdOgogICAgICAgICAgICB0cnk6CiAgICAgICAgICAgICAgICBxdWVyeV9yY29uKCcxMjcuMC4wLjEnLGludChjWydwb3J0J10pLHN0cihjLmdldCgncmNvbl9wYXNzd29yZCcsJycpKSxjbWQsMi4wKQogICAgICAgICAgICBleGNlcHQgRXhjZXB0aW9uIGFzIGV4YzoKICAgICAgICAgICAgICAgIHJ1bnRpbWVfZXJyb3JzLmFwcGVuZChzdHIoZXhjKSkKCiAgICByZXR1cm4gewogICAgICAgICdvayc6VHJ1ZSwnaWQnOnNpZCwndXJsJzpjWydmYXN0ZGxfdXJsJ10sJ3Jvb3QnOnN0cihkZXN0KSwKICAgICAgICAnZmlsZXMnOmZpbGVzLCdieXRlcyc6dG90YWwsJ2RpcnMnOmNvcGllZCwKICAgICAgICAnbWFwcyc6YnNwLmdldCgnbWlycm9yX2NvdW50JywwKSwnYnNwJzpic3AsJ2h0dHAnOmh0dHAsCiAgICAgICAgJ2Nhc2VfcmVwYWlyJzpjYXNlX3JlcGFpciwncmVtb3ZlZF96dG1wJzp6dG1wLAogICAgICAgICdjb25maWcnOmNmZ19yZXN1bHQsJ3J1bnRpbWVfZXJyb3JzJzpydW50aW1lX2Vycm9yc1s6NV0KICAgIH0KJycnCnM9cmVwbGFjZV9mdW5jKHMsJ2Zhc3RkbF9zeW5jJywnZmFzdGRsX3N0YXR1cycsc3luYykKCnN0YXR1cz1yJycnZGVmIGZhc3RkbF9zdGF0dXMoc2lkOmludCk6CiAgICBjPWxvYWRfc2VydmVyKHNpZCkKICAgIGRlc3Q9RkFTVERMX1JPT1Qvc3RyKHNpZCkKICAgIGNmZz1QYXRoKGNbJ3BhdGgnXSkvJ2NzdHJpa2Uvc2VydmVyLmNmZycKICAgIHVybD1fZmFzdGRsX3VybChjKS5yc3RyaXAoJy8nKQogICAgZmlsZXM9MDsgdG90YWw9MAogICAgaWYgZGVzdC5pc19kaXIoKToKICAgICAgICBmb3IgZnAgaW4gZGVzdC5yZ2xvYignKicpOgogICAgICAgICAgICB0cnk6CiAgICAgICAgICAgICAgICBpZiBmcC5pc19maWxlKCk6CiAgICAgICAgICAgICAgICAgICAgZmlsZXMrPTE7IHRvdGFsKz1mcC5zdGF0KCkuc3Rfc2l6ZQogICAgICAgICAgICBleGNlcHQgT1NFcnJvcjoKICAgICAgICAgICAgICAgIHBhc3MKCiAgICBjdXJyZW50PScnCiAgICBibG9ja3M9MAogICAgcmVhbF9uZXdsaW5lcz1UcnVlCiAgICBpZiBjZmcuaXNfZmlsZSgpOgogICAgICAgIHJhdz1jZmcucmVhZF90ZXh0KGVuY29kaW5nPSd1dGYtOCcsZXJyb3JzPSdpZ25vcmUnKQogICAgICAgIHJlYWxfbmV3bGluZXM9bm90IChyYXcuY291bnQoJ1xcbicpPj01IGFuZCByYXcuY291bnQoJ1xuJyk8PTIpCiAgICAgICAgdGV4dD1yYXcucmVwbGFjZSgnXFxyXFxuJywnXG4nKS5yZXBsYWNlKCdcXG4nLCdcbicpIGlmIG5vdCByZWFsX25ld2xpbmVzIGVsc2UgcmF3CiAgICAgICAgdmFscz1yZS5maW5kYWxsKHInKD9pbSleXHMqc3ZfZG93bmxvYWR1cmxccysiPyhbXiJcclxuXSspJyx0ZXh0KQogICAgICAgIGlmIHZhbHM6CiAgICAgICAgICAgIGN1cnJlbnQ9dmFsc1stMV0uc3RyaXAoKS5yc3RyaXAoJy8nKQogICAgICAgIGJsb2Nrcz1sZW4ocmUuZmluZGFsbChyJyg/aW0pXlxzKi8vIEhZUEVSLUhPU1QgRkFTVERMIEJFR0lOXHMqJCcsdGV4dCkpCgogICAgaHR0cD1faGhfZmFzdGRsX2h0dHBfdmVyaWZ5X3Y2KGRlc3Qsc2lkKSBpZiBkZXN0LmlzX2RpcigpIGVsc2Ugeydvayc6RmFsc2UsJ2NoZWNrZWQnOjAsJ2JhZCc6W119CiAgICBjb25maWd1cmVkPWJvb2woCiAgICAgICAgZGVzdC5pc19kaXIoKSBhbmQgcmVhbF9uZXdsaW5lcyBhbmQgYmxvY2tzPT0xCiAgICAgICAgYW5kIGN1cnJlbnQucnN0cmlwKCcvJyk9PXVybC5yc3RyaXAoJy8nKSBhbmQgaHR0cC5nZXQoJ29rJykKICAgICkKICAgIHJldHVybiB7CiAgICAgICAgJ29rJzpUcnVlLCdpZCc6c2lkLCd1cmwnOnVybCwnY29uZmlndXJlZF91cmwnOmN1cnJlbnQsCiAgICAgICAgJ2NvbmZpZ3VyZWQnOmNvbmZpZ3VyZWQsJ3Jvb3QnOnN0cihkZXN0KSwnZXhpc3RzJzpkZXN0LmlzX2RpcigpLAogICAgICAgICdmaWxlcyc6ZmlsZXMsJ2J5dGVzJzp0b3RhbCwnbGFzdF9zeW5jJzppbnQoYy5nZXQoJ2Zhc3RkbF9sYXN0X3N5bmMnKSBvciAwKSwKICAgICAgICAnY2ZnX3JlYWxfbmV3bGluZXMnOnJlYWxfbmV3bGluZXMsJ2Zhc3RkbF9ibG9ja3MnOmJsb2NrcywKICAgICAgICAnaHR0cF9vayc6Ym9vbChodHRwLmdldCgnb2snKSksJ2h0dHBfY2hlY2tlZCc6aW50KGh0dHAuZ2V0KCdjaGVja2VkJykgb3IgMCksCiAgICAgICAgJ2h0dHBfYmFkJzpodHRwLmdldCgnYmFkJyxbXSkKICAgIH0KJycnCnM9cmVwbGFjZV9mdW5jKHMsJ2Zhc3RkbF9zdGF0dXMnLCdfZXh0cmFjdF9leHRlcm5hbF9mYXN0ZGxfdXJsJyxzdGF0dXMpCgpjdGwud3JpdGVfdGV4dChzLGVuY29kaW5nPSd1dGYtOCcpCg==' | base64 -d >"$P"
python3 "$P" "$SRC_CTL"
python3 -m py_compile "$SRC_CTL"
install -m 0755 "$SRC_CTL" "$LIVE_CTL"
python3 -m py_compile "$LIVE_CTL"
rm -f "$P"

echo "[4/9] Validate source BSP..."
python3 - "$CSTRIKE/maps" <<'PY'
from pathlib import Path
import struct,sys
bad=[]; good=0
for p in sorted(Path(sys.argv[1]).glob('*.bsp')):
    with p.open('rb') as f: h=f.read(4)
    v=struct.unpack('<I',h)[0] if len(h)==4 else None
    if v==30: good+=1
    else: bad.append((p.name,v,h.hex()))
print("valid BSP:",good)
print("bad BSP:",len(bad))
for x in bad: print("BAD",x)
if bad: raise SystemExit(3)
PY

echo "[5/9] Full clean sync..."
"$LIVE_CTL" fastdl-sync "$SID"

echo "[6/9] Restart HLDS..."
systemctl restart "hyper-cs16@${SID}.service"
sleep 3

echo "[7/9] Verify every BSP through nginx..."
python3 - "$FASTDL/maps" "$SID" <<'PY'
from pathlib import Path
import urllib.request,urllib.parse,struct,sys
root=Path(sys.argv[1]); sid=int(sys.argv[2])
bad=[]; checked=0
for p in sorted(root.glob('*.bsp')):
    rel='maps/'+p.name
    url='http://127.0.0.1/fastdl/%d/%s'%(sid,urllib.parse.quote(rel,safe='/._-+()[]'))
    req=urllib.request.Request(url,headers={'Host':'90.189.208.25','User-Agent':'GoldSrc-FastDL-Test'})
    try:
        with urllib.request.urlopen(req,timeout=8) as r:
            data=r.read(); code=r.status
    except Exception as e:
        bad.append((p.name,'request',str(e))); continue
    checked+=1
    head=data[:4]
    ver=struct.unpack('<I',head)[0] if len(head)==4 else None
    if code!=200 or ver!=30 or len(data)!=p.stat().st_size:
        bad.append((p.name,code,ver,head.hex(),len(data),p.stat().st_size))
print("HTTP BSP checked:",checked)
print("HTTP BSP bad:",len(bad))
for x in bad[:50]: print("BAD",x)
if bad: raise SystemExit(4)
PY

echo "[8/9] Check repaired server.cfg..."
python3 - "$CSTRIKE/server.cfg" <<'PY'
from pathlib import Path
import re,sys
p=Path(sys.argv[1]); raw=p.read_bytes(); txt=raw.decode('utf-8','ignore')
print("real LF:",raw.count(b'\n'))
print("literal \\n:",raw.count(b'\\n'))
print("FastDL blocks:",len(re.findall(r'(?im)^\s*// HYPER-HOST FASTDL BEGIN\s*$',txt)))
print("sv_downloadurl entries:",len(re.findall(r'(?im)^\s*sv_downloadurl\b',txt)))
PY

echo "[9/9] Runtime/status..."
"$LIVE_CTL" fastdl-status "$SID" || true
"$LIVE_CTL" rcon "$SID" "sv_downloadurl" || true
"$LIVE_CTL" rcon "$SID" "sv_allowdownload" || true

echo
echo "[SUCCESS] FASTDL FINAL v6"
echo "URL: http://$PUBLIC_IP/fastdl/$SID/"
echo "8080 is no longer used."
echo "Backup: $BACKUP"
