#!/usr/bin/env bash
set -Eeuo pipefail

ROOT="${1:-/root/hyper-hosting-panel}"
SID="${2:-25}"
PUBLIC_IP="90.189.208.25"
LAN_IP="192.168.0.179"

SRC_CTL="$ROOT/cs16-panel/bin/hyper-cs16-ctl"
LIVE_CTL="/usr/local/sbin/hyper-cs16-ctl"
SERVER_ROOT="/srv/hyper-cs16/servers/${SID}"
CSTRIKE="$SERVER_ROOT/cstrike"
FASTDL="/srv/hyper-cs16/fastdl/${SID}"
NGINX_CONF="/etc/nginx/conf.d/00-hyper-cs16-fastdl-ip.conf"
STAMP="$(date +%Y%m%d-%H%M%S)"
BACKUP="/root/hyper-cs16-fastdl-selfheal-v5-${STAMP}"

[[ ${EUID:-$(id -u)} -eq 0 ]] || { echo "[ERROR] run as root"; exit 1; }
[[ -f "$SRC_CTL" ]] || { echo "[ERROR] missing controller: $SRC_CTL"; exit 2; }
[[ -d "$CSTRIKE" ]] || { echo "[ERROR] missing server cstrike: $CSTRIKE"; exit 2; }

mkdir -p "$BACKUP"
cp -a "$SRC_CTL" "$BACKUP/hyper-cs16-ctl.repo"
[[ -f "$LIVE_CTL" ]] && cp -a "$LIVE_CTL" "$BACKUP/hyper-cs16-ctl.live"
[[ -f "$CSTRIKE/server.cfg" ]] && cp -a "$CSTRIKE/server.cfg" "$BACKUP/server.cfg"
for f in fastdl.cfg server_download_fix.cfg SAFE_DOWNLOAD_MODE.cfg ENABLE_FASTDL_AFTER_VERIFY.cfg; do
  [[ -f "$CSTRIKE/$f" ]] && cp -a "$CSTRIKE/$f" "$BACKUP/$f"
done
[[ -f "$NGINX_CONF" ]] && cp -a "$NGINX_CONF" "$BACKUP/nginx-fastdl.conf"

echo "================================================================"
echo " HYPER-HOST CS 1.6 FASTDL SELF-HEAL v5"
echo " Server: #$SID"
echo " Public: $PUBLIC_IP"
echo " Backup: $BACKUP"
echo "================================================================"

echo "[1/8] Diagnose current server.cfg..."
python3 - "$CSTRIKE/server.cfg" <<'PY'
from pathlib import Path
import sys,re
p=Path(sys.argv[1])
raw=p.read_bytes()
print("server.cfg bytes:",len(raw))
print("real LF bytes:",raw.count(b'\n'))
print("literal \\n sequences:",raw.count(b'\\n'))
txt=raw.decode('utf-8','ignore')
logical=txt.replace('\\r\\n','\n').replace('\\n','\n').replace('\\r','\n')
print("FastDL BEGIN blocks:",len(re.findall(r'(?im)^\s*// HYPER-HOST FASTDL BEGIN',logical)))
print("sv_downloadurl entries:",len(re.findall(r'(?im)^\s*sv_downloadurl\b',logical)))
if raw.count(b'\n')==0 and raw.count(b'\\n')>20:
    print("[BAD] server.cfg is one physical line with escaped newlines")
PY

echo "[2/8] Patch panel FastDL logic..."
PATCHER="$(mktemp)"
echo 'CmZyb20gcGF0aGxpYiBpbXBvcnQgUGF0aAppbXBvcnQgcmUsIHN5cwoKY3RsID0gUGF0aChzeXMuYXJndlsxXSkKCmRlZiByZXBsYWNlX2Z1bmModGV4dCwgbmFtZSwgbmV4dF9uYW1lLCBib2R5KToKICAgIHBhdCA9IHJlLmNvbXBpbGUocmYnKD9tcyleZGVmIHtyZS5lc2NhcGUobmFtZSl9XGIuKj8oPz1eZGVmIHtyZS5lc2NhcGUobmV4dF9uYW1lKX1cYiknKQogICAgbSA9IHBhdC5zZWFyY2godGV4dCkKICAgIGlmIG5vdCBtOgogICAgICAgIHJhaXNlIFN5c3RlbUV4aXQoZidbUEFUQ0ggRVJST1JdIGZ1bmN0aW9uIHJhbmdlIG5vdCBmb3VuZDoge25hbWV9IC0+IHtuZXh0X25hbWV9JykKICAgIHJldHVybiB0ZXh0WzptLnN0YXJ0KCldICsgYm9keS5yc3RyaXAoKSArICdcblxuJyArIHRleHRbbS5lbmQoKTpdCgpzID0gY3RsLnJlYWRfdGV4dChlbmNvZGluZz0ndXRmLTgnKQoKaGVscGVycyA9IHInJydkZWYgX2hoX2Zhc3RkbF9uZ2lueF9jb25mKCktPlBhdGg6CiAgICByZXR1cm4gUGF0aCgnL2V0Yy9uZ2lueC9jb25mLmQvMDAtaHlwZXItY3MxNi1mYXN0ZGwtaXAuY29uZicpCgoKZGVmIF9oaF9mYXN0ZGxfZW5zdXJlX25naW54KCktPmRpY3Q6CiAgICByZXF1aXJlX3Jvb3QoKQogICAgY29uZj1faGhfZmFzdGRsX25naW54X2NvbmYoKQogICAgY29uZi5wYXJlbnQubWtkaXIocGFyZW50cz1UcnVlLGV4aXN0X29rPVRydWUpCiAgICBkZXNpcmVkPSgKICAgICAgICAnc2VydmVyIHtcbicKICAgICAgICAnICAgIGxpc3RlbiA4MDtcbicKICAgICAgICAnICAgIGxpc3RlbiBbOjpdOjgwO1xuJwogICAgICAgICcgICAgc2VydmVyX25hbWUgOTAuMTg5LjIwOC4yNTtcblxuJwogICAgICAgICcgICAgYWNjZXNzX2xvZyAvdmFyL2xvZy9uZ2lueC9oeXBlci1jczE2LWZhc3RkbC1hY2Nlc3MubG9nO1xuJwogICAgICAgICcgICAgZXJyb3JfbG9nICAvdmFyL2xvZy9uZ2lueC9oeXBlci1jczE2LWZhc3RkbC1lcnJvci5sb2cgd2FybjtcblxuJwogICAgICAgICcgICAgbG9jYXRpb24gXn4gL2Zhc3RkbC8ge1xuJwogICAgICAgICcgICAgICAgIGFsaWFzIC9zcnYvaHlwZXItY3MxNi9mYXN0ZGwvO1xuJwogICAgICAgICcgICAgICAgIGF1dG9pbmRleCBvZmY7XG4nCiAgICAgICAgJyAgICAgICAgZGVmYXVsdF90eXBlIGFwcGxpY2F0aW9uL29jdGV0LXN0cmVhbTtcbicKICAgICAgICAnICAgICAgICBhZGRfaGVhZGVyIENhY2hlLUNvbnRyb2wgInB1YmxpYywgbWF4LWFnZT04NjQwMCIgYWx3YXlzO1xuJwogICAgICAgICcgICAgICAgIGFkZF9oZWFkZXIgWC1IeXBlci1GYXN0REwgIjEiIGFsd2F5cztcbicKICAgICAgICAnICAgIH1cblxuJwogICAgICAgICcgICAgbG9jYXRpb24gLyB7XG4nCiAgICAgICAgJyAgICAgICAgcmV0dXJuIDQwNDtcbicKICAgICAgICAnICAgIH1cbicKICAgICAgICAnfVxuJwogICAgKQogICAgY2hhbmdlZD1ub3QgY29uZi5pc19maWxlKCkgb3IgY29uZi5yZWFkX3RleHQoZW5jb2Rpbmc9J3V0Zi04JyxlcnJvcnM9J2lnbm9yZScpIT1kZXNpcmVkCiAgICBvbGQ9Y29uZi5yZWFkX2J5dGVzKCkgaWYgY29uZi5leGlzdHMoKSBlbHNlIE5vbmUKICAgIGlmIGNoYW5nZWQ6CiAgICAgICAgY29uZi53cml0ZV90ZXh0KGRlc2lyZWQsZW5jb2Rpbmc9J3V0Zi04JykKICAgICAgICB0ZXN0PXJ1bihbJ25naW54JywnLXQnXSxjaGVjaz1GYWxzZSx0aW1lb3V0PTMwKQogICAgICAgIGlmIHRlc3QucmV0dXJuY29kZSE9MDoKICAgICAgICAgICAgaWYgb2xkIGlzIE5vbmU6CiAgICAgICAgICAgICAgICBjb25mLnVubGluayhtaXNzaW5nX29rPVRydWUpCiAgICAgICAgICAgIGVsc2U6CiAgICAgICAgICAgICAgICBjb25mLndyaXRlX2J5dGVzKG9sZCkKICAgICAgICAgICAgcmFpc2UgUnVudGltZUVycm9yKCdGYXN0REwgbmdpbnggY29uZmlnIGZhaWxlZCB2YWxpZGF0aW9uOiAnKyh0ZXN0LnN0ZG91dCBvciAnJylbLTI1MDA6XSkKICAgICAgICBydW4oWydzeXN0ZW1jdGwnLCdyZWxvYWQnLCduZ2lueCddLGNoZWNrPUZhbHNlLHRpbWVvdXQ9MzApCiAgICByZXR1cm4geydvayc6VHJ1ZSwnY29uZmlnJzpzdHIoY29uZiksJ2NoYW5nZWQnOmNoYW5nZWR9CgoKZGVmIF9oaF9mYXN0ZGxfcmVzb3VyY2VfY2FzZV9hbGlhc2VzKGNzdHJpa2U6UGF0aCktPmRpY3Q6CiAgICBhbGxvd2VkPSgnbWFwcycsJ21vZGVscycsJ3NvdW5kJywnc3ByaXRlcycsJ2dmeCcsJ3Jlc291cmNlJywnb3ZlcnZpZXdzJywnZXZlbnRzJywnbWVkaWEnKQogICAgaW5kZXg9e30KICAgIGZvciB0b3AgaW4gYWxsb3dlZDoKICAgICAgICBiYXNlPWNzdHJpa2UvdG9wCiAgICAgICAgaWYgbm90IGJhc2UuaXNfZGlyKCk6CiAgICAgICAgICAgIGNvbnRpbnVlCiAgICAgICAgZm9yIGZwIGluIGJhc2Uucmdsb2IoJyonKToKICAgICAgICAgICAgdHJ5OgogICAgICAgICAgICAgICAgaWYgZnAuaXNfZmlsZSgpIGFuZCBub3QgZnAuaXNfc3ltbGluaygpOgogICAgICAgICAgICAgICAgICAgIHJlbD1mcC5yZWxhdGl2ZV90byhjc3RyaWtlKS5hc19wb3NpeCgpCiAgICAgICAgICAgICAgICAgICAgaW5kZXguc2V0ZGVmYXVsdChyZWwubG93ZXIoKSxbXSkuYXBwZW5kKGZwKQogICAgICAgICAgICBleGNlcHQgT1NFcnJvcjoKICAgICAgICAgICAgICAgIHBhc3MKICAgIGZvciBmcCBpbiBjc3RyaWtlLmdsb2IoJyoud2FkJyk6CiAgICAgICAgaWYgZnAuaXNfZmlsZSgpOgogICAgICAgICAgICBpbmRleC5zZXRkZWZhdWx0KGZwLm5hbWUubG93ZXIoKSxbXSkuYXBwZW5kKGZwKQoKICAgIHdhbnRlZD1bXQoKICAgIGZvciByZiBpbiAoY3N0cmlrZS8nbWFwcycpLmdsb2IoJyoucmVzJykgaWYgKGNzdHJpa2UvJ21hcHMnKS5pc19kaXIoKSBlbHNlIFtdOgogICAgICAgIHRyeToKICAgICAgICAgICAgdGV4dD1yZi5yZWFkX3RleHQoZW5jb2Rpbmc9J2xhdGluMScsZXJyb3JzPSdpZ25vcmUnKQogICAgICAgIGV4Y2VwdCBFeGNlcHRpb246CiAgICAgICAgICAgIGNvbnRpbnVlCiAgICAgICAgZm9yIHJhdyBpbiB0ZXh0LnJlcGxhY2UoJ1xyJywnXG4nKS5zcGxpdGxpbmVzKCk6CiAgICAgICAgICAgIGxpbmU9cmF3LnNwbGl0KCcvLycsMSlbMF0uc3RyaXAoKS5zdHJpcCgnIicpLnJlcGxhY2UoJ1xcJywnLycpCiAgICAgICAgICAgIGlmIG5vdCBsaW5lIG9yICcuLicgaW4gUGF0aChsaW5lKS5wYXJ0czoKICAgICAgICAgICAgICAgIGNvbnRpbnVlCiAgICAgICAgICAgIGlmIHJlLm1hdGNoKHInXig/Om1hcHN8bW9kZWxzfHNvdW5kfHNwcml0ZXN8Z2Z4fHJlc291cmNlfG92ZXJ2aWV3c3xldmVudHN8bWVkaWEpLycsbGluZSxyZS5JKSBvciByZS5tYXRjaChyJ15bXi9dK1wud2FkJCcsbGluZSxyZS5JKToKICAgICAgICAgICAgICAgIHdhbnRlZC5hcHBlbmQoKHN0cihyZi5yZWxhdGl2ZV90byhjc3RyaWtlKSksbGluZSkpCgogICAgc2NyaXB0cz1jc3RyaWtlLydhZGRvbnMvYW14bW9keC9zY3JpcHRpbmcnCiAgICBpZiBzY3JpcHRzLmlzX2RpcigpOgogICAgICAgIHBhdHM9WwogICAgICAgICAgICAoJ21vZGVsJyxyZS5jb21waWxlKHIncHJlY2FjaGVfbW9kZWxccypcKFxzKiIoW14iXSspIicscmUuSSkpLAogICAgICAgICAgICAoJ3NvdW5kJyxyZS5jb21waWxlKHIncHJlY2FjaGVfc291bmRccypcKFxzKiIoW14iXSspIicscmUuSSkpLAogICAgICAgICAgICAoJ2dlbmVyaWMnLHJlLmNvbXBpbGUocidwcmVjYWNoZV9nZW5lcmljXHMqXChccyoiKFteIl0rKSInLHJlLkkpKSwKICAgICAgICAgICAgKCdtb2RlbCcscmUuY29tcGlsZShyJ0VuZ0Z1bmNfUHJlY2FjaGVNb2RlbFxzKixccyoiKFteIl0rKSInLHJlLkkpKSwKICAgICAgICAgICAgKCdzb3VuZCcscmUuY29tcGlsZShyJ0VuZ0Z1bmNfUHJlY2FjaGVTb3VuZFxzKixccyoiKFteIl0rKSInLHJlLkkpKSwKICAgICAgICAgICAgKCdnZW5lcmljJyxyZS5jb21waWxlKHInRW5nRnVuY19QcmVjYWNoZUdlbmVyaWNccyosXHMqIihbXiJdKykiJyxyZS5JKSksCiAgICAgICAgXQogICAgICAgIGZvciBzZiBpbiBzY3JpcHRzLmdsb2IoJyouc21hJyk6CiAgICAgICAgICAgIHRyeToKICAgICAgICAgICAgICAgIHRleHQ9c2YucmVhZF90ZXh0KGVuY29kaW5nPSdsYXRpbjEnLGVycm9ycz0naWdub3JlJykKICAgICAgICAgICAgZXhjZXB0IEV4Y2VwdGlvbjoKICAgICAgICAgICAgICAgIGNvbnRpbnVlCiAgICAgICAgICAgIGZvciBraW5kLHBhdCBpbiBwYXRzOgogICAgICAgICAgICAgICAgZm9yIG0gaW4gcGF0LmZpbmRpdGVyKHRleHQpOgogICAgICAgICAgICAgICAgICAgIHJlbD1tLmdyb3VwKDEpLnJlcGxhY2UoJ1xcJywnLycpLmxzdHJpcCgnLycpCiAgICAgICAgICAgICAgICAgICAgaWYga2luZD09J3NvdW5kJyBhbmQgbm90IHJlbC5sb3dlcigpLnN0YXJ0c3dpdGgoJ3NvdW5kLycpOgogICAgICAgICAgICAgICAgICAgICAgICByZWw9J3NvdW5kLycrcmVsCiAgICAgICAgICAgICAgICAgICAgaWYgJy4uJyBub3QgaW4gUGF0aChyZWwpLnBhcnRzOgogICAgICAgICAgICAgICAgICAgICAgICB3YW50ZWQuYXBwZW5kKChzdHIoc2YucmVsYXRpdmVfdG8oY3N0cmlrZSkpLHJlbCkpCgogICAgcmVwYWlyZWQ9W10KICAgIHVucmVzb2x2ZWQ9W10KICAgIHNlZW49c2V0KCkKICAgIGNyb290PWNzdHJpa2UucmVzb2x2ZSgpCiAgICBmb3Igc291cmNlLHJlbCBpbiB3YW50ZWQ6CiAgICAgICAga2V5PShzb3VyY2UscmVsKQogICAgICAgIGlmIGtleSBpbiBzZWVuOgogICAgICAgICAgICBjb250aW51ZQogICAgICAgIHNlZW4uYWRkKGtleSkKICAgICAgICB0YXJnZXQ9KGNzdHJpa2UvcmVsKS5yZXNvbHZlKCkKICAgICAgICB0cnk6CiAgICAgICAgICAgIHRhcmdldC5yZWxhdGl2ZV90byhjcm9vdCkKICAgICAgICBleGNlcHQgVmFsdWVFcnJvcjoKICAgICAgICAgICAgY29udGludWUKICAgICAgICBpZiB0YXJnZXQuaXNfZmlsZSgpOgogICAgICAgICAgICBjb250aW51ZQogICAgICAgIG1hdGNoZXM9aW5kZXguZ2V0KHJlbC5sb3dlcigpLFtdKQogICAgICAgIGlmIGxlbihtYXRjaGVzKT09MToKICAgICAgICAgICAgc3JjPW1hdGNoZXNbMF0KICAgICAgICAgICAgdGFyZ2V0LnBhcmVudC5ta2RpcihwYXJlbnRzPVRydWUsZXhpc3Rfb2s9VHJ1ZSkKICAgICAgICAgICAgc2h1dGlsLmNvcHkyKHNyYyx0YXJnZXQpCiAgICAgICAgICAgIHJlcGFpcmVkLmFwcGVuZCh7J3JlcXVlc3RlZCc6cmVsLCdjb3BpZWRfZnJvbSc6c3JjLnJlbGF0aXZlX3RvKGNzdHJpa2UpLmFzX3Bvc2l4KCksJ3NvdXJjZSc6c291cmNlfSkKICAgICAgICAgICAgaW5kZXguc2V0ZGVmYXVsdChyZWwubG93ZXIoKSxbXSkuYXBwZW5kKHRhcmdldCkKICAgICAgICBlbGlmIGxlbihtYXRjaGVzKT09MDoKICAgICAgICAgICAgdW5yZXNvbHZlZC5hcHBlbmQoeydyZXF1ZXN0ZWQnOnJlbCwnc291cmNlJzpzb3VyY2V9KQoKICAgIHJldHVybiB7CiAgICAgICAgJ3JlcGFpcmVkJzpyZXBhaXJlZFs6MTAwXSwKICAgICAgICAncmVwYWlyZWRfY291bnQnOmxlbihyZXBhaXJlZCksCiAgICAgICAgJ3VucmVzb2x2ZWQnOnVucmVzb2x2ZWRbOjEwMF0sCiAgICAgICAgJ3VucmVzb2x2ZWRfY291bnQnOmxlbih1bnJlc29sdmVkKQogICAgfQoKCmRlZiBfaGhfZmFzdGRsX3Byb2JlKGRlc3Q6UGF0aCx1cmw6c3RyKS0+ZGljdDoKICAgIGlmIG5vdCBkZXN0LmlzX2RpcigpOgogICAgICAgIHJldHVybiB7J29rJzpGYWxzZSwnY29kZSc6MCwnZmlsZSc6JycsJ2Vycm9yJzonRmFzdERMIGRpcmVjdG9yeSBpcyBtaXNzaW5nJ30KCiAgICBwcm9iZT1Ob25lCiAgICBtYXBzPWRlc3QvJ21hcHMnCiAgICBpZiBtYXBzLmlzX2RpcigpOgogICAgICAgIHByb2JlPW5leHQoaXRlcihzb3J0ZWQobWFwcy5nbG9iKCd6bV8qLmJzcCcpKSksTm9uZSkKICAgICAgICBpZiBwcm9iZSBpcyBOb25lOgogICAgICAgICAgICBwcm9iZT1uZXh0KGl0ZXIoc29ydGVkKG1hcHMuZ2xvYignKi5ic3AnKSkpLE5vbmUpCiAgICBpZiBwcm9iZSBpcyBOb25lOgogICAgICAgIHByb2JlPW5leHQoKHggZm9yIHggaW4gZGVzdC5yZ2xvYignKicpIGlmIHguaXNfZmlsZSgpKSxOb25lKQogICAgaWYgcHJvYmUgaXMgTm9uZToKICAgICAgICByZXR1cm4geydvayc6RmFsc2UsJ2NvZGUnOjAsJ2ZpbGUnOicnLCdlcnJvcic6J0Zhc3RETCBpcyBlbXB0eSd9CgogICAgcmVsPXByb2JlLnJlbGF0aXZlX3RvKGRlc3QpLmFzX3Bvc2l4KCkKICAgIGJhc2U9dXJsLnJzdHJpcCgnLycpCiAgICBwYXJzZWQ9dXJsbGliLnBhcnNlLnVybHBhcnNlKGJhc2UpCiAgICBwb3J0PXBhcnNlZC5wb3J0IG9yICg0NDMgaWYgcGFyc2VkLnNjaGVtZT09J2h0dHBzJyBlbHNlIDgwKQogICAgaG9zdF9oZWFkZXI9cGFyc2VkLmhvc3RuYW1lIG9yICc5MC4xODkuMjA4LjI1JwogICAgbG9jYWw9ZidodHRwOi8vMTI3LjAuMC4xOntwb3J0fXtwYXJzZWQucGF0aC5yc3RyaXAoIi8iKX0ve3VybGxpYi5wYXJzZS5xdW90ZShyZWwsc2FmZT0iLy5fLSsoKVtdIil9JwogICAgY3A9cnVuKAogICAgICAgIFsnY3VybCcsJy1zUycsJy0tY29ubmVjdC10aW1lb3V0JywnMicsJy0tbWF4LXRpbWUnLCc2JywnLUgnLGYnSG9zdDoge2hvc3RfaGVhZGVyfScsJy1vJywnL2Rldi9udWxsJywnLXcnLCcle2h0dHBfY29kZX0nLGxvY2FsXSwKICAgICAgICBjaGVjaz1GYWxzZSx0aW1lb3V0PTgKICAgICkKICAgIHRyeToKICAgICAgICBjb2RlPWludCgoY3Auc3Rkb3V0IG9yICcwJykuc3RyaXAoKVstMzpdKQogICAgZXhjZXB0IEV4Y2VwdGlvbjoKICAgICAgICBjb2RlPTAKICAgIHJldHVybiB7CiAgICAgICAgJ29rJzpjb2RlPT0yMDAsCiAgICAgICAgJ2NvZGUnOmNvZGUsCiAgICAgICAgJ2ZpbGUnOnJlbCwKICAgICAgICAnbG9jYWxfdXJsJzpsb2NhbCwKICAgICAgICAnaG9zdF9oZWFkZXInOmhvc3RfaGVhZGVyLAogICAgICAgICdlcnJvcic6JycgaWYgY29kZT09MjAwIGVsc2UgKGNwLnN0ZG91dCBvciAnJylbLTUwMDpdCiAgICB9CgoKJycnCgppZiAiZGVmIF9oaF9mYXN0ZGxfZW5zdXJlX25naW54KCIgbm90IGluIHM6CiAgICBtPXJlLnNlYXJjaChyJyg/bSleZGVmIF9mYXN0ZGxfdXJsXGInLHMpCiAgICBpZiBub3QgbToKICAgICAgICByYWlzZSBTeXN0ZW1FeGl0KCdbUEFUQ0ggRVJST1JdIF9mYXN0ZGxfdXJsIGZ1bmN0aW9uIG5vdCBmb3VuZCcpCiAgICBzPXNbOm0uc3RhcnQoKV0raGVscGVycytzW20uc3RhcnQoKTpdCgphcHBseV9jZmcgPSByJycnZGVmIF9mYXN0ZGxfYXBwbHlfY2ZnKGM6ZGljdCwgcm9vdDpQYXRofE5vbmU9Tm9uZSktPmRpY3Q6CiAgICByb290PVBhdGgocm9vdCBvciBjWydwYXRoJ10pCiAgICBjZmc9cm9vdC8nY3N0cmlrZS9zZXJ2ZXIuY2ZnJwogICAgY2ZnLnBhcmVudC5ta2RpcihwYXJlbnRzPVRydWUsZXhpc3Rfb2s9VHJ1ZSkKCiAgICByYXc9Y2ZnLnJlYWRfdGV4dChlbmNvZGluZz0ndXRmLTgnLGVycm9ycz0naWdub3JlJykgaWYgY2ZnLmV4aXN0cygpIGVsc2UgJycKICAgIGVzY2FwZWRfcmVwYWlyZWQ9RmFsc2UKCiAgICBpZiByYXcuY291bnQoJ1xcbicpPj01IGFuZCByYXcuY291bnQoJ1xuJyk8PTI6CiAgICAgICAgcmF3PXJhdy5yZXBsYWNlKCdcXHJcXG4nLCdcbicpLnJlcGxhY2UoJ1xcbicsJ1xuJykucmVwbGFjZSgnXFxyJywnXG4nKQogICAgICAgIGVzY2FwZWRfcmVwYWlyZWQ9VHJ1ZQoKICAgIHRleHQ9cmF3LnJlcGxhY2UoJ1xyXG4nLCdcbicpLnJlcGxhY2UoJ1xyJywnXG4nKQogICAgYmVnaW49Jy8vIEhZUEVSLUhPU1QgRkFTVERMIEJFR0lOJwogICAgZW5kPScvLyBIWVBFUi1IT1NUIEZBU1RETCBFTkQnCgogICAgdGV4dD1yZS5zdWIocicoP2ltcyleXHMqLy8gSFlQRVItSE9TVCBGQVNUREwgQkVHSU5ccyokLio/XlxzKi8vIEhZUEVSLUhPU1QgRkFTVERMIEVORFxzKiRcbj8nLCAnJywgdGV4dCkKCiAgICBtYW5hZ2VkPXsnc3ZfZG93bmxvYWR1cmwnLCdzdl9hbGxvd2Rvd25sb2FkJywnc3ZfYWxsb3d1cGxvYWQnLCdzdl9zZW5kX3Jlc291cmNlcycsJ3N2X2FsbG93X2RsZmlsZSd9CiAgICBrZXB0PVtdCiAgICByZXBsYWNlZD1bXQogICAgZm9yIGxpbmUgaW4gdGV4dC5zcGxpdGxpbmVzKCk6CiAgICAgICAgbT1yZS5tYXRjaChyJ15ccyooW0EtWmEtel9dW0EtWmEtejAtOV9dKilccysnLGxpbmUpCiAgICAgICAgaWYgbSBhbmQgbS5ncm91cCgxKS5sb3dlcigpIGluIG1hbmFnZWQ6CiAgICAgICAgICAgIHJlcGxhY2VkLmFwcGVuZChsaW5lLnN0cmlwKCkpCiAgICAgICAgICAgIGNvbnRpbnVlCiAgICAgICAga2VwdC5hcHBlbmQobGluZSkKCiAgICB1cmw9X2Zhc3RkbF91cmwoYykucnN0cmlwKCcvJykrJy8nCiAgICBibG9jaz1bCiAgICAgICAgYmVnaW4sCiAgICAgICAgJy8vIE1hbmFnZWQgYXV0b21hdGljYWxseSBieSBIWVBFUi1IT1NULiBPbmUgY2Fub25pY2FsIGJsb2NrIG9ubHkuJywKICAgICAgICAnc3ZfYWxsb3dkb3dubG9hZCAxJywKICAgICAgICAnc3ZfYWxsb3d1cGxvYWQgMCcsCiAgICAgICAgJ3N2X3NlbmRfcmVzb3VyY2VzIDEnLAogICAgICAgICdzdl9hbGxvd19kbGZpbGUgMScsCiAgICAgICAgZidzdl9kb3dubG9hZHVybCAie3VybH0iJywKICAgICAgICBlbmQsCiAgICBdCiAgICBjb250ZW50PSdcbicuam9pbihrZXB0KS5yc3RyaXAoKSsnXG5cbicrJ1xuJy5qb2luKGJsb2NrKSsnXG4nCiAgICBjZmcud3JpdGVfdGV4dChjb250ZW50LGVuY29kaW5nPSd1dGYtOCcpCgogICAgaGVscGVyX2NmZz0nLy8gSFlQRVItSE9TVCBjYW5vbmljYWwgRmFzdERMXG4nKydcbicuam9pbihibG9ja1syOi0xXSkrJ1xuJwogICAgZm9yIG5hbWUgaW4gKCdmYXN0ZGwuY2ZnJywnc2VydmVyX2Rvd25sb2FkX2ZpeC5jZmcnLCdTQUZFX0RPV05MT0FEX01PREUuY2ZnJywnRU5BQkxFX0ZBU1RETF9BRlRFUl9WRVJJRlkuY2ZnJyk6CiAgICAgICAgdHJ5OgogICAgICAgICAgICAocm9vdC8nY3N0cmlrZScvbmFtZSkud3JpdGVfdGV4dChoZWxwZXJfY2ZnLGVuY29kaW5nPSd1dGYtOCcpCiAgICAgICAgZXhjZXB0IEV4Y2VwdGlvbjoKICAgICAgICAgICAgcGFzcwoKICAgIHJldHVybiB7CiAgICAgICAgJ29rJzpUcnVlLAogICAgICAgICd1cmwnOnVybC5yc3RyaXAoJy8nKSwKICAgICAgICAnY29uZmlnJzpzdHIoY2ZnKSwKICAgICAgICAncmVwbGFjZWQnOnJlcGxhY2VkLAogICAgICAgICdlc2NhcGVkX25ld2xpbmVzX3JlcGFpcmVkJzplc2NhcGVkX3JlcGFpcmVkLAogICAgICAgICdsaW5lX2NvdW50JzpsZW4oY29udGVudC5zcGxpdGxpbmVzKCkpCiAgICB9CicnJwpzPXJlcGxhY2VfZnVuYyhzLCdfZmFzdGRsX2FwcGx5X2NmZycsJ19mYXN0ZGxfY29weV90cmVlJyxhcHBseV9jZmcpCgpmYXN0ZGxfc3luYyA9IHInJydkZWYgZmFzdGRsX3N5bmMoc2lkOmludCwgY29uZmlndXJlOmJvb2w9VHJ1ZSk6CiAgICByZXF1aXJlX3Jvb3QoKQogICAgYz1sb2FkX3NlcnZlcihzaWQpCiAgICByb290PVBhdGgoY1sncGF0aCddKQogICAgY3N0cmlrZT1yb290Lydjc3RyaWtlJwogICAgaWYgbm90IGNzdHJpa2UuaXNfZGlyKCk6CiAgICAgICAgcmFpc2UgUnVudGltZUVycm9yKGYnY3N0cmlrZSBkaXJlY3RvcnkgaXMgbWlzc2luZzoge2NzdHJpa2V9JykKCiAgICBuZ2lueF9pbmZvPV9oaF9mYXN0ZGxfZW5zdXJlX25naW54KCkKICAgIGNhc2VfaW5mbz1faGhfZmFzdGRsX3Jlc291cmNlX2Nhc2VfYWxpYXNlcyhjc3RyaWtlKQoKICAgIEZBU1RETF9ST09ULm1rZGlyKHBhcmVudHM9VHJ1ZSxleGlzdF9vaz1UcnVlKQogICAgZGVzdD1GQVNURExfUk9PVC9zdHIoc2lkKQogICAgZGVzdC5ta2RpcihwYXJlbnRzPVRydWUsZXhpc3Rfb2s9VHJ1ZSkKCiAgICBjb3BpZWRfZGlycz1bXQogICAgZm9yIG5hbWUgaW4gRkFTVERMX0RJUlM6CiAgICAgICAgc3JjPWNzdHJpa2UvbmFtZQogICAgICAgIGRkPWRlc3QvbmFtZQogICAgICAgIF9mYXN0ZGxfY29weV90cmVlKHNyYyxkZCkKICAgICAgICBpZiBzcmMuaXNfZGlyKCk6CiAgICAgICAgICAgIGNvcGllZF9kaXJzLmFwcGVuZChuYW1lKQoKICAgIHNvdXJjZV93YWRzPXtwLm5hbWU6cCBmb3IgcCBpbiBjc3RyaWtlLml0ZXJkaXIoKSBpZiBwLmlzX2ZpbGUoKSBhbmQgcC5zdWZmaXgubG93ZXIoKT09Jy53YWQnfQogICAgZm9yIG9sZCBpbiBkZXN0Lmdsb2IoJyoud2FkJyk6CiAgICAgICAgaWYgb2xkLm5hbWUgbm90IGluIHNvdXJjZV93YWRzOgogICAgICAgICAgICB0cnk6CiAgICAgICAgICAgICAgICBvbGQudW5saW5rKCkKICAgICAgICAgICAgZXhjZXB0IE9TRXJyb3I6CiAgICAgICAgICAgICAgICBwYXNzCiAgICBmb3IgbmFtZSxzcmMgaW4gc291cmNlX3dhZHMuaXRlbXMoKToKICAgICAgICBzaHV0aWwuY29weTIoc3JjLGRlc3QvbmFtZSkKCiAgICByZW1vdmVkX3p0bXA9MAogICAgZm9yIGZwIGluIGxpc3QoZGVzdC5yZ2xvYignKi56dG1wJykpOgogICAgICAgIHRyeToKICAgICAgICAgICAgZnAudW5saW5rKCkKICAgICAgICAgICAgcmVtb3ZlZF96dG1wKz0xCiAgICAgICAgZXhjZXB0IE9TRXJyb3I6CiAgICAgICAgICAgIHBhc3MKCiAgICBjZmdfcmVzdWx0PV9mYXN0ZGxfYXBwbHlfY2ZnKGMscm9vdCkgaWYgY29uZmlndXJlIGVsc2Ugeyd1cmwnOl9mYXN0ZGxfdXJsKGMpfQoKICAgIHJ1bihbJ2Nob3duJywnLVInLCdyb290Ond3dy1kYXRhJyxzdHIoZGVzdCldLGNoZWNrPUZhbHNlKQogICAgcnVuKFsnZmluZCcsc3RyKGRlc3QpLCctdHlwZScsJ2QnLCctZXhlYycsJ2NobW9kJywnMDc1NScsJ3t9JywnKyddLGNoZWNrPUZhbHNlKQogICAgcnVuKFsnZmluZCcsc3RyKGRlc3QpLCctdHlwZScsJ2YnLCctZXhlYycsJ2NobW9kJywnMDY0NCcsJ3t9JywnKyddLGNoZWNrPUZhbHNlKQoKICAgIGZpbGVzPTAKICAgIHRvdGFsPTAKICAgIG1hcF9jb3VudD0wCiAgICBmb3IgZnAgaW4gZGVzdC5yZ2xvYignKicpOgogICAgICAgIHRyeToKICAgICAgICAgICAgaWYgZnAuaXNfZmlsZSgpOgogICAgICAgICAgICAgICAgZmlsZXMrPTEKICAgICAgICAgICAgICAgIHRvdGFsKz1mcC5zdGF0KCkuc3Rfc2l6ZQogICAgICAgICAgICAgICAgaWYgZnAucGFyZW50PT1kZXN0LydtYXBzJyBhbmQgZnAuc3VmZml4Lmxvd2VyKCk9PScuYnNwJzoKICAgICAgICAgICAgICAgICAgICBtYXBfY291bnQrPTEKICAgICAgICBleGNlcHQgT1NFcnJvcjoKICAgICAgICAgICAgcGFzcwoKICAgIGNbJ2Zhc3RkbF91cmwnXT1zdHIoY2ZnX3Jlc3VsdC5nZXQoJ3VybCcpIG9yIF9mYXN0ZGxfdXJsKGMpKS5yc3RyaXAoJy8nKQogICAgY1snZmFzdGRsX2xhc3Rfc3luYyddPWludCh0aW1lLnRpbWUoKSkKICAgIGNbJ2Zhc3RkbF9maWxlcyddPWZpbGVzCiAgICBjWydmYXN0ZGxfYnl0ZXMnXT10b3RhbAogICAgc2F2ZV9zZXJ2ZXIoYykKCiAgICBydW50aW1lX2FwcGxpZWQ9RmFsc2UKICAgIHJ1bnRpbWVfZXJyb3JzPVtdCiAgICBpZiBzZXJ2aWNlX3N0YXR1cyhzaWQpPT0nYWN0aXZlJyBhbmQgdWRwX2xpc3RlbmluZyhpbnQoYy5nZXQoJ3BvcnQnKSBvciAwKSk6CiAgICAgICAgZm9yIGNtZCBpbiBbCiAgICAgICAgICAgICdzdl9hbGxvd2Rvd25sb2FkIDEnLAogICAgICAgICAgICAnc3ZfYWxsb3d1cGxvYWQgMCcsCiAgICAgICAgICAgICdzdl9zZW5kX3Jlc291cmNlcyAxJywKICAgICAgICAgICAgJ3N2X2FsbG93X2RsZmlsZSAxJywKICAgICAgICAgICAgZidzdl9kb3dubG9hZHVybCAie2NbImZhc3RkbF91cmwiXX0vIicKICAgICAgICBdOgogICAgICAgICAgICB0cnk6CiAgICAgICAgICAgICAgICBxdWVyeV9yY29uKCcxMjcuMC4wLjEnLGludChjWydwb3J0J10pLHN0cihjLmdldCgncmNvbl9wYXNzd29yZCcsJycpKSxjbWQsMi4wKQogICAgICAgICAgICBleGNlcHQgRXhjZXB0aW9uIGFzIGV4YzoKICAgICAgICAgICAgICAgIHJ1bnRpbWVfZXJyb3JzLmFwcGVuZChzdHIoZXhjKSkKICAgICAgICBydW50aW1lX2FwcGxpZWQ9bm90IHJ1bnRpbWVfZXJyb3JzCgogICAgcHJvYmU9X2hoX2Zhc3RkbF9wcm9iZShkZXN0LGNbJ2Zhc3RkbF91cmwnXSkKICAgIHJldHVybiB7CiAgICAgICAgJ29rJzpUcnVlLAogICAgICAgICdpZCc6c2lkLAogICAgICAgICd1cmwnOmNbJ2Zhc3RkbF91cmwnXSwKICAgICAgICAncm9vdCc6c3RyKGRlc3QpLAogICAgICAgICdmaWxlcyc6ZmlsZXMsCiAgICAgICAgJ2J5dGVzJzp0b3RhbCwKICAgICAgICAnbWFwcyc6bWFwX2NvdW50LAogICAgICAgICdkaXJzJzpjb3BpZWRfZGlycywKICAgICAgICAnY29uZmlnJzpjZmdfcmVzdWx0LAogICAgICAgICduZ2lueCc6bmdpbnhfaW5mbywKICAgICAgICAnY2FzZV9yZXBhaXInOmNhc2VfaW5mbywKICAgICAgICAncmVtb3ZlZF96dG1wJzpyZW1vdmVkX3p0bXAsCiAgICAgICAgJ3J1bnRpbWVfYXBwbGllZCc6cnVudGltZV9hcHBsaWVkLAogICAgICAgICdydW50aW1lX2Vycm9ycyc6cnVudGltZV9lcnJvcnNbOjVdLAogICAgICAgICdodHRwJzpwcm9iZQogICAgfQonJycKcz1yZXBsYWNlX2Z1bmMocywnZmFzdGRsX3N5bmMnLCdmYXN0ZGxfc3RhdHVzJyxmYXN0ZGxfc3luYykKCmZhc3RkbF9zdGF0dXMgPSByJycnZGVmIGZhc3RkbF9zdGF0dXMoc2lkOmludCk6CiAgICBjPWxvYWRfc2VydmVyKHNpZCkKICAgIGRlc3Q9RkFTVERMX1JPT1Qvc3RyKHNpZCkKICAgIGNmZz1QYXRoKGNbJ3BhdGgnXSkvJ2NzdHJpa2Uvc2VydmVyLmNmZycKICAgIHVybD1fZmFzdGRsX3VybChjKS5yc3RyaXAoJy8nKQogICAgZmlsZXM9MAogICAgdG90YWw9MAogICAgbWFwcz0wCgogICAgaWYgZGVzdC5pc19kaXIoKToKICAgICAgICBmb3IgZnAgaW4gZGVzdC5yZ2xvYignKicpOgogICAgICAgICAgICB0cnk6CiAgICAgICAgICAgICAgICBpZiBmcC5pc19maWxlKCk6CiAgICAgICAgICAgICAgICAgICAgZmlsZXMrPTEKICAgICAgICAgICAgICAgICAgICB0b3RhbCs9ZnAuc3RhdCgpLnN0X3NpemUKICAgICAgICAgICAgICAgICAgICBpZiBmcC5wYXJlbnQ9PWRlc3QvJ21hcHMnIGFuZCBmcC5zdWZmaXgubG93ZXIoKT09Jy5ic3AnOgogICAgICAgICAgICAgICAgICAgICAgICBtYXBzKz0xCiAgICAgICAgICAgIGV4Y2VwdCBPU0Vycm9yOgogICAgICAgICAgICAgICAgcGFzcwoKICAgIGN1cnJlbnQ9JycKICAgIGNmZ19yZWFsX25ld2xpbmVzPVRydWUKICAgIGZhc3RkbF9ibG9ja3M9MAogICAgaWYgY2ZnLmlzX2ZpbGUoKToKICAgICAgICB0cnk6CiAgICAgICAgICAgIHJhdz1jZmcucmVhZF90ZXh0KGVuY29kaW5nPSd1dGYtOCcsZXJyb3JzPSdpZ25vcmUnKQogICAgICAgICAgICBjZmdfcmVhbF9uZXdsaW5lcz1ub3QgKHJhdy5jb3VudCgnXFxuJyk+PTUgYW5kIHJhdy5jb3VudCgnXG4nKTw9MikKICAgICAgICAgICAgdGV4dD1yYXcucmVwbGFjZSgnXFxyXFxuJywnXG4nKS5yZXBsYWNlKCdcXG4nLCdcbicpIGlmIG5vdCBjZmdfcmVhbF9uZXdsaW5lcyBlbHNlIHJhdwogICAgICAgICAgICB2YWxzPXJlLmZpbmRhbGwocicoP2ltKV5ccypzdl9kb3dubG9hZHVybFxzKyI/KFteIlxyXG5dKyknLHRleHQpCiAgICAgICAgICAgIGlmIHZhbHM6CiAgICAgICAgICAgICAgICBjdXJyZW50PXZhbHNbLTFdLnN0cmlwKCkucnN0cmlwKCcvJykKICAgICAgICAgICAgZmFzdGRsX2Jsb2Nrcz1sZW4ocmUuZmluZGFsbChyJyg/aW0pXlxzKi8vIEhZUEVSLUhPU1QgRkFTVERMIEJFR0lOXHMqJCcsdGV4dCkpCiAgICAgICAgZXhjZXB0IEV4Y2VwdGlvbjoKICAgICAgICAgICAgcGFzcwoKICAgIHByb2JlPV9oaF9mYXN0ZGxfcHJvYmUoZGVzdCx1cmwpCiAgICB1cmxfbWF0Y2g9Y3VycmVudC5yc3RyaXAoJy8nKT09dXJsLnJzdHJpcCgnLycpCiAgICBjb25maWd1cmVkPWJvb2woZGVzdC5pc19kaXIoKSBhbmQgdXJsX21hdGNoIGFuZCBjZmdfcmVhbF9uZXdsaW5lcyBhbmQgZmFzdGRsX2Jsb2Nrcz09MSBhbmQgcHJvYmUuZ2V0KCdvaycpKQoKICAgIHJldHVybiB7CiAgICAgICAgJ29rJzpUcnVlLAogICAgICAgICdpZCc6c2lkLAogICAgICAgICd1cmwnOnVybCwKICAgICAgICAnY29uZmlndXJlZF91cmwnOmN1cnJlbnQsCiAgICAgICAgJ2NvbmZpZ3VyZWQnOmNvbmZpZ3VyZWQsCiAgICAgICAgJ3VybF9tYXRjaCc6dXJsX21hdGNoLAogICAgICAgICdyb290JzpzdHIoZGVzdCksCiAgICAgICAgJ2V4aXN0cyc6ZGVzdC5pc19kaXIoKSwKICAgICAgICAnZmlsZXMnOmZpbGVzLAogICAgICAgICdieXRlcyc6dG90YWwsCiAgICAgICAgJ21hcHMnOm1hcHMsCiAgICAgICAgJ2xhc3Rfc3luYyc6aW50KGMuZ2V0KCdmYXN0ZGxfbGFzdF9zeW5jJykgb3IgMCksCiAgICAgICAgJ2h0dHBfb2snOmJvb2wocHJvYmUuZ2V0KCdvaycpKSwKICAgICAgICAnaHR0cF9jb2RlJzppbnQocHJvYmUuZ2V0KCdjb2RlJykgb3IgMCksCiAgICAgICAgJ3Byb2JlX2ZpbGUnOnN0cihwcm9iZS5nZXQoJ2ZpbGUnKSBvciAnJyksCiAgICAgICAgJ2NmZ19yZWFsX25ld2xpbmVzJzpjZmdfcmVhbF9uZXdsaW5lcywKICAgICAgICAnZmFzdGRsX2Jsb2Nrcyc6ZmFzdGRsX2Jsb2NrcwogICAgfQonJycKcz1yZXBsYWNlX2Z1bmMocywnZmFzdGRsX3N0YXR1cycsJ19leHRyYWN0X2V4dGVybmFsX2Zhc3RkbF91cmwnLGZhc3RkbF9zdGF0dXMpCgpjdGwud3JpdGVfdGV4dChzLGVuY29kaW5nPSd1dGYtOCcpCg==' | base64 -d > "$PATCHER"
python3 "$PATCHER" "$SRC_CTL"
python3 -m py_compile "$SRC_CTL"
install -m 0755 "$SRC_CTL" "$LIVE_CTL"
python3 -m py_compile "$LIVE_CTL"
rm -f "$PATCHER"

echo "[3/8] Install plain-HTTP IP FastDL nginx route..."
cat >"$NGINX_CONF" <<'EOF'
server {
    listen 80;
    listen [::]:80;
    server_name 90.189.208.25;

    access_log /var/log/nginx/hyper-cs16-fastdl-access.log;
    error_log  /var/log/nginx/hyper-cs16-fastdl-error.log warn;

    location ^~ /fastdl/ {
        alias /srv/hyper-cs16/fastdl/;
        autoindex off;
        default_type application/octet-stream;
        add_header Cache-Control "public, max-age=86400" always;
        add_header X-Hyper-FastDL "1" always;
    }

    location / {
        return 404;
    }
}
EOF
nginx -t
systemctl reload nginx

echo "[4/8] Firewall..."
if command -v ufw >/dev/null 2>&1; then
  ufw allow 80/tcp >/dev/null 2>&1 || true
fi

echo "[5/8] Clean sync + cfg repair + resource-case repair..."
"$LIVE_CTL" fastdl-sync "$SID"

echo "[6/8] Restart game server so repaired server.cfg is loaded..."
systemctl restart "hyper-cs16@${SID}.service"
sleep 3

echo "[7/8] Verify FastDL filesystem + HTTP..."
"$LIVE_CTL" fastdl-status "$SID" || true

PROBE="$(find "$FASTDL/maps" -maxdepth 1 -type f -iname 'zm_*.bsp' -print -quit 2>/dev/null || true)"
if [[ -z "$PROBE" ]]; then
  PROBE="$(find "$FASTDL" -type f -print -quit 2>/dev/null || true)"
fi
if [[ -n "$PROBE" ]]; then
  REL="${PROBE#"$FASTDL/"}"
  echo "Probe file: $REL"
  CODE="$(curl -sS --connect-timeout 3 --max-time 10 -H "Host: $PUBLIC_IP" -o /tmp/hh-fastdl-probe.bin -w '%{http_code}' "http://127.0.0.1/fastdl/$SID/$REL" || true)"
  echo "Local nginx HTTP code: $CODE"
  if [[ "$CODE" != "200" ]]; then
    echo "[ERROR] Local FastDL HTTP is not 200"
    exit 10
  fi
  echo "HTTP bytes: $(wc -c </tmp/hh-fastdl-probe.bin)"
  rm -f /tmp/hh-fastdl-probe.bin

  PUBLIC_CODE="$(curl -sS --connect-timeout 3 --max-time 10 -o /dev/null -w '%{http_code}' "http://$PUBLIC_IP/fastdl/$SID/$REL" || true)"
  echo "Public-IP HTTP code from this host: $PUBLIC_CODE"
  if [[ "$PUBLIC_CODE" != "200" ]]; then
    echo "[WARN] Public-IP self-test is not 200; this may be NAT hairpin."
    echo "       External clients still require TCP 80 -> $LAN_IP:80 on the router."
  fi
fi

echo "[8/8] Verify runtime cvars + repaired cfg..."
"$LIVE_CTL" rcon "$SID" "sv_downloadurl" || true
"$LIVE_CTL" rcon "$SID" "sv_allowdownload" || true
"$LIVE_CTL" rcon "$SID" "sv_allow_dlfile" || true

python3 - "$CSTRIKE/server.cfg" <<'PY'
from pathlib import Path
import sys,re
p=Path(sys.argv[1])
raw=p.read_bytes()
txt=raw.decode('utf-8','ignore')
print("real LF bytes after repair:",raw.count(b'\n'))
print("literal \\n after repair:",raw.count(b'\\n'))
print("FastDL blocks after repair:",len(re.findall(r'(?im)^\s*// HYPER-HOST FASTDL BEGIN\s*$',txt)))
urls=re.findall(r'(?im)^\s*sv_downloadurl\s+"?([^"\r\n]+)',txt)
print("sv_downloadurl:",urls[-1] if urls else 'MISSING')
PY

echo
echo "================================================================"
echo " [SUCCESS] FASTDL SELF-HEAL v5 INSTALLED"
echo "================================================================"
echo "Expected URL: http://$PUBLIC_IP/fastdl/$SID/"
echo "Nginx route:  $NGINX_CONF"
echo "FastDL root:  $FASTDL"
echo "Backup:       $BACKUP"
