#!/usr/bin/env bash
set -Eeuo pipefail

CLOUD_DOMAIN="${CLOUD_DOMAIN:-cloud.hyper-host.pw}"
APP_ROOT="${CLOUD_APP_ROOT:-/var/www/hyper-host-cloud-app}"
MANAGED_DIR="${HYPER_NGINX_MANAGED_DIR:-/etc/nginx/hyper-host-managed}"
ACME_ROOT="${HYPER_ACME_ROOT:-/opt/hyper-host/acme-webroot}"
SITE_DIR="${HYPER_SITES_DIR:-/var/www/hyper-host-sites}/${CLOUD_DOMAIN}"
CONF="$MANAGED_DIR/15-cloud-app.conf"

mkdir -p "$MANAGED_DIR" "$ACME_ROOT/.well-known/acme-challenge" /var/log/nginx/hyper-cloud

# The old HYPER-HOST website with the same domain must never win SNI/routing.
rm -f "$MANAGED_DIR/20-site-${CLOUD_DOMAIN}.conf" 2>/dev/null || true
if [[ -d "$SITE_DIR" ]]; then
  touch "$SITE_DIR/.hyper-host-disabled" 2>/dev/null || true
fi

FPM_SOCK="${PHP_FPM_SOCK:-}"
if [[ -z "$FPM_SOCK" && -f /etc/hyper-host/hyper-host.conf ]]; then
  FPM_SOCK="$(sed -nE 's/^[[:space:]]*PHP_FPM_SOCK[[:space:]]*=[[:space:]]*["'"']?([^"'"'#[:space:]]+).*/\1/p' /etc/hyper-host/hyper-host.conf | tail -n1 || true)"
fi
if [[ -z "$FPM_SOCK" || ! -S "$FPM_SOCK" ]]; then
  FPM_SOCK="$(find /run/php -maxdepth 1 -type s -name 'php*-fpm.sock' 2>/dev/null | sort -V | tail -n1 || true)"
fi
[[ -n "$FPM_SOCK" && -S "$FPM_SOCK" ]] || { echo "[HYPER CLOUD] PHP-FPM socket not found" >&2; exit 1; }

CERT=""
KEY=""
for base in /opt/hyper-host/letsencrypt/live /etc/letsencrypt/live; do
  c="$base/$CLOUD_DOMAIN/fullchain.pem"
  k="$base/$CLOUD_DOMAIN/privkey.pem"
  if [[ -f "$c" && -f "$k" ]] \
     && openssl x509 -in "$c" -noout -checkend 0 >/dev/null 2>&1 \
     && openssl x509 -in "$c" -noout -checkhost "$CLOUD_DOMAIN" >/dev/null 2>&1; then
    CERT="$c"; KEY="$k"; break
  fi
done

write_locations(){
  cat <<NGINX
    root $APP_ROOT/public;
    index index.php;
    charset utf-8;
    client_max_body_size 8192m;
    client_body_timeout 3600s;
    send_timeout 3600s;
    add_header X-Hyper-Cloud "v104" always;

    location = /__hyper_cloud_route__ {
        default_type text/plain;
        return 200 "HYPER_CLOUD_V104";
    }

    location ^~ /.well-known/acme-challenge/ {
        root $ACME_ROOT;
        default_type text/plain;
        try_files \$uri =404;
        allow all;
    }

    location / {
        try_files \$uri \$uri/ /index.php?\$query_string;
    }

    location ~ \.php$ {
        try_files \$uri =404;
        include snippets/fastcgi-php.conf;
        fastcgi_pass unix:$FPM_SOCK;
        fastcgi_connect_timeout 60s;
        fastcgi_send_timeout 3600s;
        fastcgi_read_timeout 3600s;
        fastcgi_request_buffering off;
    }

    location ~* \.(?:css|js|png|jpg|jpeg|gif|webp|svg|ico|woff|woff2|ttf|otf)$ {
        expires 1d;
        add_header Cache-Control "public, max-age=86400";
        add_header X-Hyper-Cloud "v104" always;
        try_files \$uri =404;
    }

    location ~ /\.(?!well-known) { deny all; }
    location = /favicon.ico { log_not_found off; access_log off; }
NGINX
}

{
  cat <<NGINX
# HYPER CLOUD v104 — reserved standalone application.
# Generated by /opt/hyper-host/bin/hyper-cloud-nginx-fragment.sh
server {
    listen 80;
    listen [::]:80;
    server_name $CLOUD_DOMAIN;
    access_log /var/log/nginx/hyper-cloud/access.log;
    error_log /var/log/nginx/hyper-cloud/error.log;
NGINX
  if [[ -n "$CERT" ]]; then
    cat <<NGINX
    location ^~ /.well-known/acme-challenge/ {
        root $ACME_ROOT;
        default_type text/plain;
        try_files \$uri =404;
        allow all;
    }
    location / { return 301 https://\$host\$request_uri; }
NGINX
  else
    write_locations
  fi
  echo "}"

  if [[ -n "$CERT" ]]; then
    cat <<NGINX
server {
    listen 443 ssl http2;
    listen [::]:443 ssl http2;
    server_name $CLOUD_DOMAIN;
    ssl_certificate $CERT;
    ssl_certificate_key $KEY;
    ssl_protocols TLSv1.2 TLSv1.3;
    access_log /var/log/nginx/hyper-cloud/access-ssl.log;
    error_log /var/log/nginx/hyper-cloud/error-ssl.log;
NGINX
    write_locations
    echo "}"
  fi
} > "$CONF"

chmod 0644 "$CONF"
printf '[HYPER CLOUD] managed vhost: %s -> %s/public (ssl=%s)\n' "$CLOUD_DOMAIN" "$APP_ROOT" "$([[ -n "$CERT" ]] && echo yes || echo no)"
