<?php
declare(strict_types=1);
require __DIR__.'/../app/bootstrap.php';require __DIR__.'/../app/filelib.php';
header('X-Content-Type-Options: nosniff');header('Referrer-Policy: no-referrer');header('Cache-Control: private, no-store, max-age=0');header('X-Frame-Options: SAMEORIGIN');header('Permissions-Policy: camera=(), microphone=(), geolocation=(), payment=()');header("Content-Security-Policy: default-src 'self'; style-src 'self' 'unsafe-inline' https://cdnjs.cloudflare.com; script-src 'self' 'unsafe-inline'; font-src 'self' https://cdnjs.cloudflare.com data:; img-src 'self' data:; frame-src 'self'; object-src 'none'; base-uri 'none'; form-action 'self'; frame-ancestors 'self'");
$user=require_auth();$space=hcfl_space((string)($_GET['space']??'private'));$rel='';$entry='';$error='';$token='';$resource='';$title='Предпросмотр сайта';
try{
    $rel=hcfl_clean_rel((string)($_GET['path']??''));if($rel==='')throw new RuntimeException('HTML-файл не выбран');[,,$path]=hcfl_resolve($user,$space,$rel,true);if(!is_file($path))throw new RuntimeException('Файл не найден');$entry=trim((string)($_GET['entry']??''));
    if($entry!==''){$entry=hcfl_entry_clean($entry);if(!hcfl_html_name($entry))throw new RuntimeException('Выбранный файл не является HTML');if(!hcfl_archive_name($path))throw new RuntimeException('Архив не найден');$root=dirname($entry);if($root==='.')$root='';$payload=['uid'=>(int)$user['id'],'space'=>$space,'archive'=>$rel,'root'=>$root];$resource=$root!==''?(string)substr($entry,strlen($root)+1):$entry;$title=basename($entry);}
    else{if(!hcfl_html_name($path))throw new RuntimeException('Выбранный файл не является HTML');$root=dirname($rel);if($root==='.')$root='';$payload=['uid'=>(int)$user['id'],'space'=>$space,'archive'=>'','root'=>$root];$resource=$root!==''?(string)substr($rel,strlen($root)+1):$rel;$title=basename($rel);}
    $token=hcfl_preview_token($payload,3600);
}catch(Throwable $e){$error=$e->getMessage();http_response_code(400);}
$src=$error===''?hcfl_preview_url($token,$resource):'';
?>
<!doctype html><html lang="ru"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title><?=e($title)?> — HYPER CLOUD Preview</title><link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.7.2/css/all.min.css"><style>html,body{margin:0;width:100%;height:100%;background:#111827;font-family:Inter,system-ui,-apple-system,Segoe UI,sans-serif}.bar{height:54px;display:flex;align-items:center;gap:12px;padding:0 14px;background:#0c1220;border-bottom:1px solid #202a3e;color:#dce5f6;box-sizing:border-box}.dots{display:flex;gap:6px}.dots i{width:10px;height:10px;border-radius:50%;background:#ff5f57}.dots i:nth-child(2){background:#febc2e}.dots i:nth-child(3){background:#28c840}.address{flex:1;height:34px;border:1px solid #27334c;background:#121a2c;border-radius:10px;display:flex;align-items:center;gap:9px;padding:0 12px;min-width:0;color:#8fa0bd;font-size:12px}.address span{overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.btn{width:36px;height:36px;border:1px solid #27334c;background:#141d30;color:#d7e1f2;border-radius:10px;display:grid;place-items:center;text-decoration:none;cursor:pointer}.frame{display:block;width:100%;height:calc(100% - 54px);border:0;background:white}.err{height:100%;display:grid;place-items:center;color:#e7edf8;background:radial-gradient(circle at 50% 20%,#152646,#090e1a 55%)}.err>div{max-width:520px;padding:34px;text-align:center;border:1px solid #283651;border-radius:24px;background:#10182a}.err i{font-size:32px;color:#8194ff}.err h1{font-size:20px}.err p{color:#94a2ba;line-height:1.6}</style></head><body><?php if($error!==''):?><div class="err"><div><i class="fa-solid fa-window-restore"></i><h1>Не удалось открыть страницу</h1><p><?=e($error)?></p></div></div><?php else:?><div class="bar"><span class="dots"><i></i><i></i><i></i></span><div class="address"><i class="fa-solid fa-shield-halved"></i><span><?=e($entry!==''?basename($rel).' / '.$entry:$rel)?></span></div><button class="btn" type="button" onclick="document.getElementById('preview').contentWindow.location.reload()" title="Обновить"><i class="fa-solid fa-rotate-right"></i></button><a class="btn" href="/editor.php?<?=e(http_build_query(array_filter(['space'=>$space,'path'=>$rel,'entry'=>$entry!==''?$entry:null],fn($v)=>$v!==null),'','&',PHP_QUERY_RFC3986))?>" title="Редактировать"><i class="fa-solid fa-code"></i></a></div><iframe id="preview" class="frame" sandbox="allow-scripts allow-forms allow-modals allow-popups allow-downloads" referrerpolicy="no-referrer" src="<?=e($src)?>"></iframe><?php endif;?></body></html>
