<?php
declare(strict_types=1);
require __DIR__.'/../app/bootstrap.php';require __DIR__.'/../app/filelib.php';
header('X-Content-Type-Options: nosniff');header('Referrer-Policy: no-referrer');header('Cache-Control: private, no-store, max-age=0');header('Permissions-Policy: camera=(), microphone=(), geolocation=(), payment=()');
try{
    $payload=hcfl_preview_verify((string)($_GET['t']??''));$uid=(int)($payload['uid']??0);$user=hc_cloud_user_by_id($uid);if(!$user)throw new RuntimeException('Предпросмотр недоступен');$space=hcfl_space((string)($payload['space']??'private'));$root=hcfl_clean_rel((string)($payload['root']??''));$resource=hcfl_clean_rel((string)($_GET['r']??''));if($resource==='')throw new RuntimeException('Ресурс не найден');if(!hcfl_web_asset_allowed($resource))throw new RuntimeException('Тип ресурса запрещён');$archive=hcfl_clean_rel((string)($payload['archive']??''));$full=trim(($root!==''?$root.'/':'').$resource,'/');
    if($archive!==''){[,,$archivePath]=hcfl_resolve($user,$space,$archive,true);if(!is_file($archivePath)||!hcfl_archive_name($archivePath))throw new RuntimeException('Архив недоступен');$data=hcfl_archive_read_bytes($archivePath,$full,33554432);$body=(string)$data['content'];}
    else{[,,$path]=hcfl_resolve($user,$space,$full,true);if(!is_file($path))throw new RuntimeException('Ресурс не найден');$size=(int)(@filesize($path)?:0);if($size>67108864)throw new RuntimeException('Ресурс слишком большой для предпросмотра');$body=@file_get_contents($path);if(!is_string($body))throw new RuntimeException('Ресурс недоступен');}
    $ext=strtolower(pathinfo($resource,PATHINFO_EXTENSION));if(in_array($ext,['html','htm'],true)){$body=hcfl_rewrite_html($body,$full,$root,(string)($_GET['t']??''));header("Content-Security-Policy: sandbox allow-scripts allow-forms allow-modals allow-popups allow-downloads; default-src 'self' data: blob: https:; script-src 'self' 'unsafe-inline' 'unsafe-eval' https:; style-src 'self' 'unsafe-inline' https:; img-src 'self' data: blob: https:; media-src 'self' blob: https:; font-src 'self' data: https:; connect-src 'self' https:; frame-src https:; object-src 'none'; base-uri 'none'");}
    elseif($ext==='css')$body=hcfl_rewrite_css($body,$full,$root,(string)($_GET['t']??''));elseif(in_array($ext,['js','mjs','cjs'],true))$body=hcfl_rewrite_js($body,$full,$root,(string)($_GET['t']??''));
    header('Content-Type: '.hcfl_mime_name($resource));header('Content-Length: '.strlen($body));echo $body;
}catch(Throwable $e){http_response_code(404);header('Content-Type: text/plain; charset=utf-8');echo 'Resource unavailable';}
