<?php
declare(strict_types=1);
require dirname(__DIR__).'/app/bootstrap.php';
$page=(string)($_GET['page']??'dashboard');

if($page==='logout'){ audit('logout'); session_destroy(); redirect('/?page=login'); }
if($page==='login'){
    if(current_user()) redirect('/');
    $err='';
    if($_SERVER['REQUEST_METHOD']==='POST'){
        check_csrf(); $u=trim((string)($_POST['username']??''));$p=(string)($_POST['password']??'');
        $st=db()->prepare('SELECT * FROM users WHERE username=?');$st->execute([$u]);$row=$st->fetch();
        if($row&&password_verify($p,(string)$row['password_hash'])){ session_regenerate_id(true);$_SESSION['uid']=(int)$row['id'];audit('login','successful');redirect('/'); }
        $err='Неверный логин или пароль';
    }
    ?><!doctype html><html lang="ru"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>CS 1.6 Hosting — HYPER-HOST</title><link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"><link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.6.0/css/all.min.css" rel="stylesheet"><link href="/assets/style.css?v=16" rel="stylesheet"></head><body class="login-page"><div class="login-glow g1"></div><div class="login-glow g2"></div><main class="login-wrap"><section class="login-card"><div class="brand-icon"><i class="fa-solid fa-crosshairs"></i></div><div class="eyebrow">HYPER-HOST</div><h1>CS 1.6 Hosting</h1><p>Управление игровыми серверами</p><?php if($err):?><div class="alert alert-danger"><?=e($err)?></div><?php endif;?><form method="post" class="vstack gap-3"><?=csrf_field()?><label><span>Логин</span><input class="form-control form-control-lg" name="username" required autofocus autocomplete="username"></label><label><span>Пароль</span><input class="form-control form-control-lg" type="password" name="password" required autocomplete="current-password"></label><button class="btn btn-primary btn-lg"><i class="fa-solid fa-right-to-bracket me-2"></i>Войти</button></form></section></main></body></html><?php exit;
}
$user=require_auth();

if($_SERVER['REQUEST_METHOD']==='POST'){
    check_csrf(); $action=(string)($_POST['action']??'');
    try{
        if($action==='create_server'){
            $name=trim((string)($_POST['name']??''));$hostname=trim((string)($_POST['hostname']??$name));$port=(int)($_POST['port']??27015);$slots=(int)($_POST['slots']??16);$map=trim((string)($_POST['start_map']??'de_dust2'));$profile=(string)($_POST['profile']??'classic');$password=(string)($_POST['server_password']??'');
            if($name===''||mb_strlen($name)>96) throw new RuntimeException('Проверь название сервера'); if($port<27015||$port>27100)throw new RuntimeException('Порт 27015–27100'); if($slots<1||$slots>32)throw new RuntimeException('Слоты 1–32: это реальный лимит GoldSrc/ReHLDS'); if(!preg_match('/^[A-Za-z0-9_-]{1,64}$/',$map))throw new RuntimeException('Некорректная стартовая карта'); if(!in_array($profile,['classic','rehlds'],true))$profile='classic';
            $public=(string)cfg('public_ip','');
            // A failed/incomplete previous install may already own this port. Reuse that row instead of crashing on uq_servers_port.
            $check=db()->prepare('SELECT * FROM servers WHERE port=? LIMIT 1');$check->execute([$port]);$existing=$check->fetch();
            $reused=false;
            if($existing){
                $state=(string)($existing['status_cache']??'');$installed=(int)($existing['installed']??0);
                if($installed===1 && !in_array($state,['failed','installing'],true)) throw new RuntimeException('Порт '.$port.' уже занят сервером #'.(int)$existing['id'].' «'.(string)$existing['name'].'»');
                $id=(int)$existing['id'];$reused=true;
                db()->prepare('UPDATE servers SET name=?,hostname=?,public_ip=?,slots=?,start_map=?,build_profile=?,installed=0,status_cache=? WHERE id=?')->execute([$name,$hostname,$public,$slots,$map,$profile,'installing',$id]);
            } else {
                $st=db()->prepare('INSERT INTO servers(name,hostname,public_ip,port,slots,start_map,build_profile,status_cache) VALUES(?,?,?,?,?,?,?,?)');$st->execute([$name,$hostname,$public,$port,$slots,$map,$profile,'installing']);$id=(int)db()->lastInsertId();
            }
            $r=ctl(['server-create',$id,'--name',$name,'--port',$port,'--slots',$slots,'--map',$map,'--hostname',$hostname,'--password',$password,'--profile',$profile],1800);
            if(empty($r['ok'])){db()->prepare('UPDATE servers SET installed=0,status_cache=? WHERE id=?')->execute(['failed',$id]);throw new RuntimeException((string)($r['error']??'Не удалось установить HLDS'));}
            db()->prepare('UPDATE servers SET installed=1,status_cache=?,ftp_user=?,ftp_password=? WHERE id=?')->execute(['starting',(string)($r['ftp_user']??''),(string)($r['ftp_password']??''),$id]);audit($reused?'server_recover':'server_create',$name,$id);flash(($reused?'Незавершённый сервер восстановлен и запускается. ':'Сервер установлен и запускается. ').'FTP: '.($r['ftp_user']??'создан'));redirect('/?page=server&id='.$id);
        }
        if($action==='server_power'){
            $id=(int)($_POST['id']??0);$op=(string)($_POST['op']??'');if(!in_array($op,['start','stop','restart'],true))throw new RuntimeException('Неизвестная команда');$r=ctl([$op,$id],90);if(empty($r['ok']))throw new RuntimeException((string)($r['error']??'Команда не выполнена'));audit('server_'.$op,'',$id);flash('Команда '.$op.' выполнена');redirect('/?page=server&id='.$id);
        }
        if($action==='server_maintenance'){
            $id=(int)($_POST['id']??0);$op=(string)($_POST['op']??'');if(!in_array($op,['update','reinstall'],true))throw new RuntimeException('Неизвестная операция');$r=ctl([$op,$id],1800);if(empty($r['ok']))throw new RuntimeException((string)($r['error']??'Операция не выполнена'));audit('server_'.$op,(string)($r['backup']??''),$id);flash($op==='update'?'Файлы сервера обновлены':'Сервер переустановлен; важные AMXX-конфиги сохранены в backup');redirect('/?page=server&id='.$id);
        }
        if($action==='save_server_settings'){
            $id=(int)($_POST['id']??0);$s=server_row($id);$hostname=trim((string)($_POST['hostname']??''));$port=(int)($_POST['port']??$s['port']);$slots=(int)($_POST['slots']??16);$map=trim((string)($_POST['start_map']??'de_dust2'));$password=(string)($_POST['server_password']??'');$rcon=trim((string)($_POST['rcon_password']??''));
            if($hostname===''||mb_strlen($hostname)>160)throw new RuntimeException('Проверь Hostname');if($port<27015||$port>27100)throw new RuntimeException('Порт 27015–27100');if($slots<1||$slots>32)throw new RuntimeException('Слоты 1–32');if(!preg_match('/^[A-Za-z0-9_-]{1,64}$/',$map))throw new RuntimeException('Некорректная стартовая карта');
            $owner=db()->prepare('SELECT id,name FROM servers WHERE port=? AND id<>? LIMIT 1');$owner->execute([$port,$id]);$busy=$owner->fetch();if($busy)throw new RuntimeException('Порт '.$port.' уже занят сервером #'.(int)$busy['id'].' «'.(string)$busy['name'].'»');
            $args=['config-set',$id,'--hostname',$hostname,'--port',$port,'--slots',$slots,'--map',$map,'--password',$password];if($rcon!==''){$args[]='--rcon';$args[]=$rcon;}$r=ctl($args,90);if(empty($r['ok']))throw new RuntimeException((string)($r['error']??'Не удалось сохранить настройки'));
            try{db()->prepare('UPDATE servers SET hostname=?,port=?,slots=?,start_map=? WHERE id=?')->execute([$hostname,$port,$slots,$map,$id]);}catch(PDOException $e){if((string)$e->getCode()==='23000')throw new RuntimeException('Порт '.$port.' уже занят другим сервером');throw $e;}
            audit('server_settings','hostname/port/slots/map',$id);flash('Настройки сохранены. Изменения порта, слотов и стартовой карты применятся после рестарта сервера.');redirect('/?page=server&id='.$id);
        }
        if($action==='ftp_reset'){
            $id=(int)($_POST['id']??0);$r=ctl(['ftp-reset',$id],120);if(empty($r['ok']))throw new RuntimeException((string)($r['error']??($r['test']['error']??'FTP password reset failed')));db()->prepare('UPDATE servers SET ftp_user=?,ftp_password=? WHERE id=?')->execute([(string)$r['ftp_user'],(string)$r['ftp_password'],$id]);audit('ftp_reset','',$id);flash('FTP-пароль обновлён и доступ к корню сервера перепроверен');redirect('/?page=server&id='.$id.'#ftp');
        }
        if($action==='ftp_repair'){
            $id=(int)($_POST['id']??0);$r=ctl(['ftp-repair',$id],180);if(empty($r['ok']))throw new RuntimeException((string)($r['warning']??($r['test']['error']??'FTP repair failed')));db()->prepare('UPDATE servers SET ftp_user=?,ftp_password=? WHERE id=?')->execute([(string)$r['ftp_user'],(string)$r['ftp_password'],$id]);audit('ftp_repair',(string)($r['root']??''),$id);flash('FTP исправлен: вход открывается прямо в корне игрового сервера');redirect('/?page=server&id='.$id.'#ftp');
        }
        if($action==='upload_map'){
            $id=(int)($_POST['id']??0); server_row($id); [$token,$original]=stage_upload($_FILES['map_file']??[],'map','.bsp',256*1024*1024); $map=pathinfo($original,PATHINFO_FILENAME); if(!preg_match('/^[A-Za-z0-9_-]{1,64}$/',$map)){@unlink('/var/lib/hyper-cs16/uploads/'.$token);throw new RuntimeException('Имя BSP: только латиница, цифры, _ и -');}$r=ctl(['map-upload',$id,$token,$map],120);if(empty($r['ok']))throw new RuntimeException((string)($r['error']??'Upload failed'));audit('map_upload',(string)($r['map']??''),$id);flash('Карта загружена: '.($r['map']??''));redirect('/?page=server&id='.$id.'#maps');
        }
        if($action==='upload_plugin'){
            $id=(int)($_POST['id']??0); server_row($id); [$token,$original]=stage_upload($_FILES['plugin_file']??[],'plugin','.amxx',32*1024*1024); if(!preg_match('/^[A-Za-z0-9_.-]{1,91}\.amxx$/',$original)){@unlink('/var/lib/hyper-cs16/uploads/'.$token);throw new RuntimeException('Некорректное имя AMXX плагина');}$r=ctl(['plugin-upload',$id,$token,$original],120);if(empty($r['ok']))throw new RuntimeException((string)($r['error']??'Upload failed'));audit('plugin_upload',$original,$id);flash('AMXX плагин загружен: '.$original);redirect('/?page=server&id='.$id.'#plugins');
        }
        if($action==='delete_server'){
            $id=(int)($_POST['id']??0);$s=server_row($id);if((string)($_POST['confirm']??'')!=='DELETE')throw new RuntimeException('Для удаления введи DELETE');$r=ctl(['delete',$id],180);if(empty($r['ok']))throw new RuntimeException((string)($r['error']??'Delete failed'));db()->prepare('DELETE FROM servers WHERE id=?')->execute([$id]);audit('server_delete',(string)$s['name'],null);flash('Сервер удалён');redirect('/');
        }
        if($action==='change_password'){
            $old=(string)($_POST['old_password']??'');$new=(string)($_POST['new_password']??'');if(strlen($new)<10)throw new RuntimeException('Новый пароль минимум 10 символов');$st=db()->prepare('SELECT password_hash FROM users WHERE id=?');$st->execute([(int)$user['id']]);$hash=(string)$st->fetchColumn();if(!password_verify($old,$hash))throw new RuntimeException('Старый пароль неверный');db()->prepare('UPDATE users SET password_hash=? WHERE id=?')->execute([password_hash($new,PASSWORD_DEFAULT),(int)$user['id']]);audit('password_change');flash('Пароль изменён');redirect('/?page=settings');
        }
    } catch(Throwable $ex){ $msg=$ex->getMessage(); if($ex instanceof PDOException && (string)$ex->getCode()==='23000' && str_contains($msg,'uq_servers_port')){$msg='Этот UDP-порт уже занят другим игровым сервером. Выбери свободный порт 27015–27100.';} flash($msg,'danger'); $back=(string)($_SERVER['HTTP_REFERER']??'/'); header('Location: '.$back); exit; }
}

$servers=all_servers();$flash=flash();
$total=count($servers);$online=count(array_filter($servers,fn($s)=>$s['status_cache']==='online'));$players=array_sum(array_map(fn($s)=>(int)$s['players_online'],$servers));$ram=array_sum(array_map(fn($s)=>(float)$s['memory_mb'],$servers));
function status_badge(string $s): string { $m=['online'=>['success','ONLINE'],'offline'=>['secondary','OFFLINE'],'starting'=>['warning','STARTING'],'installing'=>['info','INSTALL'],'unreachable'=>['danger','NO QUERY'],'failed'=>['danger','FAILED']];$v=$m[$s]??['secondary',strtoupper($s)];return '<span class="badge text-bg-'.$v[0].' status-badge">'.e($v[1]).'</span>'; }
$titles=['dashboard'=>'Игровые серверы','server'=>'Управление сервером','create'=>'Новый сервер','settings'=>'Настройки панели','audit'=>'История действий'];$title=$titles[$page]??'CS 1.6 Hosting';
?><!doctype html><html lang="ru"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title><?=e($title)?> — HYPER-HOST</title><link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"><link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.6.0/css/all.min.css" rel="stylesheet"><link href="/assets/style.css?v=16" rel="stylesheet"></head><body><div class="app-shell">
<aside class="side"><a class="brand" href="/"><span><i class="fa-solid fa-crosshairs"></i></span><div><b>HYPER-HOST</b><small>CS 1.6 CONTROL</small></div></a><div class="host-pill"><i class="fa-solid fa-circle-nodes"></i><div><b><?=e((string)cfg('domain'))?></b><small><?=e((string)cfg('public_ip'))?></small></div></div><nav><a class="<?=($page==='dashboard'||$page==='server')?'active':''?>" href="/"><i class="fa-solid fa-server"></i>Серверы</a><a class="<?=$page==='create'?'active':''?>" href="/?page=create"><i class="fa-solid fa-plus"></i>Создать сервер</a><a class="<?=$page==='audit'?'active':''?>" href="/?page=audit"><i class="fa-solid fa-clock-rotate-left"></i>История</a><a class="<?=$page==='settings'?'active':''?>" href="/?page=settings"><i class="fa-solid fa-gear"></i>Настройки</a></nav><div class="side-bottom"><div class="userbox"><i class="fa-solid fa-user-shield"></i><div><b><?=e($user['username'])?></b><small><?=e($user['role'])?></small></div></div><a class="logout" href="/?page=logout"><i class="fa-solid fa-arrow-right-from-bracket"></i>Выйти</a></div></aside>
<main class="main"><header class="top"><div><span class="kicker">CS 1.6 HOSTING</span><h1><?=e($title)?></h1></div><div class="top-actions"><a class="btn btn-primary" href="/?page=create"><i class="fa-solid fa-plus me-2"></i>Новый сервер</a></div></header><?php if($flash):?><div class="alert alert-<?=e($flash['type'])?> shadow-sm"><?=nl2br(e($flash['message']))?></div><?php endif;?>
<?php if($page==='dashboard'): ?>
<section class="stats-grid"><div class="metric"><span><i class="fa-solid fa-server"></i></span><div><small>Серверов</small><b><?=$total?></b></div></div><div class="metric"><span><i class="fa-solid fa-signal"></i></span><div><small>Онлайн</small><b><?=$online?></b></div></div><div class="metric"><span><i class="fa-solid fa-users"></i></span><div><small>Игроков</small><b><?=$players?></b></div></div><div class="metric"><span><i class="fa-solid fa-memory"></i></span><div><small>RAM серверов</small><b><?=e(fmt_mb($ram))?></b></div></div></section>
<section class="panel-card"><div class="panel-head"><div><h2>Мои серверы</h2><p>HLDS / ReHLDS, AMX Mod X, FTP и RCON</p></div></div><div class="server-list"><?php if(!$servers):?><div class="empty"><i class="fa-solid fa-gamepad"></i><h3>Серверов пока нет</h3><p>Создай первый CS 1.6 сервер — порт, слоты и AMXX настроятся автоматически.</p><a class="btn btn-primary" href="/?page=create">Создать сервер</a></div><?php endif;?><?php foreach($servers as $s):?><a class="server-row" href="/?page=server&id=<?=(int)$s['id']?>"><div class="server-state <?=e($s['status_cache'])?>"><i class="fa-solid fa-power-off"></i></div><div class="server-main"><div><b><?=e($s['name'])?></b><?=status_badge((string)$s['status_cache'])?></div><span><?=e($s['public_ip'])?>:<?=(int)$s['port']?> · <?=e($s['current_map']?:$s['start_map'])?></span></div><div class="server-kpi"><small>Игроки</small><b><?=(int)$s['players_online']?> / <?=(int)($s['max_players']?:$s['slots'])?></b></div><div class="server-kpi"><small>CPU</small><b><?=number_format((float)$s['cpu_percent'],1)?>%</b></div><div class="server-kpi"><small>RAM</small><b><?=e(fmt_mb((float)$s['memory_mb']))?></b></div><i class="fa-solid fa-chevron-right arrow"></i></a><?php endforeach;?></div></section>
<?php elseif($page==='create'): ?>
<section class="form-layout"><div class="panel-card"><div class="panel-head"><div><h2>Новый Counter-Strike 1.6 сервер</h2><p>После создания панель установит игру, AMXX, FTP и systemd.</p></div></div><form method="post" class="form-grid"><?=csrf_field()?><input type="hidden" name="action" value="create_server"><label class="wide"><span>Название в панели</span><input class="form-control" name="name" value="PIXEL-PC CS 1.6" required></label><label class="wide"><span>Hostname в игре</span><input class="form-control" name="hostname" value="PIXEL-PC | Counter-Strike 1.6" required></label><label><span>Порт</span><input class="form-control" type="number" name="port" min="27015" max="27100" value="27015" required></label><label><span>Слоты <small class="text-secondary">(макс. 32)</small></span><select class="form-select" name="slots"><?php foreach([10,12,16,20,24,28,32] as $n):?><option <?=$n===16?'selected':''?>><?=$n?></option><?php endforeach;?></select></label><label><span>Стартовая карта</span><input class="form-control" name="start_map" value="de_dust2" required></label><label><span>Сборка</span><select class="form-select" name="profile"><option value="classic">Обычный HLDS + AMXX</option><option value="rehlds">ReHLDS + ReGameDLL + AMXX</option></select></label><label class="wide"><span>Пароль сервера (необязательно)</span><input class="form-control" name="server_password" autocomplete="off"></label><div class="wide callout"><i class="fa-solid fa-circle-info"></i><div><b>IP сервера</b><p><?=e((string)cfg('public_ip'))?>:порт. Убедись, что UDP-порты проброшены на роутере, если сервер за NAT.</p></div></div><div class="wide"><button class="btn btn-primary btn-lg"><i class="fa-solid fa-download me-2"></i>Установить сервер</button></div></form></div></section>
<?php elseif($page==='server'): $id=(int)($_GET['id']??0);$s=server_row($id);$lanIp=(string)cfg('lan_ip',''); ?>
<section class="server-hero"><div><div class="d-flex align-items-center gap-2 mb-2"><?=status_badge((string)$s['status_cache'])?><span class="profile-pill"><?=e(strtoupper((string)$s['build_profile']))?></span></div><h2><?=e($s['name'])?></h2><div class="connect-stack"><div class="connect-line"><span class="connect-label">Интернет</span><code id="connectAddressPublic"><?=e($s['public_ip'])?>:<?=(int)$s['port']?></code><button type="button" class="icon-btn" data-copy="#connectAddressPublic" title="Скопировать"><i class="fa-regular fa-copy"></i></button></div><?php if($lanIp!==''):?><div class="connect-line"><span class="connect-label">Локально</span><code id="connectAddressLan"><?=e($lanIp)?>:<?=(int)$s['port']?></code><button type="button" class="icon-btn" data-copy="#connectAddressLan" title="Скопировать"><i class="fa-regular fa-copy"></i></button></div><?php endif;?></div></div><div class="power-actions"><form method="post"><?=csrf_field()?><input type="hidden" name="action" value="server_power"><input type="hidden" name="id" value="<?=$id?>"><button name="op" value="start" class="btn btn-success" title="Запустить"><i class="fa-solid fa-play"></i></button><button name="op" value="restart" class="btn btn-warning" title="Перезапустить"><i class="fa-solid fa-rotate"></i></button><button name="op" value="stop" class="btn btn-danger" title="Остановить"><i class="fa-solid fa-stop"></i></button></form><form method="post" onsubmit="return confirm('Удалить сервер <?=e($s['name'])?> со всеми файлами и FTP? Это действие необратимо.')"><?=csrf_field()?><input type="hidden" name="action" value="delete_server"><input type="hidden" name="id" value="<?=$id?>"><input type="hidden" name="confirm" value="DELETE"><button class="btn btn-danger delete-hero" title="Удалить сервер"><i class="fa-solid fa-trash"></i></button></form></div></section>
<div class="live-grid"><div class="live-card"><small>Игроки</small><b id="livePlayers"><?=(int)$s['players_online']?> / <?=(int)($s['max_players']?:$s['slots'])?></b></div><div class="live-card"><small>Карта</small><b id="liveMap"><?=e($s['current_map']?:$s['start_map'])?></b></div><div class="live-card"><small>CPU</small><b id="liveCpu"><?=number_format((float)$s['cpu_percent'],1)?>%</b></div><div class="live-card"><small>RAM</small><b id="liveRam"><?=e(fmt_mb((float)$s['memory_mb']))?></b></div><div class="live-card"><small>Диск</small><b id="liveDisk"><?=e(fmt_mb((float)$s['disk_mb']))?></b></div><div class="live-card"><small>Query ping</small><b id="livePing"><?=number_format((float)$s['ping_ms'],1)?> ms</b></div><div class="live-card"><small>Uptime</small><b id="liveUptime"><?=e(human_duration((int)$s['uptime_seconds']))?></b></div></div>
<div class="network-callout"><i class="fa-solid fa-network-wired"></i><div><b>Как подключаться</b><p>Если Counter-Strike запущен на компьютере в той же локальной сети, используй <code><?=e($lanIp!==''?$lanIp:$s['public_ip'])?>:<?=(int)$s['port']?></code>. Публичный адрес <code><?=e($s['public_ip'])?>:<?=(int)$s['port']?></code> нужен для игроков из интернета. Для внешнего доступа на роутере должен быть проброшен <b>UDP <?=(int)$s['port']?></b> на этот Ubuntu-сервер. NAT loopback на роутере может не работать, поэтому публичный IP из домашней сети не всегда подключается.</p><div class="network-actions"><button type="button" class="btn btn-soft btn-sm" id="networkCheck"><i class="fa-solid fa-stethoscope me-1"></i>Проверить HLDS/UDP/A2S</button><span id="networkCheckResult" class="network-check-result"></span></div></div></div>
<ul class="nav nav-pills server-tabs" id="serverTabs"><li><button class="active" data-bs-toggle="pill" data-bs-target="#overview">Обзор</button></li><li><button data-bs-toggle="pill" data-bs-target="#players">Игроки</button></li><li><button data-bs-toggle="pill" data-bs-target="#console">Консоль</button></li><li><button data-bs-toggle="pill" data-bs-target="#maps">Карты</button></li><li><button data-bs-toggle="pill" data-bs-target="#configs">Конфиги</button></li><li><button data-bs-toggle="pill" data-bs-target="#plugins">AMXX</button></li><li><button data-bs-toggle="pill" data-bs-target="#ftp">FTP</button></li><li><button data-bs-toggle="pill" data-bs-target="#logs">Логи</button></li><li><button data-bs-toggle="pill" data-bs-target="#danger">Сервис</button></li></ul>
<div class="tab-content">
<div class="tab-pane fade show active" id="overview"><div class="detail-grid"><section class="panel-card"><div class="panel-head"><div><h2>Статистика</h2><p>История за последние 24 часа из MariaDB</p></div></div><canvas id="statsChart" height="105"></canvas></section><section class="panel-card"><div class="panel-head"><div><h2>Основные настройки</h2></div></div><form method="post" class="vstack gap-3"><?=csrf_field()?><input type="hidden" name="action" value="save_server_settings"><input type="hidden" name="id" value="<?=$id?>"><label><span>Hostname</span><input class="form-control" name="hostname" value="<?=e($s['hostname'])?>"></label><div class="row g-3"><label class="col"><span>Порт UDP</span><input class="form-control" type="number" min="27015" max="27100" name="port" value="<?=(int)$s['port']?>"></label><label class="col"><span>Слоты <small class="text-secondary">(GoldSrc максимум 32)</small></span><input class="form-control" type="number" min="1" max="32" name="slots" value="<?=(int)$s['slots']?>"></label><label class="col"><span>Стартовая карта</span><input class="form-control" name="start_map" value="<?=e($s['start_map'])?>"></label></div><label><span>Пароль входа</span><input class="form-control" name="server_password" placeholder="Пусто = без пароля"></label><label><span>Новый RCON-пароль</span><input class="form-control" name="rcon_password" placeholder="Оставь пустым, чтобы не менять"></label><button class="btn btn-primary">Сохранить</button></form></section></div></div>
<div class="tab-pane fade" id="players"><section class="panel-card"><div class="panel-head"><div><h2>Игроки онлайн</h2><p>Данные напрямую с HLDS</p></div><button class="btn btn-soft" id="refreshPlayers">Обновить</button></div><div class="table-responsive"><table class="table hh-table"><thead><tr><th>#</th><th>Ник</th><th>Steam ID</th><th>IP</th><th>Счёт</th><th>Ping</th><th>На сервере</th><th></th></tr></thead><tbody id="playersBody"><tr><td colspan="8">Загрузка...</td></tr></tbody></table></div></section><section class="panel-card mt-3"><div class="panel-head"><div><h2>Недавние игроки</h2><p>История посещений из MariaDB</p></div></div><div class="table-responsive"><table class="table hh-table"><thead><tr><th>Ник</th><th>Steam ID</th><th>Первый визит</th><th>Последний визит</th><th>Визитов</th></tr></thead><tbody id="historyPlayersBody"><tr><td colspan="5">Загрузка...</td></tr></tbody></table></div></section></div>
<div class="tab-pane fade" id="console"><section class="panel-card"><div class="panel-head"><div><h2>RCON консоль</h2><p>Можно выполнять любые обычные серверные команды GoldSrc.</p></div></div><div class="console" id="consoleOut">Готово к работе.</div><form id="consoleForm" class="console-form"><input class="form-control" id="consoleCommand" placeholder="status, amxx plugins, meta list, sv_restart 1..." autocomplete="off"><button class="btn btn-primary">Выполнить</button></form><div class="quick-commands"><?php foreach(['status','stats','amxx plugins','amxx modules','meta list','users','version','sv_restart 1'] as $cmd):?><button class="btn btn-soft btn-sm" type="button" data-command="<?=e($cmd)?>"><?=e($cmd)?></button><?php endforeach;?></div></section></div>
<div class="tab-pane fade" id="maps"><section class="panel-card"><div class="panel-head"><div><h2>Карты</h2><p>Смена карты без перезапуска сервера</p></div><form method="post" enctype="multipart/form-data" class="map-upload"><?=csrf_field()?><input type="hidden" name="action" value="upload_map"><input type="hidden" name="id" value="<?=$id?>"><input class="form-control form-control-sm" type="file" name="map_file" accept=".bsp" required><button class="btn btn-primary btn-sm">Загрузить BSP</button></form></div><div id="mapGrid" class="map-grid"><span>Загрузка...</span></div></section></div>
<div class="tab-pane fade" id="configs"><section class="panel-card"><div class="panel-head"><div><h2>Редактор конфигов</h2><p>server.cfg, AMXX, админы и список плагинов</p></div><select id="configSelect" class="form-select config-select"><?php foreach(['server.cfg','amxx.cfg','users.ini','plugins.ini','modules.ini','mapcycle.txt','maps.ini'] as $f):?><option><?=e($f)?></option><?php endforeach;?></select></div><textarea id="configEditor" class="code-editor" spellcheck="false"></textarea><div class="mt-3 d-flex justify-content-end"><button id="saveConfig" class="btn btn-primary">Сохранить файл</button></div></section></div>
<div class="tab-pane fade" id="plugins"><section class="panel-card"><div class="panel-head"><div><h2>AMX Mod X</h2><p>Загрузка, включение и отключение .amxx плагинов</p></div><form method="post" enctype="multipart/form-data" class="map-upload"><?=csrf_field()?><input type="hidden" name="action" value="upload_plugin"><input type="hidden" name="id" value="<?=$id?>"><input class="form-control form-control-sm" type="file" name="plugin_file" accept=".amxx" required><button class="btn btn-primary btn-sm">Загрузить AMXX</button></form></div><div id="pluginList" class="plugin-list">Загрузка...</div><div class="callout mt-3"><i class="fa-solid fa-folder-open"></i><div><b>FTP тоже доступен</b><p>Полный путь: <code>cstrike/addons/amxmodx/plugins</code>. После загрузки плагин появится в списке, где его можно включить.</p></div></div></section></div>
<div class="tab-pane fade" id="ftp"><section class="panel-card"><div class="panel-head"><div><h2>FTP этого сервера</h2><p>Отдельный FTP-логин. После входа корень <code>/</code> — это непосредственно <code>/srv/hyper-cs16/servers/<?=$id?></code>.</p></div></div><div class="credentials ftp-credentials"><div><small>Хост из интернета</small><code><?=e((string)cfg('public_ip'))?></code></div><div><small>Хост из LAN</small><code><?=e($lanIp!==''?$lanIp:(string)cfg('public_ip'))?></code></div><div><small>Порт</small><code>21</code></div><div><small>Пассивные порты</small><code>40000–40100/TCP</code></div><div><small>Логин</small><code><?=e($s['ftp_user'])?></code></div><div><small>Пароль</small><code><?=e($s['ftp_password'])?></code></div><div><small>Корень после входа</small><code>/</code></div><div><small>Протокол</small><code>FTP / Explicit FTPS</code></div></div><div class="callout mt-3"><i class="fa-solid fa-circle-info"></i><div><b>FileZilla / WinSCP</b><p>Для подключения из интернета на роутере пробрось TCP 21 и TCP 40000–40100 на Ubuntu. Из локальной сети используй LAN IP. Этот FTP-пользователь не видит другие CS-серверы и попадает сразу в файлы сервера #<?=$id?>.</p></div></div><div class="d-flex flex-wrap gap-2 mt-3"><form method="post"><?=csrf_field()?><input type="hidden" name="action" value="ftp_repair"><input type="hidden" name="id" value="<?=$id?>"><button class="btn btn-primary"><i class="fa-solid fa-screwdriver-wrench me-2"></i>Проверить и исправить FTP</button></form><form method="post" onsubmit="return confirm('Сгенерировать новый FTP пароль?')"><?=csrf_field()?><input type="hidden" name="action" value="ftp_reset"><input type="hidden" name="id" value="<?=$id?>"><button class="btn btn-soft">Сгенерировать новый пароль</button></form></div></section></div>
<div class="tab-pane fade" id="logs"><section class="panel-card"><div class="panel-head"><div><h2>Журнал сервера</h2><p>systemd / stdout HLDS</p></div><button class="btn btn-soft" id="refreshLogs">Обновить</button></div><pre class="console log-console" id="logOut">Загрузка...</pre></section></div>
<div class="tab-pane fade" id="danger"><div class="detail-grid"><section class="panel-card"><div class="panel-head"><div><h2>Обслуживание</h2><p>Обновление и чистая переустановка</p></div></div><form method="post" class="vstack gap-2" onsubmit="return confirm('Продолжить операцию?')"><?=csrf_field()?><input type="hidden" name="action" value="server_maintenance"><input type="hidden" name="id" value="<?=$id?>"><button name="op" value="update" class="btn btn-soft"><i class="fa-solid fa-arrows-rotate me-2"></i>Проверить/обновить файлы Steam</button><button name="op" value="reinstall" class="btn btn-warning"><i class="fa-solid fa-rotate-left me-2"></i>Переустановить сборку</button></form></section><section class="panel-card danger-card"><div class="panel-head"><div><h2>Удаление</h2><p>Остановит service, удалит FTP и все файлы сервера.</p></div></div><form method="post" onsubmit="return confirm('ТОЧНО удалить сервер со всеми файлами?')"><?=csrf_field()?><input type="hidden" name="action" value="delete_server"><input type="hidden" name="id" value="<?=$id?>"><label><span>Напиши DELETE</span><input class="form-control" name="confirm" required></label><button class="btn btn-danger mt-3">Удалить сервер</button></form></section></div></div>
</div>
<?php elseif($page==='settings'): ?>
<section class="detail-grid"><div class="panel-card"><div class="panel-head"><div><h2>Панель</h2></div></div><div class="info-list"><div><span>Домен</span><b><?=e((string)cfg('domain'))?></b></div><div><span>Public IP</span><b><?=e((string)cfg('public_ip'))?></b></div><div><span>SQL</span><b><?=e((string)cfg('db_name'))?> @ <?=e((string)cfg('db_host'))?></b></div><div><span>Игровые файлы</span><b>/srv/hyper-cs16/servers</b></div></div></div><div class="panel-card"><div class="panel-head"><div><h2>Смена пароля</h2></div></div><form method="post" class="vstack gap-3"><?=csrf_field()?><input type="hidden" name="action" value="change_password"><input class="form-control" type="password" name="old_password" placeholder="Текущий пароль" required><input class="form-control" type="password" name="new_password" placeholder="Новый пароль (10+ символов)" minlength="10" required><button class="btn btn-primary">Изменить пароль</button></form></div></section>
<?php elseif($page==='audit'): $logs=db()->query('SELECT a.*,u.username,s.name server_name FROM audit_logs a LEFT JOIN users u ON u.id=a.user_id LEFT JOIN servers s ON s.id=a.server_id ORDER BY a.id DESC LIMIT 300')->fetchAll(); ?>
<section class="panel-card"><div class="panel-head"><div><h2>Последние действия</h2><p>До 300 записей</p></div></div><div class="table-responsive"><table class="table hh-table"><thead><tr><th>Дата</th><th>Пользователь</th><th>Действие</th><th>Сервер</th><th>Детали</th><th>IP</th></tr></thead><tbody><?php foreach($logs as $l):?><tr><td><?=e($l['created_at'])?></td><td><?=e($l['username']??'system')?></td><td><code><?=e($l['action'])?></code></td><td><?=e($l['server_name']??'—')?></td><td><?=e($l['details'])?></td><td><?=e($l['ip'])?></td></tr><?php endforeach;?></tbody></table></div></section>
<?php endif; ?>
</main></div><script>window.CS16={csrf:<?=json_encode(csrf_token())?>,serverId:<?=json_encode(isset($id)?$id:null)?>};</script><script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"></script><script src="https://cdn.jsdelivr.net/npm/chart.js@4.4.4/dist/chart.umd.min.js"></script><script src="/assets/app.js?v=16"></script></body></html>
